In [177]:
import sys

from numpy.testing.print_coercion_tables import print_coercion_table

# from time import process_time_ns

# from scipy.misc.tests.test_doccer import param_doc2

print("start")
print(sys.version)
import os
import pandas as pd

os.getcwd()

start
3.8.20 (default, Oct  3 2024, 10:22:23)
[Clang 14.0.6 ]

'/Users/lai_zx/PycharmProjects/HH_DB'

### 資料載入 PD_group nPD_group

In [178]:
df_PD_group = pd.read_csv('data/PD_group_utf8.csv')
df_nPD_group = pd.read_csv('data/nPD_group_utf8.csv')

In [179]:
print(df_nPD_group.info)
print(df_PD_group.info)

<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     $]$>^"^>%]{$  $]$>^"^>%]{$             1      12H       0     1
1     /%/;#[@""^]~  /%/;#[@""^]~             4      12H       0     1
2     <]<*]#:*-:;=  <]<*]#:*-:;=             2      12H       0     1
3     }%}_~#<^!-%!  }%}_~#<^!-%!             1       62       0     1
4     @]@[$-!~)@}*  @]@[$-!~)@}*             3      12H       0     1
...            ...           ...           ...      ...     ...   ...
5445  ;];;%>:&%"-@  ;];;%>:&%"-@             4      31Q       0     2
5446  ~]~/&]!-@"(%  #%#<}-:^-{%{             5       21       0     2
5447  @%@#&$]~]&!=  @%@#&$]~]&!=             2       62       0     2
5448  +%+!<<>^/&~+  +%+!<<>^/&~+             3      31Q       0     2
5449  _%_*"$[%<-_-  _%_*"$[%<-_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      1        1984        2  ...         0         0        0
1           0      1        1981        2  ...         0         0        0
2           0      1        1982        2  ...         0         0        0
3           0      1        1981        2  ...         0         0        0
4           0      1        1982        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
5445        0      2        1929        2  ...         0         0        0
5446        0      2        1926        2  ...         0         0        0
5447        0      2        1924        2  ...         0         0        0
5448        0      2        1925        2  ...         0         0        0
5449        0      2        1927        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            0         0        0         0   台北市   30  30-34
1            0         0        0         0   雲林縣   33  30-34
2            0         0        0         0   新竹縣   32  30-34
3            0         0        0         0   新北市   33  30-34
4            0         0        0         0   彰化縣   32  30-34
...        ...       ...      ...       ...   ...  ...         ...
5445         0         0        1         0   嘉義縣   85  85~
5446         0         0        0         0   屏東縣   88  85~
5447         0         0        0         0   新竹縣   90  85~
5448         0         0        1         0   台中市   89  85~
5449         0         0        0         0   嘉義市   87  85~

[5450 rows x 30 columns]>
<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     )]))<@%/-@/\  )]))<@%/-@/\             1      31Q       0     2
1     )])->[[_;"}+  )])->[[_;"}+             3       62       0     2
2     )])/;&*^})\_  )])/;&*^})\_             3      31Q       0     2
3     )%):~-[#[%/=  )%):~-[#[%/=             4      31Q       0     2
4     )%)_#)]_>)-{  )%)_#)]_>)-{             3      31Q       0     1
...            ...           ...           ...      ...     ...   ...
2720  (%({_[-}]%%/  (%({_[-}]%%/             5       62       0     2
2721  (%(/:#=${(<"  (%(/:#=${(<"             1       62       0     1
2722  (%(/&<[!>=^!  (%(/&<[!>=^!             1       62       0     2
2723  (%([]$!-$\]]  (%([]$!-$\]]             4      31Q       0     2
2724  (%(&<]")^&+<  (%(&<]")^&+<             4       62       0     1

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      2        1926        2  ...         1         0        0
1           0      2        1928        2  ...         1         0        0
2           0      2        1923        2  ...         0         0        0
3           0      2        1922        2  ...         0         0        0
4           0      1        1941        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
2720        0      2        1915        2  ...         0         0        1
2721        0      1        1974        2  ...         0         0        0
2722        0      2        1941        A  ...         0         0        1
2723        0      2        1933        2  ...         1         0        0
2724        0      1        1953        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            1         0        0         0   宜蘭縣   88  85~
1            0         1        0         0   南投縣   86  85~
2            0         1        0         0   彰化縣   91  85~
3            0         0        0         0   雲林縣   92  85~
4            0         0        0         0   南投縣   73  70-74
...        ...       ...      ...       ...   ...  ...         ...
2720         0         0        0         0   屏東縣   99  85~
2721         0         0        0         0   台北市   40  40-44
2722         1         0        1         0   新北市   73  70-74
2723         0         0        0         0   嘉義縣   81  80-84
2724         0         0        0         0   台南市   61  60-64

[2725 rows x 30 columns]>

### disease6

In [180]:
print(len(df_PD_group.query('disease6==1')))
print(len(df_nPD_group.query('disease6==1')))

276
374

## 比例

In [181]:
# 從PD_group 抽 有 disease6 
df_d6_DP_group = (df_PD_group.query('disease6==1')).sample(74)
df_d6_nDP_group = (df_nPD_group.query('disease6==1')).sample(230)
print(len(df_d6_DP_group.query(' disease6==1')))
print(len(df_d6_nDP_group.query(' disease6==1')))

74
230

In [182]:
df_d6_DP_group['ID1_S'] = df_d6_DP_group['ID1_S'].astype(str)
df_d6_DP_group['age_group'] = df_d6_DP_group['age_group'].astype(str)
print(df_d6_DP_group.dtypes)

ID               object
ID1              object
ID1_DIVISION      int64
ID1_UNIT         object
ID_ROC            int64
ID_S              int64
ID1_ROC           int64
ID1_S            object
ID_BIRTH_Y        int64
ID1_TYPE         object
ID_RELATION     float64
ID1_AMT         float64
ID1_IDENT        object
PREM_YM           int64
ID_STATUS         int64
ID1_MARK         object
FAM_CONT_Y      float64
FAM_CONT_N      float64
ID1_CITY          int64
PD                int64
disease1          int64
disease2          int64
disease3          int64
disease4          int64
disease5          int64
disease6          int64
disease7          int64
city             object
Age               int64
age_group        object
dtype: object

In [183]:
import pandas as pd

# 假设您的 DataFrame 是 df，并且其中有一列名为 'age_groups'
# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
df_d6_DP_group['age_group'] = df_d6_DP_group['age_group'].str.strip()
# 使用 value_counts() 方法统计每个年龄组的数量
#age_group_counts =df_d6_DP_group ['age_group'].value_counts()
age_group_counts = df_d6_DP_group['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_M = df_d6_DP_group.query('ID1_S==1')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d6_DP_group.query('ID1_S==2')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
print(age_group_counts)

# 显示结果
# print(age_group_counts)
# print(age_group_counts2)
# print(age_group_counts.index.tolist())
# print(all_age_groups)

age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     0
50-54     1
55-59     2
60-64     3
65-69     0
70-74    25
75-79    25
80-84     3
85~      15
Name: count, dtype: int64

In [184]:
import pandas as pd

# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']

# 数据清理
# 去除 'age_group' 列中值的前后空格
df_d6_DP_group['age_group'] = df_d6_DP_group['age_group'].str.strip()

# 确保 'ID1_S' 和 'ID' 列的数据类型正确
df_d6_DP_group['ID1_S'] = df_d6_DP_group['ID1_S'].astype(int)
df_d6_DP_group['ID'] = df_d6_DP_group['ID'].astype(str)

# 将 'age_group' 列转换为分类数据类型，确保顺序正确
df_d6_DP_group['age_group'] = pd.Categorical(df_d6_DP_group['age_group'], categories=all_age_groups, ordered=True)

# 按性别过滤数据
# 男性数据（ID1_S == 1）
df_d6_DP_M = df_d6_DP_group[df_d6_DP_group['ID1_S'] == 1]
df_d6_DP_F = df_d6_DP_group[df_d6_DP_group['ID1_S'] == 2]

# 按年龄组统计男性的 ID 数量
age_group_counts_M = df_d6_DP_M.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d6_DP_F.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
# 显示结果
print("男性各年龄组的 ID 数量：")
print(age_group_counts_M)
print(age_group_counts_F)
NP_PD_d6_M = age_group_counts_M.to_numpy()
NP_PD_d6_F = age_group_counts_F.to_numpy()
print(NP_PD_d6_M)

男性各年龄组的 ID 数量：
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     0
50-54     1
55-59     2
60-64     3
65-69     0
70-74    17
75-79     7
80-84     3
85~       0
Name: ID, dtype: int64
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     0
50-54     0
55-59     0
60-64     0
65-69     0
70-74     8
75-79    18
80-84     0
85~      15
Name: ID, dtype: int64
[ 0  0  0  0  0  0  0  0  0  0  1  2  3  0 17  7  3  0]

In [185]:
df_d6_DP_group.dtypes

ID                object
ID1               object
ID1_DIVISION       int64
ID1_UNIT          object
ID_ROC             int64
ID_S               int64
ID1_ROC            int64
ID1_S              int64
ID_BIRTH_Y         int64
ID1_TYPE          object
ID_RELATION      float64
ID1_AMT          float64
ID1_IDENT         object
PREM_YM            int64
ID_STATUS          int64
ID1_MARK          object
FAM_CONT_Y       float64
FAM_CONT_N       float64
ID1_CITY           int64
PD                 int64
disease1           int64
disease2           int64
disease3           int64
disease4           int64
disease5           int64
disease6           int64
disease7           int64
city              object
Age                int64
age_group       category
dtype: object

In [186]:
import pandas as pd

who2000 = pd.read_csv('data/who2000.csv')
# 定义所有可能的 `ID1_S` 和 `age_group` 组合
all_ID1_S = ['1', '2']
#all_age_groups = who2000['AGE']
# 确保 ID1_S 是整数类型
df_d6_nDP_group['ID1_S'] = df_d6_nDP_group['ID1_S'].astype(int)

# 确保 age_group 列没有多余空格
df_d6_nDP_group['age_group'] = df_d6_nDP_group['age_group'].str.strip()

all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
# 去除 'age_group' 列中值的前后空格
df_d6_DP_group['age_group'] = df_d6_DP_group['age_group'].str.strip()

# 创建 MultiIndex，包含所有可能的组合
index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])

# 男性组
# 男性组
whole_nPD_M = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d6_nDP_group[(df_d6_nDP_group['ID1_S'] == 1) & (df_d6_nDP_group['age_group'] == all_age_groups[i])]
    # 打印每个分组数据以调试
    #print(f"男性组第{i}组数据:\n", data)
    whole_nPD_M[i] = data if not data.empty else pd.DataFrame(columns=df_d6_nDP_group.columns).reindex(
        index=[(1, all_age_groups[i])])

# 女性组
whole_nPD_F = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d6_nDP_group.query(f'ID1_S == 2 and age_group == "{all_age_groups[i]}"')
    # 打印每个分组数据以调试
    print(f"女性组第{i}组数据:\n", data)
    whole_nPD_F[i] = data if not data.empty else pd.DataFrame(columns=df_d6_nDP_group.columns).reindex(
        index=[(2, all_age_groups[i])])

女性组第0组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第1组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第2组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第3组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第4组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第5组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第6组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第7组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第8组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第9组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第10组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3050  -]-_-$)^=/{#  -]-_-$)^=/{#             5       21       0     2
3042  >]>;]&%@#)^>  >]>;]&%@#)^>             2       32       0     2
3035  !]!%"/_>+(_:  !]!%"/_>+(_:             5       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3050        0      2        1961        2  ...         0         0        1
3042        0      2        1963        2  ...         0         0        1
3035        0      2        1963        2  ...         0         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3050         0         0        1         0   高雄市   53      50-54
3042         1         0        1         0   苗栗縣   51      50-54
3035         1         0        1         0   高雄市   51      50-54

[3 rows x 30 columns]
女性组第11组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3224  $]$!<$)$~)}~  $]$!<$)$~)}~             1      12H       0     2
3212  [][>^]]:%#+^  [][>^]]:%#+^             5       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3224        0      2        1958        2  ...         0         0        1
3212        0      2        1958        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3224         1         0        1         0   新北市   56      55-59
3212         0         0        1         0   高雄市   56      55-59

[2 rows x 30 columns]
女性组第12组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3275  ^]^@\#&$@+/!  ^]^@\#&$@+/!             3      31Q       0     2
3422  /%/@}$*%&\#_  /%/@}$*%&\#_             2       62       0     2
3277  [][[$#\^:#="  [][[$#\^:#="             1       21       0     2
3284  =]=\{@~-*&{<  =]=\{@~-*&{<             2       21       0     2
3349  &%&/)&$_!>:;  &%&/)&$_!>:;             1       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3275        0      2        1951        2  ...         0         1        0
3422        0      2        1954        A  ...         1         0        0
3277        0      2        1953        2  ...         0         0        0
3284        0      2        1954        2  ...         1         1        0
3349        0      2        1950        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3275         0         0        1         0   彰化縣   63      60-64
3422         1         0        1         0   新竹縣   60      60-64
3277         0         1        1         0   新北市   61      60-64
3284         1         0        1         0   桃園市   60      60-64
3349         0         0        1         0   台北市   64      60-64

[5 rows x 30 columns]
女性组第13组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3579  $]$]_$$#~;\&  $]$]_$$#~;\&             4       62       0     2
3510  <%<+-/~+-^*&  <%<+-/~+-^*&             3       62       0     2
3570  ~]~~}#&#;\!@  ~]~~}#&#;\!@             1       62       0     2
3536  #]#&&)&;>-^$  #]#&&)&;>-^$             5       21       0     2
3484  *%*=/{"=&\#>  *%*=/{"=&\#>             3       62       0     2
3529  <]<*(#^#&$=^  <]<*(#^#&$=^             1      31Q       0     2
3502  >]>][&-{&(~[  >]>][&-{&(~[             2      31Q       0     2
3580  {]{"+)(!!:[{  {]{"+)(!!:[{             1      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3579        0      2        1946        2  ...         1         0        0
3510        0      2        1948        A  ...         1         0        0
3570        0      2        1949        2  ...         1         0        0
3536        0      2        1948        2  ...         0         0        0
3484        0      2        1948        A  ...         0         0        1
3529        0      2        1948        2  ...         0         0        0
3502        0      2        1949        2  ...         0         0        0
3580        0      2        1948        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3579         1         0        1         0   台南市   68      65-69
3510         0         0        1         0   台中市   66      65-69
3570         1         1        1         0   台北市   65      65-69
3536         0         1        1         0   屏東縣   66      65-69
3484         0         0        1         0   台中市   66      65-69
3529         1         0        1         0   宜蘭縣   66      65-69
3502         0         0        1         0   苗栗縣   65      65-69
3580         0         1        1         0   宜蘭縣   66      65-69

[8 rows x 30 columns]
女性组第14组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3835  \]\~(<_</@[~  \]\~(<_</@[~             5      31Q       0     2
3985  )]):][^<_({^  )]):][^<_({^             3      31Q       0     2
3912  $]$)(]}_="\)  $]$)(]}_="\)             4      31Q       0     2
3727  &]&_$$[+>:!>  &]&_$$[+>:!>             5      31Q       0     2
3954  !%!@_$><+<;_  !%!@_$><+<;_             3      31Q       0     2
3971  ]]]!<$;(~<#)  ]]]!<$;(~<#)             1      31Q       0     2
3900  ~%~]*>>:$[<]  ~%~]*>>:$[<]             6       62       0     2
3730  &]&%]/!;<:*}  &]&%]/!;<:*}             3      31Q       0     2
3992  {%{>=#_>\;+>  {%{>=#_>\;+>             1       21       0     2
4084  <%<#~["<~;~:  <%<#~["<~;~:             3      12H       0     2
3611  %]%^_]#(##_!  %]%^_]#(##_!             4      31Q       0     2
3938  ]]]<{@^>@(_;  ]]]<{@^>@(_;             1      12H       0     2
4096  #]#!=>/")~"[  #]#!=>/")~"[             4      31Q       0     2
3769  !%![}$);+~\}  !%![}$);+~\}             4      31Q       0     2
3747  \]\]\$@@\(>*  \]\]\$@@\(>*             5       32       0     2
4011  "]"+"[$@_>(:  "]"+"[$@_>(:             4      31Q       0     2
4145  )%)[-</];#$<  )%)[-</];#$<             1       62       0     2
3736  %%%@>{{#][:-  %%%@>{{#][:-             5       62       0     2
3728  ~%~]*>>:$[<]  ~%~]*>>:$[<]             6       62       0     2
3849  *%*%:@+"(<-~  *%*%:@+"(<-~             3      31Q       0     2
3939  ~%~]*>>:$[<]  ~%~]*>>:$[<]             6       62       0     2
3681  @]@=_")}+<{$  @]@=_")}+<{$             1       21       0     2
3803  &%&%%#%/#%"#  &%&%%#%/#%"#             4      31Q       0     2
4091  \]\~(<_</@[~  \]\~(<_</@[~             5      31Q       0     2
4155  {]{:~&~;)#)[  {]{:~&~;)#)[             2       21       0     2
3758  <%<]/"~:{#+"  <%<]/"~:{#+"             1      12H       0     2
3625  >%>>>>;\}~"_  >%>>>>;\}~"_             6       62       0     2
3733  "]";&]"[:&+>  "]";&]"[:&+>             2       62       0     2
4165  _]_:;$@;/*#!  _]_:;$@;/*#!             1       62       0     2
3869  :%:>%/>:/"""  :%:>%/>:/"""             1       62       0     2
3796  !]![[")!%{#-  !]![[")!%{#-             5      31Q       0     2
3660  @%@;#{+%"\;!  @%@;#{+%"\;!             3       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3835        0      2        1942        2  ...         0         0        1
3985        0      2        1940        2  ...         0         0        1
3912        0      2        1943        2  ...         1         0        1
3727        0      2        1942        2  ...         0         0        0
3954        0      2        1942        2  ...         0         0        0
3971        0      2        1940        2  ...         1         0        0
3900        0      2        1943        A  ...         1         1        0
3730        0      2        1942        2  ...         0         0        0
3992        0      2        1942        2  ...         1         0        0
4084        0      2        1941        1  ...         1         0        0
3611        0      2        1941        2  ...         0         0        0
3938        0      2        1942        2  ...         0         0        0
4096        0      2        1943        2  ...         1         0        1
3769        0      2        1943        2  ...         0         0        1
3747        0      2        1944        2  ...         1         0        1
4011        0      2        1940        2  ...         1         0        1
4145        0      2        1940        2  ...         0         0        0
3736        0      2        1943        A  ...         0         0        0
3728        0      2        1943        A  ...         1         1        0
3849        0      2        1940        2  ...         0         0        1
3939        0      2        1943        A  ...         1         1        0
3681        0      2        1941        2  ...         0         1        0
3803        0      2        1944        2  ...         1         0        0
4091        0      2        1942        2  ...         0         0        1
4155        0      2        1944        2  ...         1         0        0
3758        0      2        1943        2  ...         0         1        0
3625        0      2        1940        A  ...         0         0        1
3733        0      2        1941        A  ...         1         0        0
4165        0      2        1940        A  ...         0         0        1
3869        0      2        1944        A  ...         1         0        0
3796        0      2        1940        2  ...         0         0        1
3660        0      2        1942        A  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3835         1         0        1         0   屏東縣   72      70-74
3985         0         0        1         0   彰化縣   74      70-74
3912         0         0        1         0   嘉義縣   71      70-74
3727         1         0        1         0   高雄市   72      70-74
3954         0         0        1         0   彰化縣   72      70-74
3971         1         0        1         0   新北市   74      70-74
3900         0         0        1         0   花蓮縣   71      70-74
3730         0         0        1         0   彰化縣   72      70-74
3992         0         0        1         0   台北市   72      70-74
4084         0         0        1         0   台中市   73      70-74
3611         1         0        1         0   台南市   73      70-74
3938         1         1        1         0   新北市   72      70-74
4096         1         0        1         0   台南市   71      70-74
3769         0         0        1         0   雲林縣   71      70-74
3747         0         0        1         0   高雄市   70      70-74
4011         0         1        1         0   嘉義縣   74      70-74
4145         0         0        1         0   台北市   74      70-74
3736         0         0        1         0   屏東縣   71      70-74
3728         0         0        1         0   花蓮縣   71      70-74
3849         0         0        1         0   彰化縣   74      70-74
3939         0         0        1         0   花蓮縣   71      70-74
3681         1         0        1         0   台北市   73      70-74
3803         0         0        1         0   台南市   70      70-74
4091         1         0        1         0   屏東縣   72      70-74
4155         0         1        1         0   苗栗縣   70      70-74
3758         1         1        1         0   台北市   71      70-74
3625         1         0        1         0   花蓮縣   74      70-74
3733         1         1        1         0   桃園市   73      70-74
4165         1         1        1         0   新北市   74      70-74
3869         1         1        1         0   宜蘭縣   70      70-74
3796         0         0        1         0   屏東縣   74      70-74
3660         0         0        1         0   台中市   72      70-74

[32 rows x 30 columns]
女性组第15组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4357  \]\^/<!^/$;;  \]\^/<!^/$;;             2       62       0     2
4482  +%+"&/+]("~^  +%+"&/+]("~^             2       62       0     2
4570  >]>=/{})_!#}  >]>=/{})_!#}             2      31Q       0     2
4488  ;];@*/~\-*^(  ;];@*/~\-*^(             4      31Q       0     2
4479  >]>=/{})_!#}  >]>=/{})_!#}             2      31Q       0     2
4321  -%-_[{>^\;(/  -%-_[{>^\;(/             5      31Q       0     2
4496  >%>"<[*+"{;@  >%>"<[*+"{;@             3      31Q       0     2
4553  -%-_[{>^\;(/  -%-_[{>^\;(/             5      31Q       0     2
4263  \]\/=]*!#^;#  \]\/=]*!#^;#             5      31Q       0     2
4317  @%@@]@;>~&/#  @%@@]@;>~&/#             1       62       0     2
4585  ;%;!]]@=:-^/  ;%;!]]@=:-^/             4      12H       0     2
4548  {%{=+{@^!"/(  {%{=+{@^!"/(             3      31Q       0     2
4302  #]#+*@\^;{$-  #]#+*@\^;{$-             4      31Q       0     2
4197  ~]~}{{++\/_{  ~]~}{{++\/_{             2      31Q       0     2
4464  {%{@;[[<%{{-  {%{@;[[<%{{-             4      31Q       0     2
4196  ]]]>>)/[[^*"  ]]]>>)/[[^*"             5      31Q       0     2
4192  _%__>#>!!]:;  _%__>#>!!]:;             1      31Q       0     2
4297  #]#%$)[:#)#+  #]#%$)[:#)#+             3      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
4357        0      2        1935        A  ...         0         0        0
4482        0      2        1939        A  ...         0         0        0
4570        0      2        1935        2  ...         1         0        0
4488        0      2        1938        2  ...         0         0        1
4479        0      2        1935        2  ...         1         0        0
4321        0      2        1936        2  ...         0         0        0
4496        0      2        1939        2  ...         0         1        1
4553        0      2        1936        2  ...         0         0        0
4263        0      2        1938        2  ...         1         0        0
4317        0      2        1939        A  ...         1         1        1
4585        0      2        1937        1  ...         0         0        0
4548        0      2        1936        2  ...         1         0        0
4302        0      2        1937        2  ...         0         0        0
4197        0      2        1936        2  ...         1         0        0
4464        0      2        1939        2  ...         0         0        0
4196        0      2        1938        2  ...         0         0        0
4192        0      2        1935        2  ...         1         0        0
4297        0      2        1937        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
4357         0         0        1         0   苗栗縣   79      75-79
4482         1         0        1         0   桃園市   75      75-79
4570         0         0        1         0   苗栗縣   79      75-79
4488         0         0        1         0   嘉義縣   76      75-79
4479         0         0        1         0   苗栗縣   79      75-79
4321         1         1        1         0   屏東縣   78      75-79
4496         1         0        1         0   台中市   75      75-79
4553         1         1        1         0   屏東縣   78      75-79
4263         1         0        1         0   屏東縣   76      75-79
4317         1         0        1         0   新北市   75      75-79
4585         1         0        1         0   台南市   77      75-79
4548         1         1        1         0   台中市   78      75-79
4302         0         0        1         0   台南市   77      75-79
4197         0         1        1         0   苗栗縣   78      75-79
4464         1         1        1         0   台南市   75      75-79
4196         0         0        1         0   屏東縣   76      75-79
4192         1         0        1         0   新北市   79      75-79
4297         0         0        1         0   彰化縣   77      75-79

[18 rows x 30 columns]
女性组第16组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4762  "]";(#-@&-*-  "]";(#-@&-*-             3      31Q       0     2
4702  [%[\^"^%!~!]  [%[\^"^%!~!]             5      31Q       0     2
4680  :]:*}[-"!)"@  :]:*}[-"!)"@             4      31Q       0     2
4727  #%#+<$^"=:>"  #%#+<$^"=:>"             1       62       0     2
4653  }%}<^&!]>#\[  }%}<^&!]>#\[             6      31Q       0     2
4711  /]/~\)]-=;>\  /]/~\)]-=;>\             4      31Q       0     2

In [187]:
nPD_d6_M = []
nPD_d6_F = []

# 使用 whole_nPD_M 字典中的分组进行采样
for i in range(18):
    nPD_d6_M.append(whole_nPD_M[i].sample(n=NP_PD_d6_F[i] * 2, replace=True))

# 使用 whole_nPD_F 字典中的分组进行采样
for i in range(18):
    nPD_d6_F.append(whole_nPD_F[i].sample(n=NP_PD_d6_M[i] * 2, replace=True))

In [188]:
for i in range(18):
    print(len(nPD_d6_M[i]))
for i in range(18):
    print(len(nPD_d6_F[i]))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
16
36
0
30
0
0
0
0
0
0
0
0
0
0
2
4
6
0
34
14
6
0

In [189]:
# 为女性组数据添加一个标记列，并垂直合并
for i in range(18):
    nPD_d6_age_F = pd.concat([nPD_d6_F[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d6_age_F))
for i in range(18):

    nPD_d6_age_M = pd.concat([nPD_d6_M[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d6_age_M))
nPD_d6_age = pd.concat([nPD_d6_age_F, nPD_d6_age_M], axis=0, ignore_index=True)

print("all:", len(nPD_d6_age))
# print(nPD_d6_age)

66
82
all: 148

In [190]:
print(len(df_d6_DP_group))

74

# 結果

In [191]:
# #odds ratio語法
# import pandas as pd
# import numpy as np
# from scipy.stats import fisher_exact
# import statsmodels.api as sm
# from statsmodels.stats.contingency_tables import Table2x2
# from datetime import datetime
# #合併PD與nPD
# df_d6_PDandnPD=pd.concat([df_d6_DP_group,nPD_d6_age])
# # 創建交叉表
# contingency_table = pd.crosstab(df_d6_PDandnPD['PD'], df_d6_PDandnPD['disease6'])
# print(contingency_table.shape)
# # 計算odds ratio和p-value
# odds_ratio, p_value = fisher_exact(contingency_table)
# 
# # 計算odds ratio的信賴區間
# table = Table2x2(contingency_table.values)
# confidence_interval = table.oddsratio_confint()
# print(confidence_interval.shape)
# print(f'Odds Ratio: {odds_ratio}')
# print(f'p-value: {p_value}')
# print(f'Confidence Interval: {confidence_interval}')
# if p_value < 0.05:
#     print("\nfail")
# else:
#     print("\npass")
#     
#     nowtime = datetime.now().strftime("%Y%m%d_%H%M")
#     pass_csvFileName=f'd6_pass_PDandnPD{nowtime}.csv'
#     print(pass_csvFileName)    
#     df_d6_PDandnPD.to_csv(f'data/{pass_csvFileName}', index=False)

In [192]:
import pandas as pd
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime

# 假设 df_d6_PDandnPD 是您的合并数据集
df_d6_PDandnPD = pd.concat([df_d6_DP_group, nPD_d6_age])

# 存储结果的列表
results = []
sumP=0
# 遍历 disease1 到 disease7
for n in range(1, 8):
    disease_col = f'disease{n}'
    
    # 筛选出 diseaseN == 1 的样本
    # disease_data = df_d1_PDandnPD[df_d1_PDandnPD[disease_col] == 1]
    
    # 创建 PD 与当前疾病的交叉表
    contingency_table = pd.crosstab(df_d6_PDandnPD['PD'], df_d6_PDandnPD[disease_col])
    
    # 检查表格是否为 2x2
    if contingency_table.shape == (2, 2):
        # 计算 Odds Ratio 和 p 值
        odds_ratio, p_value = fisher_exact(contingency_table)
        
        # 计算置信区间
        table = Table2x2(contingency_table.values)
        confidence_interval = table.oddsratio_confint()
        
        # 记录结果
        results.append({
            'Disease': disease_col,
            'Odds Ratio': odds_ratio,
            'p-value': p_value,
            'Confidence Interval': confidence_interval
        })
        
        # 输出结果
        print(f'\n{disease_col}:')
        print(f'Odds Ratio: {odds_ratio}')
        print(f'p-value: {p_value}')
        print(f'Confidence Interval: {confidence_interval}')
        
        # 检查 p 值
        if p_value < 0.05:
             print("Y_顯著")
        else:
            print("N_不顯著")
            sumP+=1
    else:
        print(f'\n{disease_col}:')
        print("X_交叉表不是 2x2，无法计算统计量。请检查数据。")
print(sumP)

disease1:
Odds Ratio: 1.3894736842105264
p-value: 0.34136158614907847
Confidence Interval: (0.7544750380540204, 2.5589145057643945)
N_不顯著

disease2:
Odds Ratio: 0.37464788732394366
p-value: 0.19029363300447757
Confidence Interval: (0.10493726155933396, 1.3375710152006497)
N_不顯著

disease3:
Odds Ratio: 1.3262786596119929
p-value: 0.3810613848587072
Confidence Interval: (0.7509580092905767, 2.342361438562869)
N_不顯著

disease4:
Odds Ratio: 0.5054302422723476
p-value: 0.08569157768272857
Confidence Interval: (0.24137413722280604, 1.0583558484879274)
N_不顯著

disease5:
Odds Ratio: 0.6587615283267457
p-value: 0.41401743986014355
Confidence Interval: (0.27932523333264925, 1.553625306334491)
N_不顯著

disease6:
X_交叉表不是 2x2，无法计算统计量。请检查数据。

disease7:
Odds Ratio: 1.2176470588235293
p-value: 0.7848098069281264
Confidence Interval: (0.4248426986773547, 3.4899137127165165)
N_不顯著
6

In [193]:
# !ls ~/df_outData

In [194]:
if sumP == 6:
    df_d6_PDandnPD.to_csv('data/out/pass6_d6.csv', index=False)
    print("\npass6_d6.csv")

pass6_d6.csv

In [195]:
# !ls ./data

In [196]:
# !cp ./data/{pass_csvFileName} ~/df_outData/

In [197]:
# !ls ~/df_outData

In [198]:
# df_d6_PDandnPD