In [217]:
import sys

from numpy.testing.print_coercion_tables import print_coercion_table

# from time import process_time_ns

# from scipy.misc.tests.test_doccer import param_doc2

print("start")
print(sys.version)
import os
import pandas as pd

os.getcwd()

start
3.8.20 (default, Oct  3 2024, 10:22:23)
[Clang 14.0.6 ]

'/Users/lai_zx/PycharmProjects/HH_DB'

In [218]:
#轉檔保存
# df_nPD=pd.read_csv('data/nPD_group.csv',encoding='cp950')
# df_PD=pd.read_csv('data/PD_group.csv',encoding='cp950')
# df_nPD.head(10)
# df_nPD.to_csv('data/nPD_group_utf8.csv.csv',index=False,encoding='utf-8')
# df_PD.to_csv('data/PD_group_utf8.csv',index=False,encoding='utf-8')

In [219]:

#釋放記憶體
import gc

# del df_PD
# del df_nPD
# gc.collect()

### 資料載入 PD_group nPD_group

In [220]:
df_PD_group = pd.read_csv('data/PD_group_utf8.csv')
df_nPD_group = pd.read_csv('data/nPD_group_utf8.csv')

In [221]:
print(df_nPD_group.info)
print(df_PD_group.info)

<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     $]$>^"^>%]{$  $]$>^"^>%]{$             1      12H       0     1
1     /%/;#[@""^]~  /%/;#[@""^]~             4      12H       0     1
2     <]<*]#:*-:;=  <]<*]#:*-:;=             2      12H       0     1
3     }%}_~#<^!-%!  }%}_~#<^!-%!             1       62       0     1
4     @]@[$-!~)@}*  @]@[$-!~)@}*             3      12H       0     1
...            ...           ...           ...      ...     ...   ...
5445  ;];;%>:&%"-@  ;];;%>:&%"-@             4      31Q       0     2
5446  ~]~/&]!-@"(%  #%#<}-:^-{%{             5       21       0     2
5447  @%@#&$]~]&!=  @%@#&$]~]&!=             2       62       0     2
5448  +%+!<<>^/&~+  +%+!<<>^/&~+             3      31Q       0     2
5449  _%_*"$[%<-_-  _%_*"$[%<-_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      1        1984        2  ...         0         0        0
1           0      1        1981        2  ...         0         0        0
2           0      1        1982        2  ...         0         0        0
3           0      1        1981        2  ...         0         0        0
4           0      1        1982        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
5445        0      2        1929        2  ...         0         0        0
5446        0      2        1926        2  ...         0         0        0
5447        0      2        1924        2  ...         0         0        0
5448        0      2        1925        2  ...         0         0        0
5449        0      2        1927        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            0         0        0         0   台北市   30  30-34
1            0         0        0         0   雲林縣   33  30-34
2            0         0        0         0   新竹縣   32  30-34
3            0         0        0         0   新北市   33  30-34
4            0         0        0         0   彰化縣   32  30-34
...        ...       ...      ...       ...   ...  ...         ...
5445         0         0        1         0   嘉義縣   85  85~
5446         0         0        0         0   屏東縣   88  85~
5447         0         0        0         0   新竹縣   90  85~
5448         0         0        1         0   台中市   89  85~
5449         0         0        0         0   嘉義市   87  85~

[5450 rows x 30 columns]>
<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     )]))<@%/-@/\  )]))<@%/-@/\             1      31Q       0     2
1     )])->[[_;"}+  )])->[[_;"}+             3       62       0     2
2     )])/;&*^})\_  )])/;&*^})\_             3      31Q       0     2
3     )%):~-[#[%/=  )%):~-[#[%/=             4      31Q       0     2
4     )%)_#)]_>)-{  )%)_#)]_>)-{             3      31Q       0     1
...            ...           ...           ...      ...     ...   ...
2720  (%({_[-}]%%/  (%({_[-}]%%/             5       62       0     2
2721  (%(/:#=${(<"  (%(/:#=${(<"             1       62       0     1
2722  (%(/&<[!>=^!  (%(/&<[!>=^!             1       62       0     2
2723  (%([]$!-$\]]  (%([]$!-$\]]             4      31Q       0     2
2724  (%(&<]")^&+<  (%(&<]")^&+<             4       62       0     1

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      2        1926        2  ...         1         0        0
1           0      2        1928        2  ...         1         0        0
2           0      2        1923        2  ...         0         0        0
3           0      2        1922        2  ...         0         0        0
4           0      1        1941        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
2720        0      2        1915        2  ...         0         0        1
2721        0      1        1974        2  ...         0         0        0
2722        0      2        1941        A  ...         0         0        1
2723        0      2        1933        2  ...         1         0        0
2724        0      1        1953        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            1         0        0         0   宜蘭縣   88  85~
1            0         1        0         0   南投縣   86  85~
2            0         1        0         0   彰化縣   91  85~
3            0         0        0         0   雲林縣   92  85~
4            0         0        0         0   南投縣   73  70-74
...        ...       ...      ...       ...   ...  ...         ...
2720         0         0        0         0   屏東縣   99  85~
2721         0         0        0         0   台北市   40  40-44
2722         1         0        1         0   新北市   73  70-74
2723         0         0        0         0   嘉義縣   81  80-84
2724         0         0        0         0   台南市   61  60-64

[2725 rows x 30 columns]>

### disease1

In [222]:
print(len(df_PD_group.query('disease1==1')))
print(len(df_nPD_group.query('disease1==1')))

1052
1194

## 比例

In [223]:
# 從PD_group 抽 有 disease1 
df_d1_DP_group = (df_PD_group.query('disease1==1')).sample(430)
df_d1_nDP_group = (df_nPD_group.query('disease1==1')).sample(1100)
print(len(df_d1_DP_group.query('disease1==1')))
print(len(df_d1_nDP_group.query('disease1==1')))

430
1100

In [224]:
df_d1_nDP_group.query('ID1_S==2 and age_group=="85~"')

Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]

In [225]:
df_d1_DP_group['ID1_S'] = df_d1_DP_group['ID1_S'].astype(str)
df_d1_DP_group['age_group'] = df_d1_DP_group['age_group'].astype(str)
print(df_d1_DP_group.dtypes)

ID               object
ID1              object
ID1_DIVISION      int64
ID1_UNIT         object
ID_ROC            int64
ID_S              int64
ID1_ROC           int64
ID1_S            object
ID_BIRTH_Y        int64
ID1_TYPE         object
ID_RELATION     float64
ID1_AMT         float64
ID1_IDENT        object
PREM_YM           int64
ID_STATUS         int64
ID1_MARK         object
FAM_CONT_Y      float64
FAM_CONT_N      float64
ID1_CITY          int64
PD                int64
disease1          int64
disease2          int64
disease3          int64
disease4          int64
disease5          int64
disease6          int64
disease7          int64
city             object
Age               int64
age_group        object
dtype: object

In [226]:
#依比例分組抽樣
#先算出PD group的比例
# 範例


a = df_d1_DP_group.groupby(by=['ID1_S', 'age_group'])['ID'].count()
PD_M = list(a.iloc[0:18])
PD_F = list(a.iloc[18:])
print(PD_M)

[8, 30, 25, 24, 32, 51, 35, 54, 5, 6, 9, 41, 37, 21, 52]

In [227]:
# import pandas as pd
# 
# # 将 age_group 明确转换为字符串格式
# df_d1_DP_group['age_group'] = df_d1_DP_group['age_group'].astype(str)
# 
# # 确保 ID1_S 也为字符串
# df_d1_DP_group['ID1_S'] = df_d1_DP_group['ID1_S'].astype(str)
# #print(df_d1_DP_group.dtypes)
# #定义所有 ID1_S 和年龄组
# all_ID1_S = ['1', '2']
# all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', 
#                   '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80-84', '85~']
# # # 将列表元素明确转换为字符串（Python 内置的字符串是对象类型）
# # all_ID1_S = list(map(str, [1, 2]))
# # all_age_groups = list(map(str, ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', 
# #                                 '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', 
# #                                 '60-64', '65-69', '70-74', '75-79', '80-84', '85~']))
# 
# # 创建 MultiIndex 用于填充
# index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])
# 
# # 重新计算分组，补全缺失组合
# pdAge = df_d1_DP_group.groupby(['ID1_S', 'age_group'])['ID'].count().reindex(index, fill_value=0)
# 
# # 分割为 PD_d1_M 和 PD_d1_F 的列表
# PD_d1_M = list(pdAge.loc['1'])
# PD_d1_F = list(pdAge.loc['2'])
# 
# # 输出结果，查看分组后的数据
# print("PD_d1_M:", PD_d1_M)  # 这里应该包含所有年龄组的值（包括 0）
# print("=")
# print("PD_d1_F:", PD_d1_F)  # 这里应该包含所有年龄组的值（包括 0）
# print("pdAge DataFrame:\n", pdAge)

In [228]:
import pandas as pd

# 假设您的 DataFrame 是 df，并且其中有一列名为 'age_groups'
# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
df_d1_DP_group['age_group'] = df_d1_DP_group['age_group'].str.strip()
# 使用 value_counts() 方法统计每个年龄组的数量
#age_group_counts =df_d1_DP_group ['age_group'].value_counts()
age_group_counts = df_d1_DP_group['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_M = df_d1_DP_group.query('ID1_S==1')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d1_DP_group.query('ID1_S==2')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
print(age_group_counts)

# 显示结果
# print(age_group_counts)
# print(age_group_counts2)
# print(age_group_counts.index.tolist())
# print(all_age_groups)

age_group
0-4        0
5-9        0
10-14      0
15-19      0
20-24      0
25-29      0
30-34      0
35-39      0
40-44      0
45-49      8
50-54      5
55-59     30
60-64     31
65-69     33
70-74     73
75-79     88
80-84     56
85~      106
Name: count, dtype: int64

In [229]:
import pandas as pd

# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']

# 数据清理
# 去除 'age_group' 列中值的前后空格
df_d1_DP_group['age_group'] = df_d1_DP_group['age_group'].str.strip()

# 确保 'ID1_S' 和 'ID' 列的数据类型正确
df_d1_DP_group['ID1_S'] = df_d1_DP_group['ID1_S'].astype(int)
df_d1_DP_group['ID'] = df_d1_DP_group['ID'].astype(str)

# 将 'age_group' 列转换为分类数据类型，确保顺序正确
df_d1_DP_group['age_group'] = pd.Categorical(df_d1_DP_group['age_group'], categories=all_age_groups, ordered=True)

# 按性别过滤数据
# 男性数据（ID1_S == 1）
df_d1_DP_M = df_d1_DP_group[df_d1_DP_group['ID1_S'] == 1]
df_d1_DP_F = df_d1_DP_group[df_d1_DP_group['ID1_S'] == 2]

# 按年龄组统计男性的 ID 数量
age_group_counts_M = df_d1_DP_M.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d1_DP_F.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
# 显示结果
print("男性各年龄组的 ID 数量：")
print(age_group_counts_M)
print(age_group_counts_F)
NP_PD_d1_M = age_group_counts_M.to_numpy()
NP_PD_d1_F = age_group_counts_F.to_numpy()
print(NP_PD_d1_M)

男性各年龄组的 ID 数量：
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     8
50-54     0
55-59    30
60-64    25
65-69    24
70-74    32
75-79    51
80-84    35
85~      54
Name: ID, dtype: int64
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     0
50-54     5
55-59     0
60-64     6
65-69     9
70-74    41
75-79    37
80-84    21
85~      52
Name: ID, dtype: int64
[ 0  0  0  0  0  0  0  0  0  8  0 30 25 24 32 51 35 54]

In [230]:
df_d1_DP_group.dtypes

ID                object
ID1               object
ID1_DIVISION       int64
ID1_UNIT          object
ID_ROC             int64
ID_S               int64
ID1_ROC            int64
ID1_S              int64
ID_BIRTH_Y         int64
ID1_TYPE          object
ID_RELATION      float64
ID1_AMT          float64
ID1_IDENT         object
PREM_YM            int64
ID_STATUS          int64
ID1_MARK          object
FAM_CONT_Y       float64
FAM_CONT_N       float64
ID1_CITY           int64
PD                 int64
disease1           int64
disease2           int64
disease3           int64
disease4           int64
disease5           int64
disease6           int64
disease7           int64
city              object
Age                int64
age_group       category
dtype: object

In [231]:
import pandas as pd

who2000 = pd.read_csv('data/who2000.csv')
# 定义所有可能的 `ID1_S` 和 `age_group` 组合
all_ID1_S = ['1', '2']
#all_age_groups = who2000['AGE']
# 确保 ID1_S 是整数类型
df_d1_nDP_group['ID1_S'] = df_d1_nDP_group['ID1_S'].astype(int)

# 确保 age_group 列没有多余空格
df_d1_nDP_group['age_group'] = df_d1_nDP_group['age_group'].str.strip()

all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
# 去除 'age_group' 列中值的前后空格
df_d1_DP_group['age_group'] = df_d1_DP_group['age_group'].str.strip()

# 创建 MultiIndex，包含所有可能的组合
index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])

# 男性组
# 男性组
whole_nPD_M = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d1_nDP_group[(df_d1_nDP_group['ID1_S'] == 1) & (df_d1_nDP_group['age_group'] == all_age_groups[i])]
    # 打印每个分组数据以调试
    #print(f"男性组第{i}组数据:\n", data)
    whole_nPD_M[i] = data if not data.empty else pd.DataFrame(columns=df_d1_nDP_group.columns).reindex(
        index=[(1, all_age_groups[i])])

# 女性组
whole_nPD_F = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d1_nDP_group.query(f'ID1_S == 2 and age_group == "{all_age_groups[i]}"')
    # 打印每个分组数据以调试
    print(f"女性组第{i}组数据:\n", data)
    whole_nPD_F[i] = data if not data.empty else pd.DataFrame(columns=df_d1_nDP_group.columns).reindex(
        index=[(2, all_age_groups[i])])

女性组第0组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第1组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第2组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第3组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第4组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第5组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第6组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第7组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2839  >%><~{}-(!:(  >%><~{}-(!:(             4       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2839        0      2        1978        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2839         0         0        0         0   雲林縣   36      35-39

[1 rows x 30 columns]
女性组第8组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2922  <]</${/]!%%#  <]</${/]!%%#             3       52       0     2
2919  *%*]>>:-@%&\  *%*]>>:-@%&\             3       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2922        0      2        1972        2  ...         1         0        0
2919        0      2        1972        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2922         0         0        0         0   台中市   42      40-44
2919         0         0        0         0   台中市   42      40-44

[2 rows x 30 columns]
女性组第9组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2977  )%)!-]&"^-(}  )%)!-]&"^-(}             1       62       0     2
2990  "]"^(@=()*!;  "]"^(@=()*!;             3       32       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2977        0      2        1965        2  ...         1         0        0
2990        0      2        1966        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2977         0         0        0         0   新北市   49      45-49
2990         0         0        0         0   彰化縣   48      45-49

[2 rows x 30 columns]
女性组第10组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3026  "%"~;$](*!~%  "%"~;$](*!~%             4      31Q       0     2
3139  :]::%@*>(%;)  :]::%@*>(%;)             5      13I       0     2
3131  \%\<>"^-+#!>  \%\<>"^-+#!>             5       21       0     2
3067  "%"~}/{-})}\  "%"~}/{-})}\             5       21       0     2
3034  &%&~)))-;}][  &%&~)))-;}][             4      12H       0     2
3043  "]"&:<<%:(<]  "]"&:<<%:(<]             1       21       0     2
3082  %]%\/&@<"*}(  %]%\/&@<"*}(             5       21       0     2
3029  $%$@&[(!+{%"  $%$@&[(!+{%"             5      31Q       0     2
3080  ^]^*<])-}\+*  ^]^*<])-}\+*             1       62       0     2
3081  *%*>$/@*[!*"  *%*>$/@*[!*"             5       62       0     2
3134  /%/#^{;!![:+  /%/#^{;!![:+             4       21       0     2
3071  !]!;#"^#}[<#  !]!;#"^#}[<#             5      12H       0     2
3084  &%&~)))-;}][  &%&~)))-;}][             4      12H       0     2
3040  @]@"("$(*#+!  @]@"("$(*#+!             1       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3026        0      2        1960        2  ...         1         0        0
3139        0      2        1960        2  ...         1         0        1
3131        0      2        1960        2  ...         1         0        1
3067        0      2        1960        2  ...         1         0        1
3034        0      2        1964        2  ...         1         0        0
3043        0      2        1963        2  ...         1         0        0
3082        0      2        1960        2  ...         1         0        1
3029        0      2        1963        2  ...         1         0        0
3080        0      2        1962        2  ...         1         0        0
3081        0      2        1963        A  ...         1         0        0
3134        0      2        1963        2  ...         1         0        0
3071        0      2        1961        2  ...         1         0        0
3084        0      2        1964        2  ...         1         0        0
3040        0      2        1961        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3026         0         0        0         0   雲林縣   54      50-54
3139         1         0        0         0   高雄市   54      50-54
3131         0         0        0         0   高雄市   54      50-54
3067         1         0        0         0   高雄市   54      50-54
3034         0         0        0         0   嘉義縣   50      50-54
3043         0         0        0         0   台北市   51      50-54
3082         1         0        0         0   屏東縣   54      50-54
3029         1         0        0         0   屏東縣   51      50-54
3080         1         0        0         0   台北市   52      50-54
3081         0         0        0         0   屏東縣   51      50-54
3134         0         0        0         0   台南市   51      50-54
3071         0         0        0         0   高雄市   53      50-54
3084         0         0        0         0   嘉義縣   50      50-54
3040         0         0        0         0   新北市   53      50-54

[14 rows x 30 columns]
女性组第11组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3153  ;];)@>()$[}!  ;];)@>()$[}!             4      12H       0     2
3148  #]#/$[<)#(:(  #]#/$[<)#(:(             4      31Q       0     2
3267  !]!!*<@-"=;!  !]!!*<@-"=;!             1      31Q       0     2
3197  ~%~(=[@{*-#<  ~%~(=[@{*-#<             3       21       0     2
3218  ~]~&:"_):%["  ~]~&:"_):%["             1       21       0     2
3238  -%-_{<#::!^&  -%-_{<#::!^&             1       21       0     2
3162  #]#_#@;@$]\:  #]#_#@;@$]\:             4       21       0     2
3180  (](<+{]^%!:-  (](<+{]^%!:-             2       21       0     2
3249  %%%;"[:]>>-[  %%%;"[:]>>-[             2       62       0     2
3219  }]}+&)$<*@$_  }]}+&)$<*@$_             2      12H       0     2
3156  \]\->#+;)(;&  \]\->#+;)(;&             1       21       0     2
3241  #]#{{]+"+%:_  #]#{{]+"+%:_             1      12H       0     2
3253  ~%~&<#;~^/>>  ~%~&<#;~^/>>             1       62       0     2
3185  ]%]~+@_!%%%\  ]%]~+@_!%%%\             2       21       0     2
3210  :%:>@{<-%[~=  :%:>@{<-%[~=             3       21       0     2
3202  *]*-!-<%*@$<  *]*-!-<%*@$<             6       62       0     2
3235  _]_#}){;]<$:  _]_#}){;]<$:             4       21       0     2
3159  -%-]*"(&(==(  -%-]*"(&(==(             5       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3153        0      2        1955        2  ...         1         0        0
3148        0      2        1956        2  ...         1         0        1
3267        0      2        1957        2  ...         1         1        0
3197        0      2        1957        2  ...         1         0        0
3218        0      2        1958        2  ...         1         0        0
3238        0      2        1957        2  ...         1         0        0
3162        0      2        1956        2  ...         1         1        1
3180        0      2        1956        2  ...         1         0        1
3249        0      2        1958        A  ...         1         0        1
3219        0      2        1959        1  ...         1         1        0
3156        0      2        1957        2  ...         1         0        0
3241        0      2        1959        2  ...         1         1        0
3253        0      2        1959        2  ...         1         0        1
3185        0      2        1958        2  ...         1         0        0
3210        0      2        1957        2  ...         1         0        0
3202        0      2        1959        A  ...         1         0        0
3235        0      2        1957        2  ...         1         0        1
3159        0      2        1959        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3153         1         0        0         0   嘉義縣   59      55-59
3148         1         0        0         0   雲林縣   58      55-59
3267         0         0        0         0   新北市   57      55-59
3197         1         0        0         0   南投縣   57      55-59
3218         0         0        0         1   台北市   56      55-59
3238         0         0        0         0   台北市   57      55-59
3162         0         0        0         0   雲林縣   58      55-59
3180         0         0        0         0   新竹市   58      55-59
3249         1         0        0         0   桃園市   56      55-59
3219         0         0        0         0   桃園市   55      55-59
3156         0         0        0         0   台北市   57      55-59
3241         0         0        0         0   台北市   55      55-59
3253         0         0        0         0   台北市   55      55-59
3185         0         0        0         0   桃園市   56      55-59
3210         0         0        0         0   南投縣   57      55-59
3202         0         0        0         0   台東縣   55      55-59
3235         1         0        0         0   台南市   57      55-59
3159         1         0        0         1   屏東縣   55      55-59

[18 rows x 30 columns]
女性组第12组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3345  @%@;&/@%<#)&  @%@;&/@%<#)&             1       62       0     2
3330  "%""$]-;^"::  "%""$]-;^"::             1       32       0     2
3401  }%}{!--;_-)]  }%}{!--;_-)]             2       62       0     2
3324  #%#-><]+}}"!  #%#-><]+}}"!             2       62       0     2
3329  #%#[%[!*[{:=  #%#[%[!*[{:=             1      12H       0     2
3455  ;];<"#(_#[){  ;];<"#(_#[){             3      31Q       0     2
3350  #]#(:-<-":$}  #]#(:-<-":$}             1       21       0     2
3382  &]&}@)[;%_\>  &]&}@)[;%_\>             1       21       0     2
3336  %%%({@&#$(\+  %%%({@&#$(\+             4      31Q       0     2
3412  -]-;<#-+^_%(  -]-;<#-+^_%(             1      12H       0     2
3308  [%["@"~&+!_\  [%["@"~&+!_\             4      31Q       0     2
3372  :]:/=]>)"@(=  :]:/=]>)"@(=             3       21       0     2
3297  !]!)!"";"}:{  !]!)!"";"}:{             1       21       0     2
3456  ]]]_~-+"~;</  ]]]_~-+"~;</             3       62       0     2
3368  &]&}@)[;%_\>  &]&}@)[;%_\>             1       21       0     2
3431  =]=!)#~#$+}_  =]=!)#~#$+}_             1       21       0     2
3284  =]=\{@~-*&{<  =]=\{@~-*&{<             2       21       0     2
3349  &%&/)&$_!>:;  &%&/)&$_!>:;             1       21       0     2
3413  ~]~-$/:_:!%]  ~]~-$/:_:!%]             3      31Q       0     2
3406  @]@[<>])>!+<  @]@[<>])>!+<             3      12H       0     2
3298  (](<:{/##$%_  (](<:{/##$%_             4      31Q       0     2
3445  ]]]{^&:!;*#{  ]]]{^&:!;*#{             1       21       0     2
3318  {]{}=]=*\@{-  {]{}=]=*\@{-             1      12H       0     2
3342  /]/:()]\""{<  /]/:()]\""{<             4      31Q       0     2
3321  %%%}}[>_(!{@  %%%}}[>_(!{@             2       21       0     2
3339  $]$&/@:$>)$>  $]$&/@:$>)$>             3      31Q       0     2
3285  {]{$~[%_\&*_  {]{$~[%_\&*_             4       32       0     2
3422  /%/@}$*%&\#_  /%/@}$*%&\#_             2       62       0     2
3370  =]=*<#::-+)@  =]=*<#::-+)@             1       21       0     2
3394  $]$]@>\:<$!<  $]$]@>\:<$!<             1      12H       0     2
3424  *%*:<";<+-<$  *%*:<";<+-<$             3      12H       0     2
3411  ^%^!/[-*@[~!  ^%^!/[-*@[~!             2       62       0     2
3416  [][~@->^+;!!  [][~@->^+;!!             5       52       0     2
3335  {]{;(@*$>*{]  {]{;(@*$>*{]             1       62       0     2
3399  %]%[%@--:*&~  %]%[%@--:*&~             1      12M       0     2
3355  ~%~<-@&]@>}/  ~%~<-@&]@>}/             4       21       0     2
3377  =%=!)/:<=~^%  =%=!)/:<=~^%             5       21       0     2
3395  <%<<@@&!~;[=  <%<<@@&!~;[=             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3345        0      2        1951        2  ...         1         0        0
3330        0      2        1950        2  ...         1         0        1
3401        0      2        1951        2  ...         1         0        1
3324        0      2        1952        2  ...         1         0        1
3329        0      2        1951        2  ...         1         0        0
3455        0      2        1950        2  ...         1         1        0
3350        0      2        1953        2  ...         1         0        0
3382        0      2        1950        2  ...         1         0        0
3336        0      2        1951        2  ...         1         0        0
3412        0      2        1950        2  ...         1         0        1
3308        0      2        1951        2  ...         1         0        0
3372        0      2        1951        2  ...         1         0        0
3297        0      2        1953        2  ...         1         0        0
3456        0      2        1950        A  ...         1         0        1
3368        0      2        1950        2  ...         1         0        0
3431        0      2        1950        2  ...         1         0        1
3284        0      2        1954        2  ...         1         1        0
3349        0      2        1950        2  ...         1         0        1
3413        0      2        1951        2  ...         1         0        1
3406        0      2        1954        2  ...         1         0        0
3298        0      2        1953        2  ...         1         0        1
3445        0      2        1954        2  ...         1         0        1
3318        0      2        1951        2  ...         1         0        0
3342        0      2        1953        2  ...         1         0        0
3321        0      2        1954        2  ...         1         0        0
3339        0      2        1950        2  ...         1         0        0
3285        0      2        1951        2  ...         1         0        1
3422        0      2        1954        A  ...         1         0        0
3370        0      2        1950        2  ...         1         0        0
3394        0      2        1953        2  ...         1         0        0
3424        0      2        1952        2  ...         1         0        0
3411        0      2        1953        A  ...         1         0        0
3416        0      2        1954        2  ...         1         0        1
3335        0      2        1950        2  ...         1         0        0
3399        0      2        1954        2  ...         1         1        0
3355        0      2        1954        2  ...         1         0        1
3377        0      2        1954        2  ...         1         0        0
3395        0      2        1952        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3345         0         0        0         0   新北市   63      60-64
3330         1         0        0         0   宜蘭縣   64      60-64
3401         0         0        0         0   新竹縣   63      60-64
3324         0         0        0         0   桃園市   62      60-64
3329         0         0        0         0   新北市   63      60-64
3455         1         0        0         0   彰化縣   64      60-64
3350         0         0        0         0   基隆市   61      60-64
3382         0         0        0         0   新北市   64      60-64
3336         0         0        0         0   台南市   63      60-64
3412         0         1        0         0   新北市   64      60-64
3308         0         0        0         0   嘉義縣   63      60-64
3372         0         0        0         0   南投縣   63      60-64
3297         0         0        0         0   台北市   61      60-64
3456         0         0        0         0   台中市   64      60-64
3368         0         0        0         0   新北市   64      60-64
3431         1         0        0         0   台北市   64      60-64
3284         1         0        1         0   桃園市   60      60-64
3349         0         0        1         0   台北市   64      60-64
3413         0         0        0         0   彰化縣   63      60-64
3406         0         0        0         0   台中市   60      60-64
3298         1         0        0         0   雲林縣   61      60-64
3445         1         0        0         0   台北市   60      60-64
3318         0         0        0         0   新北市   63      60-64
3342         0         0        0         0   嘉義市   61      60-64
3321         0         0        0         0   新竹縣   60      60-64
3339         0         0        0         0   台中市   64      60-64
3285         1         0        0         1   台南市   63      60-64
3422         1         0        1         0   新竹縣   60      60-64
3370         0         0        0         0   台北市   64      60-64
3394         1         0        0         0   基隆市   61      60-64
3424         0         0        0         0   台中市   62      60-64
3411         0         0        0         0   桃園市   61      60-64
3416         1         0        1         0   高雄市   60      60-64
3335         1         1        0         0   台北市   64      60-64
3399         1         0        0         0   新北市   60      60-64
3355         0         1        0         0   台南市   60      60-64
3377         1         1        0         0   澎湖縣   60      60-64
3395         1         0        0         0   台南市   62      60-64

[38 rows x 30 columns]
女性组第13组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \

In [232]:
# whole_nPD_F[17]

# print(df_d1_nDP_group.query('ID1_S == 2'))

# print(df_d1_nDP_group['ID1_S'].dtype)  # 應該為整數類型
# print(df_d1_nDP_group['ID1_S'].unique())  # 查看唯一值
# print(df_d1_nDP_group['age_group'].unique())  # 查看age_group的唯一值

In [233]:
# # 初始化字典来存储结果
# whole_nPD_M = {}
# whole_nPD_F = {}
# 
# # 遍历所有年龄段的索引
# for i in range(18):
#     age_group = who2000['AGE'][i]  # 获取每个年龄段
# 
#     # 筛选男性数据并存储在字典中
#     whole_nPD_M[i] = df_d1_PD_group[(df_nPD_group['ID1_S'] == '1') & (df_nPD_group['age_group'] == age_group)]
# 
#     # 筛选女性数据并存储在字典中
#     whole_nPD_F[i] = df_nPD_group[(df_nPD_group['ID1_S'] == '2') & (df_nPD_group['age_group'] == age_group)]
# 
# # 示例：访问男性的第一个年龄组数据
# # print(whole_nPD_M[17])
# # 
# # # 示例：访问女性的第一个年龄组数据
# # print(whole_nPD_F[17])
# 
# print(df_nPD_group['age_group'].head(10))
# print(who2000['AGE'][3])

In [234]:
nPD_d1_M = []
nPD_d1_F = []

# 使用 whole_nPD_M 字典中的分组进行采样
for i in range(18):
    nPD_d1_M.append(whole_nPD_M[i].sample(n=NP_PD_d1_F[i] * 2, replace=True))

# 使用 whole_nPD_F 字典中的分组进行采样
for i in range(18):
    nPD_d1_F.append(whole_nPD_F[i].sample(n=NP_PD_d1_M[i] * 2, replace=True))

In [235]:
for i in range(18):
    print(len(nPD_d1_M[i]))
for i in range(18):
    print(len(nPD_d1_F[i]))

0
0
0
0
0
0
0
0
0
0
10
0
12
18
82
74
42
104
0
0
0
0
0
0
0
0
0
16
0
60
50
48
64
102
70
108

In [236]:
# 为女性组数据添加一个标记列，并垂直合并
for i in range(18):
    nPD_d1_age_F = pd.concat([nPD_d1_F[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d1_age_F))
for i in range(18):

    nPD_d1_age_M = pd.concat([nPD_d1_M[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d1_age_M))
nPD_d1_age = pd.concat([nPD_d1_age_F, nPD_d1_age_M], axis=0, ignore_index=True)

print("all:", len(nPD_d1_age))
# print(nPD_d1_age)

518
342
all: 860

In [237]:
print(len(df_d1_DP_group))

430

# 結果

In [238]:
#odds ratio語法
import pandas as pd
import numpy as np
from scipy.stats import fisher_exact
import statsmodels.api as sm
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime
#合併PD與nPD
df_d1_PDandnPD=pd.concat([df_d1_DP_group,nPD_d1_age])
# 創建交叉表
contingency_table = pd.crosstab(df_d1_PDandnPD['PD'], df_d1_PDandnPD['disease2'])


print(contingency_table.shape)
# 計算odds ratio和p-value
odds_ratio, p_value = fisher_exact(contingency_table)

# 計算odds ratio的信賴區間
table = Table2x2(contingency_table.values)
confidence_interval = table.oddsratio_confint()

print(f'Odds Ratio: {odds_ratio}')
print(f'p-value: {p_value}')
print(f'Confidence Interval: {confidence_interval}')
if p_value < 0.05:
    print("\nfail")
else:
    print("\npass")
    
    nowtime = datetime.now().strftime("%Y%m%d_%H%M")
    pass_csvFileName=f'd1_pass_PDandnPD{nowtime}.csv'
    print(pass_csvFileName)    
    df_d1_PDandnPD.to_csv(f'data/{pass_csvFileName}', index=False)

(2, 2)
Odds Ratio: 1.1428191842699615
p-value: 0.5449078590850145
Confidence Interval: (0.7744295165848939, 1.6864487470659195)

pass
d1_pass_PDandnPD20241101_1824.csv

In [239]:
import pandas as pd
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime

# 假设 df_d1_PDandnPD 是您的合并数据集
df_d1_PDandnPD = pd.concat([df_d1_DP_group, nPD_d1_age])

# 存储结果的列表
results = []
sumP=0
# 遍历 disease1 到 disease7
for n in range(1, 8):
    disease_col = f'disease{n}'
    
    # 筛选出 diseaseN == 1 的样本
    # disease_data = df_d1_PDandnPD[df_d1_PDandnPD[disease_col] == 1]
    
    # 创建 PD 与当前疾病的交叉表
    contingency_table = pd.crosstab(df_d1_PDandnPD['PD'], df_d1_PDandnPD[disease_col])
    
    # 检查表格是否为 2x2
    if contingency_table.shape == (2, 2):
        # 计算 Odds Ratio 和 p 值
        odds_ratio, p_value = fisher_exact(contingency_table)
        
        # 计算置信区间
        table = Table2x2(contingency_table.values)
        confidence_interval = table.oddsratio_confint()
        
        # 记录结果
        results.append({
            'Disease': disease_col,
            'Odds Ratio': odds_ratio,
            'p-value': p_value,
            'Confidence Interval': confidence_interval
        })
        
        # 输出结果
        print(f'\n{disease_col}:')
        print(f'Odds Ratio: {odds_ratio}')
        print(f'p-value: {p_value}')
        print(f'Confidence Interval: {confidence_interval}')
        
        # 检查 p 值
        if p_value < 0.05:
            print("Y_结果显著，存在统计学关联。")
        else:
            print("N_结果不显著，未发现统计学关联。")
            sumP+=1
    else:
        print(f'\n{disease_col}:')
        print("X_交叉表不是 2x2，无法计算统计量。请检查数据。")
print(sumP)
# 将结果转换为 DataFrame
# results_df = pd.DataFrame(results)
# 
# # 显示所有结果
# print("\n所有疾病的分析结果：")
# print(results_df)

# 保存结果到 CSV 文件
#nowtime = datetime.now().strftime("%Y%m%d_%H%M")
#results_df.to_csv(f'data/disease_analysis_results_{nowtime}.csv', index=False)

disease1:
X_交叉表不是 2x2，无法计算统计量。请检查数据。

disease2:
Odds Ratio: 1.1428191842699615
p-value: 0.5449078590850145
Confidence Interval: (0.7744295165848939, 1.6864487470659195)
N_结果不显著，未发现统计学关联。

disease3:
Odds Ratio: 1.1856212228239542
p-value: 0.17007324828961884
Confidence Interval: (0.9298946198876049, 1.5116741767798076)
N_结果不显著，未发现统计学关联。

disease4:
Odds Ratio: 0.9937691995594969
p-value: 1.0
Confidence Interval: (0.7597948717356023, 1.2997945349870512)
N_结果不显著，未发现统计学关联。

disease5:
Odds Ratio: 1.1127188843451818
p-value: 0.588941689896718
Confidence Interval: (0.7851326509967954, 1.5769861487819352)
N_结果不显著，未发现统计学关联。

disease6:
Odds Ratio: 1.092218137254902
p-value: 0.6958245488883232
Confidence Interval: (0.7476503226666524, 1.5955860957749535)
N_结果不显著，未发现统计学关联。

disease7:
Odds Ratio: 1.1856357927786498
p-value: 0.4461787288019734
Confidence Interval: (0.7804862895281349, 1.8010979205896556)
N_结果不显著，未发现统计学关联。
6

In [240]:

if sumP == 6:
    df_d1_PDandnPD.to_csv('data/out/pass6_d1.csv', index=False)
    print("\npass6_d1.csv")

pass6_d1.csv

In [241]:
# !ls ~/df_outData

In [242]:
# !ls ./data

In [243]:
# !cp ./data/{pass_csvFileName} ~/df_outData/