In [265]:
import sys

from numpy.testing.print_coercion_tables import print_coercion_table

# from time import process_time_ns

# from scipy.misc.tests.test_doccer import param_doc2

print("start")
print(sys.version)
import os
import pandas as pd

os.getcwd()

start
3.8.20 (default, Oct  3 2024, 10:22:23)
[Clang 14.0.6 ]

'/Users/lai_zx/PycharmProjects/HH_DB'

### 資料載入 PD_group nPD_group

In [266]:
df_PD_group = pd.read_csv('data/PD_group_utf8.csv')
df_nPD_group = pd.read_csv('data/nPD_group_utf8.csv')

In [267]:
print(df_nPD_group.info)
print(df_PD_group.info)

<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     $]$>^"^>%]{$  $]$>^"^>%]{$             1      12H       0     1
1     /%/;#[@""^]~  /%/;#[@""^]~             4      12H       0     1
2     <]<*]#:*-:;=  <]<*]#:*-:;=             2      12H       0     1
3     }%}_~#<^!-%!  }%}_~#<^!-%!             1       62       0     1
4     @]@[$-!~)@}*  @]@[$-!~)@}*             3      12H       0     1
...            ...           ...           ...      ...     ...   ...
5445  ;];;%>:&%"-@  ;];;%>:&%"-@             4      31Q       0     2
5446  ~]~/&]!-@"(%  #%#<}-:^-{%{             5       21       0     2
5447  @%@#&$]~]&!=  @%@#&$]~]&!=             2       62       0     2
5448  +%+!<<>^/&~+  +%+!<<>^/&~+             3      31Q       0     2
5449  _%_*"$[%<-_-  _%_*"$[%<-_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      1        1984        2  ...         0         0        0
1           0      1        1981        2  ...         0         0        0
2           0      1        1982        2  ...         0         0        0
3           0      1        1981        2  ...         0         0        0
4           0      1        1982        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
5445        0      2        1929        2  ...         0         0        0
5446        0      2        1926        2  ...         0         0        0
5447        0      2        1924        2  ...         0         0        0
5448        0      2        1925        2  ...         0         0        0
5449        0      2        1927        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            0         0        0         0   台北市   30  30-34
1            0         0        0         0   雲林縣   33  30-34
2            0         0        0         0   新竹縣   32  30-34
3            0         0        0         0   新北市   33  30-34
4            0         0        0         0   彰化縣   32  30-34
...        ...       ...      ...       ...   ...  ...         ...
5445         0         0        1         0   嘉義縣   85  85~
5446         0         0        0         0   屏東縣   88  85~
5447         0         0        0         0   新竹縣   90  85~
5448         0         0        1         0   台中市   89  85~
5449         0         0        0         0   嘉義市   87  85~

[5450 rows x 30 columns]>
<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     )]))<@%/-@/\  )]))<@%/-@/\             1      31Q       0     2
1     )])->[[_;"}+  )])->[[_;"}+             3       62       0     2
2     )])/;&*^})\_  )])/;&*^})\_             3      31Q       0     2
3     )%):~-[#[%/=  )%):~-[#[%/=             4      31Q       0     2
4     )%)_#)]_>)-{  )%)_#)]_>)-{             3      31Q       0     1
...            ...           ...           ...      ...     ...   ...
2720  (%({_[-}]%%/  (%({_[-}]%%/             5       62       0     2
2721  (%(/:#=${(<"  (%(/:#=${(<"             1       62       0     1
2722  (%(/&<[!>=^!  (%(/&<[!>=^!             1       62       0     2
2723  (%([]$!-$\]]  (%([]$!-$\]]             4      31Q       0     2
2724  (%(&<]")^&+<  (%(&<]")^&+<             4       62       0     1

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      2        1926        2  ...         1         0        0
1           0      2        1928        2  ...         1         0        0
2           0      2        1923        2  ...         0         0        0
3           0      2        1922        2  ...         0         0        0
4           0      1        1941        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
2720        0      2        1915        2  ...         0         0        1
2721        0      1        1974        2  ...         0         0        0
2722        0      2        1941        A  ...         0         0        1
2723        0      2        1933        2  ...         1         0        0
2724        0      1        1953        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            1         0        0         0   宜蘭縣   88  85~
1            0         1        0         0   南投縣   86  85~
2            0         1        0         0   彰化縣   91  85~
3            0         0        0         0   雲林縣   92  85~
4            0         0        0         0   南投縣   73  70-74
...        ...       ...      ...       ...   ...  ...         ...
2720         0         0        0         0   屏東縣   99  85~
2721         0         0        0         0   台北市   40  40-44
2722         1         0        1         0   新北市   73  70-74
2723         0         0        0         0   嘉義縣   81  80-84
2724         0         0        0         0   台南市   61  60-64

[2725 rows x 30 columns]>

### disease5

In [268]:
print(len(df_PD_group.query('disease5==1')))
print(len(df_nPD_group.query('disease5==1')))

228
279

## 比例

In [269]:
# 從PD_group 抽 有 disease5 
df_d5_DP_group = (df_PD_group.query('disease5==1')).sample(43)
df_d5_nDP_group = (df_nPD_group.query('disease5==1')).sample(260)
print(len(df_d5_DP_group.query(' disease5==1')))
print(len(df_d5_nDP_group.query(' disease5==1')))

43
260

In [270]:
df_d5_DP_group['ID1_S'] = df_d5_DP_group['ID1_S'].astype(str)
df_d5_DP_group['age_group'] = df_d5_DP_group['age_group'].astype(str)
print(df_d5_DP_group.dtypes)

ID               object
ID1              object
ID1_DIVISION      int64
ID1_UNIT         object
ID_ROC            int64
ID_S              int64
ID1_ROC           int64
ID1_S            object
ID_BIRTH_Y        int64
ID1_TYPE         object
ID_RELATION     float64
ID1_AMT         float64
ID1_IDENT        object
PREM_YM           int64
ID_STATUS         int64
ID1_MARK         object
FAM_CONT_Y      float64
FAM_CONT_N      float64
ID1_CITY          int64
PD                int64
disease1          int64
disease2          int64
disease3          int64
disease4          int64
disease5          int64
disease6          int64
disease7          int64
city             object
Age               int64
age_group        object
dtype: object

In [271]:
import pandas as pd

# 假设您的 DataFrame 是 df，并且其中有一列名为 'age_groups'
# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
df_d5_DP_group['age_group'] = df_d5_DP_group['age_group'].str.strip()
# 使用 value_counts() 方法统计每个年龄组的数量
#age_group_counts =df_d5_DP_group ['age_group'].value_counts()
age_group_counts = df_d5_DP_group['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_M = df_d5_DP_group.query('ID1_S==1')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d5_DP_group.query('ID1_S==2')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
print(age_group_counts)

# 显示结果
# print(age_group_counts)
# print(age_group_counts2)
# print(age_group_counts.index.tolist())
# print(all_age_groups)

age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     0
50-54     0
55-59     0
60-64     1
65-69     2
70-74    13
75-79     8
80-84     5
85~      14
Name: count, dtype: int64

In [272]:
import pandas as pd

# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']

# 数据清理
# 去除 'age_group' 列中值的前后空格
df_d5_DP_group['age_group'] = df_d5_DP_group['age_group'].str.strip()

# 确保 'ID1_S' 和 'ID' 列的数据类型正确
df_d5_DP_group['ID1_S'] = df_d5_DP_group['ID1_S'].astype(int)
df_d5_DP_group['ID'] = df_d5_DP_group['ID'].astype(str)

# 将 'age_group' 列转换为分类数据类型，确保顺序正确
df_d5_DP_group['age_group'] = pd.Categorical(df_d5_DP_group['age_group'], categories=all_age_groups, ordered=True)

# 按性别过滤数据
# 男性数据（ID1_S == 1）
df_d5_DP_M = df_d5_DP_group[df_d5_DP_group['ID1_S'] == 1]
df_d5_DP_F = df_d5_DP_group[df_d5_DP_group['ID1_S'] == 2]

# 按年龄组统计男性的 ID 数量
age_group_counts_M = df_d5_DP_M.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d5_DP_F.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
# 显示结果
print("男性各年龄组的 ID 数量：")
print(age_group_counts_M)
print(age_group_counts_F)
NP_PD_d5_M = age_group_counts_M.to_numpy()
NP_PD_d5_F = age_group_counts_F.to_numpy()
print(NP_PD_d5_M)

男性各年龄组的 ID 数量：
age_group
0-4      0
5-9      0
10-14    0
15-19    0
20-24    0
25-29    0
30-34    0
35-39    0
40-44    0
45-49    0
50-54    0
55-59    0
60-64    1
65-69    2
70-74    4
75-79    7
80-84    0
85~      4
Name: ID, dtype: int64
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     0
50-54     0
55-59     0
60-64     0
65-69     0
70-74     9
75-79     1
80-84     5
85~      10
Name: ID, dtype: int64
[0 0 0 0 0 0 0 0 0 0 0 0 1 2 4 7 0 4]

In [273]:
df_d5_DP_group.dtypes

ID                object
ID1               object
ID1_DIVISION       int64
ID1_UNIT          object
ID_ROC             int64
ID_S               int64
ID1_ROC            int64
ID1_S              int64
ID_BIRTH_Y         int64
ID1_TYPE          object
ID_RELATION      float64
ID1_AMT          float64
ID1_IDENT         object
PREM_YM            int64
ID_STATUS          int64
ID1_MARK          object
FAM_CONT_Y       float64
FAM_CONT_N       float64
ID1_CITY           int64
PD                 int64
disease1           int64
disease2           int64
disease3           int64
disease4           int64
disease5           int64
disease6           int64
disease7           int64
city              object
Age                int64
age_group       category
dtype: object

In [274]:
import pandas as pd

who2000 = pd.read_csv('data/who2000.csv')
# 定义所有可能的 `ID1_S` 和 `age_group` 组合
all_ID1_S = ['1', '2']
#all_age_groups = who2000['AGE']
# 确保 ID1_S 是整数类型
df_d5_nDP_group['ID1_S'] = df_d5_nDP_group['ID1_S'].astype(int)

# 确保 age_group 列没有多余空格
df_d5_nDP_group['age_group'] = df_d5_nDP_group['age_group'].str.strip()

all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
# 去除 'age_group' 列中值的前后空格
df_d5_DP_group['age_group'] = df_d5_DP_group['age_group'].str.strip()

# 创建 MultiIndex，包含所有可能的组合
index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])

# 男性组
# 男性组
whole_nPD_M = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d5_nDP_group[(df_d5_nDP_group['ID1_S'] == 1) & (df_d5_nDP_group['age_group'] == all_age_groups[i])]
    # 打印每个分组数据以调试
    #print(f"男性组第{i}组数据:\n", data)
    whole_nPD_M[i] = data if not data.empty else pd.DataFrame(columns=df_d5_nDP_group.columns).reindex(
        index=[(1, all_age_groups[i])])

# 女性组
whole_nPD_F = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d5_nDP_group.query(f'ID1_S == 2 and age_group == "{all_age_groups[i]}"')
    # 打印每个分组数据以调试
    print(f"女性组第{i}组数据:\n", data)
    whole_nPD_F[i] = data if not data.empty else pd.DataFrame(columns=df_d5_nDP_group.columns).reindex(
        index=[(2, all_age_groups[i])])

女性组第0组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第1组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第2组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第3组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第4组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第5组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第6组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第7组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第8组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第9组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第10组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3047  [%[{=&=>/>{_  [%[{=&=>/>{_             2      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3047        0      2        1962        2  ...         0         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3047         1         1        0         0   桃園市   52      50-54

[1 rows x 30 columns]
女性组第11组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3201  !%!!+]&!~>*~  !%!!+]&!~>*~             5      12H       0     2
3203  ~]~)^@!"@<\$  ~]~)^@!"@<\$             1      12H       0     2
3215  _%_$>$(>{%)-  _%_$>$(>{%)-             2       21       0     2
3188  %]%)}@/-!~-*  %]%)}@/-!~-*             1       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3201        0      2        1955        B  ...         0         0        0
3203        0      2        1958        2  ...         0         0        0
3215        0      2        1957        2  ...         0         0        0
3188        0      2        1956        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3201         1         1        0         0   屏東縣   59      55-59
3203         0         1        0         1   台北市   56      55-59
3215         0         1        1         0   桃園市   57      55-59
3188         0         1        0         0   台北市   58      55-59

[4 rows x 30 columns]
女性组第12组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3440  !%!>=&({)(/&  !%!>=&({)(/&             4       21       0     2
3288  /]/<{-#+@~<%  /]/<{-#+@~<%             3       21       0     2
3277  [][[$#\^:#="  [][[$#\^:#="             1       21       0     2
3400  #]#^)]>_]\+]  #]#^)]>_]\+]             2       21       0     2
3407  !%!\=$<:&%{(  !%!\=$<:&%{(             3      31Q       0     2
3396  +%+)&@-[)={)  +%+)&@-[)={)             5       21       0     2
3377  =%=!)/:<=~^%  =%=!)/:<=~^%             5       21       0     2
3371  $%$~]</-^:>#  $%$~]</-^:>#             1       21       0     2
3335  {]{;(@*$>*{]  {]{;(@*$>*{]             1       62       0     2
3412  -]-;<#-+^_%(  -]-;<#-+^_%(             1      12H       0     2
3355  ~%~<-@&]@>}/  ~%~<-@&]@>}/             4       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3440        0      2        1954        2  ...         0         1        0
3288        0      2        1952        2  ...         0         0        0
3277        0      2        1953        2  ...         0         0        0
3400        0      2        1953        2  ...         0         0        1
3407        0      2        1954        2  ...         0         0        0
3396        0      2        1953        2  ...         0         1        0
3377        0      2        1954        2  ...         1         0        0
3371        0      2        1953        2  ...         0         0        0
3335        0      2        1950        2  ...         1         0        0
3412        0      2        1950        2  ...         1         0        1
3355        0      2        1954        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3440         0         1        0         0   台南市   60      60-64
3288         0         1        0         0   台中市   62      60-64
3277         0         1        1         0   新北市   61      60-64
3400         0         1        0         0   桃園市   61      60-64
3407         0         1        0         0   彰化縣   60      60-64
3396         1         1        0         0   高雄市   61      60-64
3377         1         1        0         0   澎湖縣   60      60-64
3371         0         1        0         0   台北市   61      60-64
3335         1         1        0         0   台北市   64      60-64
3412         0         1        0         0   新北市   64      60-64
3355         0         1        0         0   台南市   60      60-64

[11 rows x 30 columns]
女性组第13组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3542  ]]]!%&)"/";>  ]]]!%&)"/";>             5       62       0     2
3570  ~]~~}#&#;\!@  ~]~~}#&#;\!@             1       62       0     2
3536  #]#&&)&;>-^$  #]#&&)&;>-^$             5       21       0     2
3562  "%"*}>-<"=]#  "%"*}>-<"=]#             1      11B       0     2
3526  %]%]"[+!~{":  %]%]"[+!~{":             5       32       0     2
3549  <%<}}@!/$/\/  <%<}}@!/$/\/             1       62       0     2
3590  #]#@+<&_{=>#  #]#@+<&_{=>#             4       32       0     2
3580  {]{"+)(!!:[{  {]{"+)(!!:[{             1      31Q       0     2
3471  @]@!*&-!-&[/  @]@!*&-!-&[/             4       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3542        0      2        1946        2  ...         0         0        0
3570        0      2        1949        2  ...         1         0        0
3536        0      2        1948        2  ...         0         0        0
3562        0      2        1947        2  ...         0         0        0
3526        0      2        1949        2  ...         1         0        0
3549        0      2        1947        2  ...         1         0        0
3590        0      2        1949        2  ...         0         0        0
3580        0      2        1948        2  ...         0         1        0
3471        0      2        1947        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3542         0         1        0         0   高雄市   68      65-69
3570         1         1        1         0   台北市   65      65-69
3536         0         1        1         0   屏東縣   66      65-69
3562         0         1        0         0   新北市   67      65-69
3526         1         1        0         0   高雄市   65      65-69
3549         1         1        0         0   基隆市   67      65-69
3590         0         1        0         0   雲林縣   65      65-69
3580         0         1        1         0   宜蘭縣   66      65-69
3471         0         1        0         1   嘉義縣   67      65-69

[9 rows x 30 columns]
女性组第14组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3936  >%>[%-%\!+#~  >%>[%-%\!+#~             4      31Q       0     2
3646  }]}#[-!=~=="  }]}#[-!=~=="             4       62       0     2
4155  {]{:~&~;)#)[  {]{:~&~;)#)[             2       21       0     2
3811  #%#!"["~_][#  #%#!"["~_][#             2       62       0     2
4000  +]+&]]:_#;+^  +]+&]]:_#;+^             4      31Q       0     2
4157  {]{[;-$/#>@<  {]{[;-$/#>@<             2      31Q       0     2
4085  $]$-;$(:~[*{  $]$-;$(:~[*{             1       62       0     2
3645  -%-]_&/-![>&  -%-]_&/-![>&             1       62       0     2
4165  _]_:;$@;/*#!  _]_:;$@;/*#!             1       62       0     2
4139  }]}@"<__$&/-  }]}@"<__$&/-             1       62       0     2
4138  ]%][)@[;*[^~  ]%][)@[;*[^~             5      31Q       0     2
3758  <%<]/"~:{#+"  <%<]/"~:{#+"             1      12H       0     2
3732  :%:>%/>:/"""  :%:>%/>:/"""             1       62       0     2
4142  !%!(*[{(:\<~  !%!(*[{(:\<~             1       62       0     2
3797  >]>}#)}=<$])  >]>}#)}=<$])             4      31Q       0     2
4029  !]!}*/(}\$}!  !]!}*/(}\$}!             4       62       0     2
4086  )])@*]\%"&=&  )])@*]\%"&=&             3      31Q       0     2
3822  >]>}#)}=<$])  >]>}#)}=<$])             4      31Q       0     2
3721  +%+_/&#)%/@(  +%+_/&#)%/@(             3      31Q       0     2
3889  ;];]_$^>)"!(  ;];]_$^>)"!(             4      31Q       0     2
3934  +%+!=[#][/$<  +%+!=[#][/$<             5       32       0     2
3869  :%:>%/>:/"""  :%:>%/>:/"""             1       62       0     2
3968  +%+-<{{^@[[(  +%+-<{{^@[[(             1       62       0     2
3955  \%\+~<)]"-{>  \%\+~<)]"-{>             5      31Q       0     2
3755  !%!(*[{(:\<~  !%!(*[{(:\<~             1       62       0     2
3733  "]";&]"[:&+>  "]";&]"[:&+>             2       62       0     2
3722  +%+}})"^@=$^  +%+}})"^@=$^             6       62       0     2
3999  _]_)}/(:#_%/  _]_)}/(:#_%/             4      31Q       0     2
3938  ]]]<{@^>@(_;  ]]]<{@^>@(_;             1      12H       0     2
3653  -]-]\[<[:~;^  -]-]\[<[:~;^             4      31Q       0     2
3824  &%&=%>~:]+(]  &%&=%>~:]+(]             5      31Q       0     2
3974  (](%_[;_(![_  (](%_[;_(![_             3      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3936        0      2        1943        2  ...         0         0        0
3646        0      2        1941        A  ...         1         0        0
4155        0      2        1944        2  ...         1         0        0
3811        0      2        1940        2  ...         0         0        0
4000        0      2        1944        2  ...         0         0        0
4157        0      2        1942        2  ...         1         0        0
4085        0      2        1941        A  ...         1         0        0
3645        0      2        1943        2  ...         0         0        0
4165        0      2        1940        A  ...         0         0        1
4139        0      2        1942        A  ...         1         1        0
4138        0      2        1943        2  ...         1         0        0
3758        0      2        1943        2  ...         0         1        0
3732        0      2        1944        A  ...         1         0        0
4142        0      2        1941        A  ...         0         0        1
3797        0      2        1942        2  ...         0         0        0
4029        0      2        1941        A  ...         0         0        0
4086        0      2        1941        2  ...         0         0        0
3822        0      2        1942        2  ...         0         0        0
3721        0      2        1940        2  ...         1         0        0
3889        0      2        1941        2  ...         1         0        0
3934        0      2        1941        2  ...         1         0        0
3869        0      2        1944        A  ...         1         0        0
3968        0      2        1940        A  ...         0         1        0
3955        0      2        1942        2  ...         1         0        0
3755        0      2        1941        A  ...         0         0        1
3733        0      2        1941        A  ...         1         0        0
3722        0      2        1944        A  ...         0         0        1
3999        0      2        1942        2  ...         1         0        0
3938        0      2        1942        2  ...         0         0        0
3653        0      2        1941        2  ...         0         0        0
3824        0      2        1942        2  ...         0         0        0
3974        0      2        1941        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3936         0         1        0         0   雲林縣   71      70-74
3646         1         1        0         0   嘉義縣   73      70-74
4155         0         1        1         0   苗栗縣   70      70-74
3811         1         1        0         0   桃園市   74      70-74
4000         0         1        0         0   雲林縣   70      70-74
4157         0         1        0         0   桃園市   72      70-74
4085         0         1        0         0   新北市   73      70-74
3645         0         1        0         1   新北市   71      70-74
4165         1         1        1         0   新北市   74      70-74
4139         0         1        0         0   新北市   72      70-74
4138         0         1        0         0   高雄市   71      70-74
3758         1         1        1         0   台北市   71      70-74
3732         1         1        1         0   宜蘭縣   70      70-74
4142         1         1        1         1   新北市   73      70-74
3797         0         1        0         0   雲林縣   72      70-74
4029         1         1        0         0   台南市   73      70-74
4086         0         1        0         0   彰化縣   73      70-74
3822         0         1        0         0   雲林縣   72      70-74
3721         1         1        0         0   南投縣   74      70-74
3889         1         1        0         0   嘉義縣   73      70-74
3934         0         1        0         0   澎湖縣   73      70-74
3869         1         1        1         0   宜蘭縣   70      70-74
3968         0         1        0         0   台北市   74      70-74
3955         0         1        0         0   屏東縣   72      70-74
3755         1         1        1         1   新北市   73      70-74
3733         1         1        1         0   桃園市   73      70-74
3722         0         1        0         0   花蓮縣   70      70-74
3999         0         1        0         0   雲林縣   72      70-74
3938         1         1        1         0   新北市   72      70-74
3653         0         1        0         0   雲林縣   73      70-74
3824         0         1        0         0   屏東縣   72      70-74
3974         0         1        0         0   台中市   73      70-74

[32 rows x 30 columns]
女性组第15组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4562  "%"%$"^/"})*  "%"%$"^/"})*             5       62       0     2
4446  /]/#_)@]\[]-  /]/#_)@]\[]-             5      31Q       0     2
4500  ;];#;@:"@=#{  ;];#;@:"@=#{             3      31Q       0     2
4499  !]!:]"\$@;({  !]!:]"\$@;({             5       21       0     2
4467  >]>"("(<@{{:  >]>"("(<@{{:             4      31Q       0     2
4584  %]%)/#_[&^#&  %]%)/#_[&^#&             2      31Q       0     2
4548  {%{=+{@^!"/(  {%{=+{@^!"/(             3      31Q       0     2
4204  /%/--{#]{=+!  /%/--{#]{=+!             4      31Q       0     2
4258  $%$->$~^[&*#  $%$->$~^[&*#             4      31Q       0     2
4592  %]%;(/-@&-&_  %]%;(/-@&-&_             1       21       0     2
4472  ^]^*!>>["-$~  ^]^*!>>["-$~             3      31Q       0     2
4198  ;];{{]^+<;(^  ;];{{]^+<;(^             4      31Q       0     2
4425  )])(\#<>;-*+  )])(\#<>;-*+             5      31Q       0     2
4197  ~]~}{{++\/_{  ~]~}{{++\/_{             2      31Q       0     2
4399  ^]^~^]+<>:!)  ^]^~^]+<>:!)             5      31Q       0     2
4493  ~%~("/~="-%\  ~%~("/~="-%\             2       62       0     2
4486  ;];{{]^+<;(^  ;];{{]^+<;(^             4      31Q       0     2
4431  %%%#@)<$;\<&  %%%#@)<$;\<&             1       62       0     2
4464  {%{@;[[<%{{-  {%{@;[[<%{{-             4      31Q       0     2
4417  $]$+={;+[/>;  $]$+={;+[/>;             5      31Q       0     2
4182  *]*><[:>&\"~  *]*><[:>&\"~             5      31Q       0     2
4321  -%-_[{>^\;(/  -%-_[{>^\;(/             5      31Q       0     2
4401  "%"!#"}~\{&[  "%"!#"}~\{&[             4      31Q       0     2
4553  -%-_[{>^\;(/  -%-_[{>^\;(/             5      31Q       0     2
4589  _%_(=@>#@/{]  _%_(=@>#@/{]             1       62       0     2
4235  ;];/}#&}(~%^  ;];/}#&}(~%^             1       62       0     2
4524  <%<@%/=#)!%>  <%<@%/=#)!%>             2       62       0     2
4187  }%}&+/"[[]^]  }%}&+/"[[]^]             5       62       0     2
4287  *]*\:)}-%&>{  *]*\:)}-%&>{             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
4562        0      2        1936        A  ...         1         0        1
4446        0      2        1938        2  ...         1         0        0
4500        0      2        1937        2  ...         0         0        1
4499        0      2        1937        2  ...         0         0        1
4467        0      2        1936        2  ...         1         0        0
4584        0      2        1939        2  ...         0         0        0
4548        0      2        1936        2  ...         1         0        0
4204        0      2        1939        2  ...         1         0        1
4258        0      2        1939        2  ...         1         0        0
4592        0      2        1938        2  ...         1         0        0
4472        0      2        1938        2  ...         0         0        1
4198        0      2        1935        2  ...         1         0        0

In [275]:
nPD_d5_M = []
nPD_d5_F = []

# 使用 whole_nPD_M 字典中的分组进行采样
for i in range(18):
    nPD_d5_M.append(whole_nPD_M[i].sample(n=NP_PD_d5_F[i] * 2, replace=True))

# 使用 whole_nPD_F 字典中的分组进行采样
for i in range(18):
    nPD_d5_F.append(whole_nPD_F[i].sample(n=NP_PD_d5_M[i] * 2, replace=True))

In [276]:
for i in range(18):
    print(len(nPD_d5_M[i]))
for i in range(18):
    print(len(nPD_d5_F[i]))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
18
2
10
20
0
0
0
0
0
0
0
0
0
0
0
0
2
4
8
14
0
8

In [277]:
# 为女性组数据添加一个标记列，并垂直合并
for i in range(18):
    nPD_d5_age_F = pd.concat([nPD_d5_F[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d5_age_F))
for i in range(18):

    nPD_d5_age_M = pd.concat([nPD_d5_M[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d5_age_M))
nPD_d5_age = pd.concat([nPD_d5_age_F, nPD_d5_age_M], axis=0, ignore_index=True)

print("all:", len(nPD_d5_age))
# print(nPD_d5_age)

36
50
all: 86

In [278]:
print(len(df_d5_DP_group))

43

# 結果

In [279]:
# #odds ratio語法
# import pandas as pd
# import numpy as np
# from scipy.stats import fisher_exact
# import statsmodels.api as sm
# from statsmodels.stats.contingency_tables import Table2x2
# from datetime import datetime
# #合併PD與nPD
# df_d5_PDandnPD=pd.concat([df_d5_DP_group,nPD_d5_age])
# # 創建交叉表
# contingency_table = pd.crosstab(df_d5_PDandnPD['PD'], df_d5_PDandnPD['disease5'])
# print(contingency_table.shape)
# # 計算odds ratio和p-value
# odds_ratio, p_value = fisher_exact(contingency_table)
# 
# # 計算odds ratio的信賴區間
# table = Table2x2(contingency_table.values)
# confidence_interval = table.oddsratio_confint()
# 
# print(f'Odds Ratio: {odds_ratio}')
# print(f'p-value: {p_value}')
# print(f'Confidence Interval: {confidence_interval}')
# if p_value < 0.05:
#     print("\nfail")
# else:
#     print("\npass")
#     
#     nowtime = datetime.now().strftime("%Y%m%d_%H%M")
#     pass_csvFileName=f'd5_pass_PDandnPD{nowtime}.csv'
#     print(pass_csvFileName)    
#     df_d5_PDandnPD.to_csv(f'data/{pass_csvFileName}', index=False)

In [280]:
import pandas as pd
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime

# 假设 df_d5_PDandnPD 是您的合并数据集
df_d5_PDandnPD = pd.concat([df_d5_DP_group, nPD_d5_age])

# 存储结果的列表
results = []
sumP=0
# 遍历 disease1 到 disease7
for n in range(1, 8):
    disease_col = f'disease{n}'
    
    # 筛选出 diseaseN == 1 的样本
    # disease_data = df_d1_PDandnPD[df_d1_PDandnPD[disease_col] == 1]
    
    # 创建 PD 与当前疾病的交叉表
    contingency_table = pd.crosstab(df_d5_PDandnPD['PD'], df_d5_PDandnPD[disease_col])
    
    # 检查表格是否为 2x2
    if contingency_table.shape == (2, 2):
        # 计算 Odds Ratio 和 p 值
        odds_ratio, p_value = fisher_exact(contingency_table)
        
        # 计算置信区间
        table = Table2x2(contingency_table.values)
        confidence_interval = table.oddsratio_confint()
        
        # 记录结果
        results.append({
            'Disease': disease_col,
            'Odds Ratio': odds_ratio,
            'p-value': p_value,
            'Confidence Interval': confidence_interval
        })
        
        # 输出结果
        print(f'\n{disease_col}:')
        print(f'Odds Ratio: {odds_ratio}')
        print(f'p-value: {p_value}')
        print(f'Confidence Interval: {confidence_interval}')
        
        # 检查 p 值
        if p_value < 0.05:
             print("Y_顯著")
        else:
            print("N_不顯著")
            sumP+=1
    else:
        print(f'\n{disease_col}:')
        print("X_交叉表不是 2x2，无法计算统计量。请检查数据。")
print(sumP)

disease1:
Odds Ratio: 1.4598930481283423
p-value: 0.3526741541533128
Confidence Interval: (0.694244769674002, 3.0699370093551543)
N_不顯著

disease2:
Odds Ratio: 0.0
p-value: 0.3004975940507437
Confidence Interval: (0.012314981856094774, 4.613994189862858)
N_不顯著

disease3:
Odds Ratio: 1.1869565217391305
p-value: 0.682255636264648
Confidence Interval: (0.5295178642529026, 2.660657703185944)
N_不顯著

disease4:
Odds Ratio: 0.5202839756592292
p-value: 0.15518015705820853
Confidence Interval: (0.22015536884061393, 1.2295653599242862)
N_不顯著

disease5:
X_交叉表不是 2x2，无法计算统计量。请检查数据。

disease6:
Odds Ratio: 0.5656565656565656
p-value: 0.270037884345167
Confidence Interval: (0.22019743407007444, 1.4530930009318617)
N_不顯著

disease7:
Odds Ratio: 1.4849624060150375
p-value: 0.5327405442201321
Confidence Interval: (0.4423202736154258, 4.985331848467791)
N_不顯著
6

In [281]:
# !ls ~/df_outData

In [282]:
if sumP == 6:
    df_d5_PDandnPD.to_csv('data/out/pass6_d5.csv', index=False)
    print("\npass6_d5.csv")

pass6_d5.csv

In [283]:
# !ls ./data

In [284]:
# !cp ./data/{pass_csvFileName} ~/df_outData/

In [285]:
# !ls ~/df_outData

In [286]:
# df_d5_PDandnPD