In [463]:
import sys

from numpy.testing.print_coercion_tables import print_coercion_table

# from time import process_time_ns

# from scipy.misc.tests.test_doccer import param_doc2

print("start")
print(sys.version)
import os
import pandas as pd

os.getcwd()

start
3.8.20 (default, Oct  3 2024, 10:22:23)
[Clang 14.0.6 ]

'/Users/lai_zx/PycharmProjects/HH_DB'

### 資料載入 PD_group nPD_group

In [464]:
df_PD_group = pd.read_csv('data/PD_group_utf8.csv')
df_nPD_group = pd.read_csv('data/nPD_group_utf8.csv')

In [465]:
print(df_nPD_group.info)
print(df_PD_group.info)

<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     $]$>^"^>%]{$  $]$>^"^>%]{$             1      12H       0     1
1     /%/;#[@""^]~  /%/;#[@""^]~             4      12H       0     1
2     <]<*]#:*-:;=  <]<*]#:*-:;=             2      12H       0     1
3     }%}_~#<^!-%!  }%}_~#<^!-%!             1       62       0     1
4     @]@[$-!~)@}*  @]@[$-!~)@}*             3      12H       0     1
...            ...           ...           ...      ...     ...   ...
5445  ;];;%>:&%"-@  ;];;%>:&%"-@             4      31Q       0     2
5446  ~]~/&]!-@"(%  #%#<}-:^-{%{             5       21       0     2
5447  @%@#&$]~]&!=  @%@#&$]~]&!=             2       62       0     2
5448  +%+!<<>^/&~+  +%+!<<>^/&~+             3      31Q       0     2
5449  _%_*"$[%<-_-  _%_*"$[%<-_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      1        1984        2  ...         0         0        0
1           0      1        1981        2  ...         0         0        0
2           0      1        1982        2  ...         0         0        0
3           0      1        1981        2  ...         0         0        0
4           0      1        1982        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
5445        0      2        1929        2  ...         0         0        0
5446        0      2        1926        2  ...         0         0        0
5447        0      2        1924        2  ...         0         0        0
5448        0      2        1925        2  ...         0         0        0
5449        0      2        1927        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            0         0        0         0   台北市   30  30-34
1            0         0        0         0   雲林縣   33  30-34
2            0         0        0         0   新竹縣   32  30-34
3            0         0        0         0   新北市   33  30-34
4            0         0        0         0   彰化縣   32  30-34
...        ...       ...      ...       ...   ...  ...         ...
5445         0         0        1         0   嘉義縣   85  85~
5446         0         0        0         0   屏東縣   88  85~
5447         0         0        0         0   新竹縣   90  85~
5448         0         0        1         0   台中市   89  85~
5449         0         0        0         0   嘉義市   87  85~

[5450 rows x 30 columns]>
<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     )]))<@%/-@/\  )]))<@%/-@/\             1      31Q       0     2
1     )])->[[_;"}+  )])->[[_;"}+             3       62       0     2
2     )])/;&*^})\_  )])/;&*^})\_             3      31Q       0     2
3     )%):~-[#[%/=  )%):~-[#[%/=             4      31Q       0     2
4     )%)_#)]_>)-{  )%)_#)]_>)-{             3      31Q       0     1
...            ...           ...           ...      ...     ...   ...
2720  (%({_[-}]%%/  (%({_[-}]%%/             5       62       0     2
2721  (%(/:#=${(<"  (%(/:#=${(<"             1       62       0     1
2722  (%(/&<[!>=^!  (%(/&<[!>=^!             1       62       0     2
2723  (%([]$!-$\]]  (%([]$!-$\]]             4      31Q       0     2
2724  (%(&<]")^&+<  (%(&<]")^&+<             4       62       0     1

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      2        1926        2  ...         1         0        0
1           0      2        1928        2  ...         1         0        0
2           0      2        1923        2  ...         0         0        0
3           0      2        1922        2  ...         0         0        0
4           0      1        1941        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
2720        0      2        1915        2  ...         0         0        1
2721        0      1        1974        2  ...         0         0        0
2722        0      2        1941        A  ...         0         0        1
2723        0      2        1933        2  ...         1         0        0
2724        0      1        1953        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            1         0        0         0   宜蘭縣   88  85~
1            0         1        0         0   南投縣   86  85~
2            0         1        0         0   彰化縣   91  85~
3            0         0        0         0   雲林縣   92  85~
4            0         0        0         0   南投縣   73  70-74
...        ...       ...      ...       ...   ...  ...         ...
2720         0         0        0         0   屏東縣   99  85~
2721         0         0        0         0   台北市   40  40-44
2722         1         0        1         0   新北市   73  70-74
2723         0         0        0         0   嘉義縣   81  80-84
2724         0         0        0         0   台南市   61  60-64

[2725 rows x 30 columns]>

### disease4

In [466]:
print(len(df_PD_group.query('disease4==1')))
print(len(df_nPD_group.query('disease4==1')))

423
597

## 比例

In [467]:
# 從PD_group 抽 有 disease4 
df_d4_DP_group = (df_PD_group.query('disease4==1')).sample(90)
df_d4_nDP_group = (df_nPD_group.query('disease4==1')).sample(550)
print(len(df_d4_DP_group.query(' disease4==1')))
print(len(df_d4_nDP_group.query(' disease4==1')))

90
550

In [468]:
df_d4_DP_group['ID1_S'] = df_d4_DP_group['ID1_S'].astype(str)
df_d4_DP_group['age_group'] = df_d4_DP_group['age_group'].astype(str)
print(df_d4_DP_group.dtypes)

ID               object
ID1              object
ID1_DIVISION      int64
ID1_UNIT         object
ID_ROC            int64
ID_S              int64
ID1_ROC           int64
ID1_S            object
ID_BIRTH_Y        int64
ID1_TYPE         object
ID_RELATION     float64
ID1_AMT         float64
ID1_IDENT        object
PREM_YM           int64
ID_STATUS         int64
ID1_MARK         object
FAM_CONT_Y      float64
FAM_CONT_N      float64
ID1_CITY          int64
PD                int64
disease1          int64
disease2          int64
disease3          int64
disease4          int64
disease5          int64
disease6          int64
disease7          int64
city             object
Age               int64
age_group        object
dtype: object

In [469]:
import pandas as pd

# 假设您的 DataFrame 是 df，并且其中有一列名为 'age_groups'
# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
df_d4_DP_group['age_group'] = df_d4_DP_group['age_group'].str.strip()
# 使用 value_counts() 方法统计每个年龄组的数量
#age_group_counts =df_d4_DP_group ['age_group'].value_counts()
age_group_counts = df_d4_DP_group['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_M = df_d4_DP_group.query('ID1_S==1')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d4_DP_group.query('ID1_S==2')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
print(age_group_counts)

# 显示结果
# print(age_group_counts)
# print(age_group_counts2)
# print(age_group_counts.index.tolist())
# print(all_age_groups)

age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     5
45-49     1
50-54     3
55-59    12
60-64     1
65-69    13
70-74    21
75-79    11
80-84     8
85~      15
Name: count, dtype: int64

In [470]:
import pandas as pd

# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']

# 数据清理
# 去除 'age_group' 列中值的前后空格
df_d4_DP_group['age_group'] = df_d4_DP_group['age_group'].str.strip()

# 确保 'ID1_S' 和 'ID' 列的数据类型正确
df_d4_DP_group['ID1_S'] = df_d4_DP_group['ID1_S'].astype(int)
df_d4_DP_group['ID'] = df_d4_DP_group['ID'].astype(str)

# 将 'age_group' 列转换为分类数据类型，确保顺序正确
df_d4_DP_group['age_group'] = pd.Categorical(df_d4_DP_group['age_group'], categories=all_age_groups, ordered=True)

# 按性别过滤数据
# 男性数据（ID1_S == 1）
df_d4_DP_M = df_d4_DP_group[df_d4_DP_group['ID1_S'] == 1]
df_d4_DP_F = df_d4_DP_group[df_d4_DP_group['ID1_S'] == 2]

# 按年龄组统计男性的 ID 数量
age_group_counts_M = df_d4_DP_M.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d4_DP_F.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
# 显示结果
print("男性各年龄组的 ID 数量：")
print(age_group_counts_M)
print(age_group_counts_F)
NP_PD_d4_M = age_group_counts_M.to_numpy()
NP_PD_d4_F = age_group_counts_F.to_numpy()
print(NP_PD_d4_M)

男性各年龄组的 ID 数量：
age_group
0-4      0
5-9      0
10-14    0
15-19    0
20-24    0
25-29    0
30-34    0
35-39    0
40-44    4
45-49    1
50-54    0
55-59    8
60-64    0
65-69    7
70-74    4
75-79    3
80-84    5
85~      6
Name: ID, dtype: int64
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     1
45-49     0
50-54     3
55-59     4
60-64     1
65-69     6
70-74    17
75-79     8
80-84     3
85~       9
Name: ID, dtype: int64
[0 0 0 0 0 0 0 0 4 1 0 8 0 7 4 3 5 6]

In [471]:
df_d4_DP_group.dtypes

ID                object
ID1               object
ID1_DIVISION       int64
ID1_UNIT          object
ID_ROC             int64
ID_S               int64
ID1_ROC            int64
ID1_S              int64
ID_BIRTH_Y         int64
ID1_TYPE          object
ID_RELATION      float64
ID1_AMT          float64
ID1_IDENT         object
PREM_YM            int64
ID_STATUS          int64
ID1_MARK          object
FAM_CONT_Y       float64
FAM_CONT_N       float64
ID1_CITY           int64
PD                 int64
disease1           int64
disease2           int64
disease3           int64
disease4           int64
disease5           int64
disease6           int64
disease7           int64
city              object
Age                int64
age_group       category
dtype: object

In [472]:
import pandas as pd

who2000 = pd.read_csv('data/who2000.csv')
# 定义所有可能的 `ID1_S` 和 `age_group` 组合
all_ID1_S = ['1', '2']
#all_age_groups = who2000['AGE']
# 确保 ID1_S 是整数类型
df_d4_nDP_group['ID1_S'] = df_d4_nDP_group['ID1_S'].astype(int)

# 确保 age_group 列没有多余空格
df_d4_nDP_group['age_group'] = df_d4_nDP_group['age_group'].str.strip()

all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
# 去除 'age_group' 列中值的前后空格
df_d4_DP_group['age_group'] = df_d4_DP_group['age_group'].str.strip()

# 创建 MultiIndex，包含所有可能的组合
index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])

# 男性组
# 男性组
whole_nPD_M = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d4_nDP_group[(df_d4_nDP_group['ID1_S'] == 1) & (df_d4_nDP_group['age_group'] == all_age_groups[i])]
    # 打印每个分组数据以调试
    #print(f"男性组第{i}组数据:\n", data)
    whole_nPD_M[i] = data if not data.empty else pd.DataFrame(columns=df_d4_nDP_group.columns).reindex(
        index=[(1, all_age_groups[i])])

# 女性组
whole_nPD_F = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d4_nDP_group.query(f'ID1_S == 2 and age_group == "{all_age_groups[i]}"')
    # 打印每个分组数据以调试
    print(f"女性组第{i}组数据:\n", data)
    whole_nPD_F[i] = data if not data.empty else pd.DataFrame(columns=df_d4_nDP_group.columns).reindex(
        index=[(2, all_age_groups[i])])

女性组第0组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第1组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第2组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第3组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第4组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第5组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第6组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第7组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第8组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2966  <%<:~@[#;%&:  <%<:~@[#;%&:             2       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2966        0      2        1970        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2966         1         0        0         0   桃園市   44      40-44

[1 rows x 30 columns]
女性组第9组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3022  <]<":]}}>[_\  <]<":]}}>[_\             3      12H       0     2
2997  !%!{>$%;!\\^  !%!{>$%;!\\^             1      12H       0     2
2979  +]+;<[&";(=>  +]+;<[&";(=>             3      12F       0     2
2986  "]"+]#/(&-/{  "]"+]#/(&-/{             5       21       0     2
3019  +]+;<[&";(=>  +]+;<[&";(=>             3      12F       0     2
2991  /%/(\>{$-#("  /%/(\>{$-#("             3      11A       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3022        0      2        1965        2  ...         0         0        0
2997        0      2        1967        2  ...         0         0        0
2979        0      2        1966        2  ...         0         0        0
2986        0      2        1965        2  ...         0         0        1
3019        0      2        1966        2  ...         0         0        0
2991        0      2        1967        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3022         1         0        0         0   台中市   49      45-49
2997         1         0        0         0   新北市   47      45-49
2979         1         0        0         0   南投縣   48      45-49
2986         1         0        0         0   屏東縣   49      45-49
3019         1         0        0         0   南投縣   48      45-49
2991         1         0        0         0   南投縣   47      45-49

[6 rows x 30 columns]
女性组第10组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3087  /%/$%{&)@%;$  /%/$%{&)@%;$             5       21       0     2
3030  "%"&(">]++:@  "%"&(">]++:@             2      12H       0     2
3119  :]:\=>@(+]~&  :]:\=>@(+]~&             4      31Q       0     2
3080  ^]^*<])-}\+*  ^]^*<])-}\+*             1       62       0     2
3035  !]!%"/_>+(_:  !]!%"/_>+(_:             5       62       0     2
3042  >]>;]&%@#)^>  >]>;]&%@#)^>             2       32       0     2
3082  %]%\/&@<"*}(  %]%\/&@<"*}(             5       21       0     2
3139  :]::%@*>(%;)  :]::%@*>(%;)             5      13I       0     2
3028  #]#$\/((^"~&  #]#$\/((^"~&             2      31Q       0     2
3029  $%$@&[(!+{%"  $%$@&[(!+{%"             5      31Q       0     2
3047  [%[{=&=>/>{_  [%[{=&=>/>{_             2      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3087        0      2        1962        2  ...         0         0        0
3030        0      2        1962        2  ...         0         0        0
3119        0      2        1961        2  ...         0         0        0
3080        0      2        1962        2  ...         1         0        0
3035        0      2        1963        2  ...         0         0        1
3042        0      2        1963        2  ...         0         0        1
3082        0      2        1960        2  ...         1         0        1
3139        0      2        1960        2  ...         1         0        1
3028        0      2        1960        2  ...         0         0        1
3029        0      2        1963        2  ...         1         0        0
3047        0      2        1962        2  ...         0         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3087         1         0        1         0   高雄市   52      50-54
3030         1         0        0         0   桃園市   52      50-54
3119         1         0        0         1   雲林縣   53      50-54
3080         1         0        0         0   台北市   52      50-54
3035         1         0        1         0   高雄市   51      50-54
3042         1         0        1         0   苗栗縣   51      50-54
3082         1         0        0         0   屏東縣   54      50-54
3139         1         0        0         0   高雄市   54      50-54
3028         1         0        0         0   桃園市   54      50-54
3029         1         0        0         0   屏東縣   51      50-54
3047         1         1        0         0   桃園市   52      50-54

[11 rows x 30 columns]
女性组第11组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3148  #]#/$[<)#(:(  #]#/$[<)#(:(             4      31Q       0     2
3182  {]{/-)^{]>&<  {]{/-)^{]>&<             5      31Q       0     2
3201  !%!!+]&!~>*~  !%!!+]&!~>*~             5      12H       0     2
3150  )%)*/[-^>;^_  )%)*/[-^>;^_             5       62       0     2
3248  ~%~#&-_;-!:-  ~%~#&-_;-!:-             1       21       0     2
3237  ]]])<#]\":>;  ]]])<#]\":>;             2      11C       0     2
3159  -%-]*"(&(==(  -%-]*"(&(==(             5       21       0     2
3249  %%%;"[:]>>-[  %%%;"[:]>>-[             2       62       0     2
3256  #%#$*-<_\&=&  #%#$*-<_\&=&             3       21       0     2
3252  <]<\=>@(+]/"  <]<\=>@(+]/"             1      12H       0     2
3168  }]}%&"!*(%#)  }]}%&"!*(%#)             6      11B       0     2
3153  ;];)@>()$[}!  ;];)@>()$[}!             4      12H       0     2
3224  $]$!<$)$~)}~  $]$!<$)$~)}~             1      12H       0     2
3235  _]_#}){;]<$:  _]_#}){;]<$:             4       21       0     2
3197  ~%~(=[@{*-#<  ~%~(=[@{*-#<             3       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3148        0      2        1956        2  ...         1         0        1
3182        0      2        1957        2  ...         0         0        0
3201        0      2        1955        B  ...         0         0        0
3150        0      2        1957        2  ...         0         0        0
3248        0      2        1959        2  ...         0         0        0
3237        0      2        1955        2  ...         0         0        1
3159        0      2        1959        2  ...         1         0        1
3249        0      2        1958        A  ...         1         0        1
3256        0      2        1955        2  ...         0         0        0
3252        0      2        1957        2  ...         0         0        1
3168        0      2        1955        2  ...         0         0        0
3153        0      2        1955        2  ...         1         0        0
3224        0      2        1958        2  ...         0         0        1
3235        0      2        1957        2  ...         1         0        1
3197        0      2        1957        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3148         1         0        0         0   雲林縣   58      55-59
3182         1         0        0         0   屏東縣   57      55-59
3201         1         1        0         0   屏東縣   59      55-59
3150         1         0        0         0   屏東縣   57      55-59
3248         1         0        0         0   台北市   55      55-59
3237         1         0        0         0   桃園市   59      55-59
3159         1         0        0         1   屏東縣   55      55-59
3249         1         0        0         0   桃園市   56      55-59
3256         1         0        0         1   台中市   59      55-59
3252         1         0        0         0   台北市   57      55-59
3168         1         0        0         0   台東縣   59      55-59
3153         1         0        0         0   嘉義縣   59      55-59
3224         1         0        1         0   新北市   56      55-59
3235         1         0        0         0   台南市   57      55-59
3197         1         0        0         0   南投縣   57      55-59

[15 rows x 30 columns]
女性组第12组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3319  *]*#">"=})<^  *]*#">"=})<^             3       32       0     2
3445  ]]]{^&:!;*#{  ]]]{^&:!;*#{             1       21       0     2
3328  <%<(;$_\(>$(  <%<(;$_\(>$(             2       62       0     2
3396  +%+)&@-[)={)  +%+)&@-[)={)             5       21       0     2
3455  ;];<"#(_#[){  ;];<"#(_#[){             3      31Q       0     2
3377  =%=!)/:<=~^%  =%=!)/:<=~^%             5       21       0     2
3399  %]%[%@--:*&~  %]%[%@--:*&~             1      12M       0     2
3312  -]-~)>{]\<_$  -]-~)>{]\<_$             2       21       0     2
3374  &]&/;#+}^_-#  &]&/;#+}^_-#             2       62       0     2
3344  (](*!-$<-}%;  (](*!-$<-}%;             6      31Q       0     2
3394  $]$]@>\:<$!<  $]$]@>\:<$!<             1      12H       0     2
3431  =]=!)#~#$+}_  =]=!)#~#$+}_             1       21       0     2
3395  <%<<@@&!~;[=  <%<<@@&!~;[=             4      31Q       0     2
3285  {]{$~[%_\&*_  {]{$~[%_\&*_             4       32       0     2
3366  <%<$~>@+\]_~  <%<$~>@+\]_~             4       21       0     2
3330  "%""$]-;^"::  "%""$]-;^"::             1       32       0     2
3317  <]<\$<&+$)-_  <]<\$<&+$)-_             2       21       0     2
3335  {]{;(@*$>*{]  {]{;(@*$>*{]             1       62       0     2
3284  =]=\{@~-*&{<  =]=\{@~-*&{<             2       21       0     2
3298  (](<:{/##$%_  (](<:{/##$%_             4      31Q       0     2
3422  /%/@}$*%&\#_  /%/@}$*%&\#_             2       62       0     2
3375  >]>-=/~=:~{^  >]>-=/~=:~{^             1       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3319        0      2        1952        2  ...         0         0        0
3445        0      2        1954        2  ...         1         0        1
3328        0      2        1953        2  ...         1         0        1
3396        0      2        1953        2  ...         0         1        0
3455        0      2        1950        2  ...         1         1        0
3377        0      2        1954        2  ...         1         0        0
3399        0      2        1954        2  ...         1         1        0
3312        0      2        1953        2  ...         0         0        1
3374        0      2        1951        A  ...         0         0        1
3344        0      2        1954        2  ...         0         0        0
3394        0      2        1953        2  ...         1         0        0
3431        0      2        1950        2  ...         1         0        1
3395        0      2        1952        2  ...         1         0        1
3285        0      2        1951        2  ...         1         0        1
3366        0      2        1953        2  ...         0         0        0
3330        0      2        1950        2  ...         1         0        1
3317        0      2        1953        2  ...         0         0        1
3335        0      2        1950        2  ...         1         0        0
3284        0      2        1954        2  ...         1         1        0
3298        0      2        1953        2  ...         1         0        1
3422        0      2        1954        A  ...         1         0        0
3375        0      2        1952        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3319         1         0        0         0   彰化縣   62      60-64
3445         1         0        0         0   台北市   60      60-64
3328         1         0        0         0   桃園市   61      60-64
3396         1         1        0         0   高雄市   61      60-64
3455         1         0        0         0   彰化縣   64      60-64
3377         1         1        0         0   澎湖縣   60      60-64
3399         1         0        0         0   新北市   60      60-64
3312         1         0        0         0   新竹縣   61      60-64
3374         1         0        0         0   桃園市   63      60-64
3344         1         0        0         0   台東縣   60      60-64
3394         1         0        0         0   基隆市   61      60-64
3431         1         0        0         0   台北市   64      60-64
3395         1         0        0         0   台南市   62      60-64
3285         1         0        0         1   台南市   63      60-64
3366         1         0        0         0   台南市   61      60-64
3330         1         0        0         0   宜蘭縣   64      60-64
3317         1         0        1         0   新竹縣   61      60-64
3335         1         1        0         0   台北市   64      60-64
3284         1         0        1         0   桃園市   60      60-64
3298         1         0        0         0   雲林縣   61      60-64
3422         1         0        1         0   新竹縣   60      60-64
3375         1         0        0         0   新北市   62      60-64

[22 rows x 30 columns]
女性组第13组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3466  /]/-->/"/<>$  /]/-->/"/<>$             5      12H       0     2
3485  *%*/\&"+(+(;  *%*/\&"+(+(;             2      31Q       0     2
3594  [][;+/${;=@[  [][;+/${;=@[             1       21       0     2
3526  %]%]"[+!~{":  %]%]"[+!~{":             5       32       0     2
3592  @]@:->[{~%$#  @]@:->[{~%$#             4       21       0     2
3480  ;%;)[)\<(>:-  ;%;)[)\<(>:-             4      31Q       0     2
3549  <%<}}@!/$/\/  <%<}}@!/$/\/             1       62       0     2
3570  ~]~~}#&#;\!@  ~]~~}#&#;\!@             1       62       0     2
3579  $]$]_$$#~;\&  $]$]_$$#~;\&             4       62       0     2
3508  =%=\%{)=$;)@  =%=\%{)=$;)@             1      12H       0     2
3533  _%_%_>&;$]=+  _%_%_>&;$]=+             1       62       0     2
3529  <]<*(#^#&$=^  <]<*(#^#&$=^             1      31Q       0     2
3575  "]"^/&!^/$-~  "]"^/&!^/$-~             5       62       0     2
3461  !]!$){]}%%\<  !]!$){]}%%\<             4       21       0     2
3496  $]$[*$@"[\%#  $]$[*$@"[\%#             1       62       0     2
3597  @%@_-<[}:^=_  @%@_-<[}:^=_             3       62       0     2
3491  *]*-+@<\_=++  *]*-+@<\_=++             4       21       0     2
3561  @%@^>@_/(];~  @%@^>@_/(];~             1      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3466        0      2        1946        2  ...         0         0        0
3485        0      2        1945        2  ...         0         0        1
3594        0      2        1945        2  ...         0         1        1
3526        0      2        1949        2  ...         1         0        0
3592        0      2        1949        2  ...         1         0        1
3480        0      2        1949        2  ...         0         0        0
3549        0      2        1947        2  ...         1         0        0
3570        0      2        1949        2  ...         1         0        0
3579        0      2        1946        2  ...         1         0        0
3508        0      2        1947        B  ...         0         0        1
3533        0      2        1946        2  ...         1         0        0
3529        0      2        1948        2  ...         0         0        0
3575        0      2        1946        2  ...         0         0        0
3461        0      2        1949        2  ...         0         0        1
3496        0      2        1949        2  ...         1         0        0
3597        0      2        1945        A  ...         1         1        0
3491        0      2        1949        2  ...         1         0        0
3561        0      2        1947        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3466         1         0        0         0   高雄市   68      65-69
3485         1         0        0         1   新竹市   69      65-69
3594         1         0        0         0   台北市   69      65-69
3526         1         1        0         0   高雄市   65      65-69
3592         1         0        0         0   台南市   65      65-69
3480         1         0        1         0   台南市   65      65-69
3549         1         1        0         0   基隆市   67      65-69
3570         1         1        1         0   台北市   65      65-69
3579         1         0        1         0   台南市   68      65-69
3508         1         0        0         0   台北市   67      65-69
3533         1         0        0         0   基隆市   68      65-69
3529         1         0        1         0   宜蘭縣   66      65-69
3575         1         0        0         0   高雄市   68      65-69
3461         1         0        0         0   台南市   65      65-69
3496         1         1        0         0   台北市   65      65-69
3597         1         0        0         0   南投縣   69      65-69
3491         1         0        0         0   台南市   65      65-69
3561         1         0        0         0   新北市   67      65-69

[18 rows x 30 columns]
女性组第14组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3919  !]!%*"$!]"+_  !]!%*"$!]"+_             3      31Q       0     2

In [473]:
nPD_d4_M = []
nPD_d4_F = []

# 使用 whole_nPD_M 字典中的分组进行采样
for i in range(18):
    nPD_d4_M.append(whole_nPD_M[i].sample(n=NP_PD_d4_F[i] * 2, replace=True))

# 使用 whole_nPD_F 字典中的分组进行采样
for i in range(18):
    nPD_d4_F.append(whole_nPD_F[i].sample(n=NP_PD_d4_M[i] * 2, replace=True))

In [474]:
for i in range(18):
    print(len(nPD_d4_M[i]))
for i in range(18):
    print(len(nPD_d4_F[i]))

0
0
0
0
0
0
0
0
2
0
6
8
2
12
34
16
6
18
0
0
0
0
0
0
0
0
8
2
0
16
0
14
8
6
10
12

In [475]:
# 为女性组数据添加一个标记列，并垂直合并
for i in range(18):
    nPD_d4_age_F = pd.concat([nPD_d4_F[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d4_age_F))
for i in range(18):

    nPD_d4_age_M = pd.concat([nPD_d4_M[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d4_age_M))
nPD_d4_age = pd.concat([nPD_d4_age_F, nPD_d4_age_M], axis=0, ignore_index=True)

print("all:", len(nPD_d4_age))
# print(nPD_d4_age)

76
104
all: 180

In [476]:
print(len(df_d4_DP_group))

90

# 結果

In [477]:
#odds ratio語法
import pandas as pd
import numpy as np
from scipy.stats import fisher_exact
import statsmodels.api as sm
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime
#合併PD與nPD
df_d4_PDandnPD=pd.concat([df_d4_DP_group,nPD_d4_age])
# 創建交叉表
contingency_table = pd.crosstab(df_d4_PDandnPD['PD'], df_d4_PDandnPD['disease6'])

# 計算odds ratio和p-value
odds_ratio, p_value = fisher_exact(contingency_table)

# 計算odds ratio的信賴區間
table = Table2x2(contingency_table.values)
confidence_interval = table.oddsratio_confint()

print(f'Odds Ratio: {odds_ratio}')
print(f'p-value: {p_value}')
print(f'Confidence Interval: {confidence_interval}')
if p_value < 0.05:
    print("\nfail")
else:
    print("\npass")
    
    nowtime = datetime.now().strftime("%Y%m%d_%H%M")
    pass_csvFileName=f'd4_pass_PDandnPD{nowtime}.csv'
    print(pass_csvFileName)    
    df_d4_PDandnPD.to_csv(f'data/{pass_csvFileName}', index=False)

Odds Ratio: 0.6296296296296297
p-value: 0.34240171160203303
Confidence Interval: (0.2826215320395765, 1.402700875784759)

pass
d4_pass_PDandnPD20241101_1825.csv

In [478]:
import pandas as pd
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime

# 假设 df_d4_PDandnPD 是您的合并数据集
df_d4_PDandnPD = pd.concat([df_d4_DP_group, nPD_d4_age])

# 存储结果的列表
results = []
sumP=0
# 遍历 disease1 到 disease7
for n in range(1, 8):
    disease_col = f'disease{n}'
    
    # 筛选出 diseaseN == 1 的样本
    # disease_data = df_d1_PDandnPD[df_d1_PDandnPD[disease_col] == 1]
    
    # 创建 PD 与当前疾病的交叉表
    contingency_table = pd.crosstab(df_d4_PDandnPD['PD'], df_d4_PDandnPD[disease_col])
    
    # 检查表格是否为 2x2
    if contingency_table.shape == (2, 2):
        # 计算 Odds Ratio 和 p 值
        odds_ratio, p_value = fisher_exact(contingency_table)
        
        # 计算置信区间
        table = Table2x2(contingency_table.values)
        confidence_interval = table.oddsratio_confint()
        
        # 记录结果
        results.append({
            'Disease': disease_col,
            'Odds Ratio': odds_ratio,
            'p-value': p_value,
            'Confidence Interval': confidence_interval
        })
        
        # 输出结果
        print(f'\n{disease_col}:')
        print(f'Odds Ratio: {odds_ratio}')
        print(f'p-value: {p_value}')
        print(f'Confidence Interval: {confidence_interval}')
        
        # 检查 p 值
        if p_value < 0.05:
             print("Y_顯著")
        else:
            print("N_不顯著")
            sumP+=1
    else:
        print(f'\n{disease_col}:')
        print("X_交叉表不是 2x2，无法计算统计量。请检查数据。")
print(sumP)

disease1:
Odds Ratio: 1.1685393258426966
p-value: 0.6060061556288059
Confidence Interval: (0.7039352506235476, 1.9397865852453828)
N_不顯著

disease2:
Odds Ratio: 0.37209302325581395
p-value: 0.07411219384185057
Confidence Interval: (0.12323624598121816, 1.123478055123107)
N_不顯著

disease3:
Odds Ratio: 1.6428571428571428
p-value: 0.06786747888725111
Confidence Interval: (0.9860295708173504, 2.737219726178666)
N_不顯著

disease4:
X_交叉表不是 2x2，无法计算统计量。请检查数据。

disease5:
Odds Ratio: 0.4878048780487805
p-value: 0.09614314285029979
Confidence Interval: (0.21376503569966354, 1.1131549098726614)
N_不顯著

disease6:
Odds Ratio: 0.6296296296296297
p-value: 0.34240171160203303
Confidence Interval: (0.2826215320395765, 1.402700875784759)
N_不顯著

disease7:
Odds Ratio: 1.3846153846153846
p-value: 0.41739856753341137
Confidence Interval: (0.6354909071235556, 3.016816986400821)
N_不顯著
6

In [479]:
if sumP ==6:
    df_d4_PDandnPD.to_csv('data/out/pass6_d4.csv', index=False)
    print("\npass6_d4.csv")

pass6_d4.csv

In [480]:
# !ls ~/df_outData

In [481]:
# !ls ./data

In [482]:
# !cp ./data/{pass_csvFileName} ~/df_outData/

In [483]:
# !ls ~/df_outData

In [484]:
# df_d4_PDandnPD