In [76]:
import sys

from numpy.testing.print_coercion_tables import print_coercion_table

# from time import process_time_ns

# from scipy.misc.tests.test_doccer import param_doc2

print("start")
print(sys.version)
import os
import pandas as pd

os.getcwd()

start
3.8.20 (default, Oct  3 2024, 10:22:23)
[Clang 14.0.6 ]

'/Users/lai_zx/PycharmProjects/HH_DB'

In [77]:
#轉檔保存
# df_nPD=pd.read_csv('data/nPD_group.csv',encoding='cp950')
# df_PD=pd.read_csv('data/PD_group.csv',encoding='cp950')
# df_nPD.head(10)
# df_nPD.to_csv('data/nPD_group_utf8.csv.csv',index=False,encoding='utf-8')
# df_PD.to_csv('data/PD_group_utf8.csv',index=False,encoding='utf-8')

In [78]:

#釋放記憶體
import gc

# del df_PD
# del df_nPD
# gc.collect()

### 資料載入 PD_group nPD_group

In [79]:
df_PD_group = pd.read_csv('data/PD_group_utf8.csv')
df_nPD_group = pd.read_csv('data/nPD_group_utf8.csv')

In [80]:
print(df_nPD_group.info)
print(df_PD_group.info)

<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     $]$>^"^>%]{$  $]$>^"^>%]{$             1      12H       0     1
1     /%/;#[@""^]~  /%/;#[@""^]~             4      12H       0     1
2     <]<*]#:*-:;=  <]<*]#:*-:;=             2      12H       0     1
3     }%}_~#<^!-%!  }%}_~#<^!-%!             1       62       0     1
4     @]@[$-!~)@}*  @]@[$-!~)@}*             3      12H       0     1
...            ...           ...           ...      ...     ...   ...
5445  ;];;%>:&%"-@  ;];;%>:&%"-@             4      31Q       0     2
5446  ~]~/&]!-@"(%  #%#<}-:^-{%{             5       21       0     2
5447  @%@#&$]~]&!=  @%@#&$]~]&!=             2       62       0     2
5448  +%+!<<>^/&~+  +%+!<<>^/&~+             3      31Q       0     2
5449  _%_*"$[%<-_-  _%_*"$[%<-_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      1        1984        2  ...         0         0        0
1           0      1        1981        2  ...         0         0        0
2           0      1        1982        2  ...         0         0        0
3           0      1        1981        2  ...         0         0        0
4           0      1        1982        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
5445        0      2        1929        2  ...         0         0        0
5446        0      2        1926        2  ...         0         0        0
5447        0      2        1924        2  ...         0         0        0
5448        0      2        1925        2  ...         0         0        0
5449        0      2        1927        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            0         0        0         0   台北市   30  30-34
1            0         0        0         0   雲林縣   33  30-34
2            0         0        0         0   新竹縣   32  30-34
3            0         0        0         0   新北市   33  30-34
4            0         0        0         0   彰化縣   32  30-34
...        ...       ...      ...       ...   ...  ...         ...
5445         0         0        1         0   嘉義縣   85  85~
5446         0         0        0         0   屏東縣   88  85~
5447         0         0        0         0   新竹縣   90  85~
5448         0         0        1         0   台中市   89  85~
5449         0         0        0         0   嘉義市   87  85~

[5450 rows x 30 columns]>
<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     )]))<@%/-@/\  )]))<@%/-@/\             1      31Q       0     2
1     )])->[[_;"}+  )])->[[_;"}+             3       62       0     2
2     )])/;&*^})\_  )])/;&*^})\_             3      31Q       0     2
3     )%):~-[#[%/=  )%):~-[#[%/=             4      31Q       0     2
4     )%)_#)]_>)-{  )%)_#)]_>)-{             3      31Q       0     1
...            ...           ...           ...      ...     ...   ...
2720  (%({_[-}]%%/  (%({_[-}]%%/             5       62       0     2
2721  (%(/:#=${(<"  (%(/:#=${(<"             1       62       0     1
2722  (%(/&<[!>=^!  (%(/&<[!>=^!             1       62       0     2
2723  (%([]$!-$\]]  (%([]$!-$\]]             4      31Q       0     2
2724  (%(&<]")^&+<  (%(&<]")^&+<             4       62       0     1

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      2        1926        2  ...         1         0        0
1           0      2        1928        2  ...         1         0        0
2           0      2        1923        2  ...         0         0        0
3           0      2        1922        2  ...         0         0        0
4           0      1        1941        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
2720        0      2        1915        2  ...         0         0        1
2721        0      1        1974        2  ...         0         0        0
2722        0      2        1941        A  ...         0         0        1
2723        0      2        1933        2  ...         1         0        0
2724        0      1        1953        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            1         0        0         0   宜蘭縣   88  85~
1            0         1        0         0   南投縣   86  85~
2            0         1        0         0   彰化縣   91  85~
3            0         0        0         0   雲林縣   92  85~
4            0         0        0         0   南投縣   73  70-74
...        ...       ...      ...       ...   ...  ...         ...
2720         0         0        0         0   屏東縣   99  85~
2721         0         0        0         0   台北市   40  40-44
2722         1         0        1         0   新北市   73  70-74
2723         0         0        0         0   嘉義縣   81  80-84
2724         0         0        0         0   台南市   61  60-64

[2725 rows x 30 columns]>

### disease2

In [81]:
print(len(df_PD_group.query('disease2==1')))
print(len(df_nPD_group.query('disease2==1')))

216
271

## 比例

In [82]:
# 從PD_group 抽 有 disease2 
df_d2_DP_group = (df_PD_group.query('disease2==1')).sample(30)
df_d2_nDP_group = (df_nPD_group.query('disease2==1')).sample(271)
print(len(df_d2_DP_group.query(' disease2==1')))
print(len(df_d2_nDP_group.query(' disease2==1')))

30
271

In [83]:
#df_d2_nDP_group.query('Id2_S==2 and age_group=="85~"')

In [84]:
df_d2_DP_group['ID1_S'] = df_d2_DP_group['ID1_S'].astype(str)
df_d2_DP_group['age_group'] = df_d2_DP_group['age_group'].astype(str)
print(df_d2_DP_group.dtypes)

ID               object
ID1              object
ID1_DIVISION      int64
ID1_UNIT         object
ID_ROC            int64
ID_S              int64
ID1_ROC           int64
ID1_S            object
ID_BIRTH_Y        int64
ID1_TYPE         object
ID_RELATION     float64
ID1_AMT         float64
ID1_IDENT        object
PREM_YM           int64
ID_STATUS         int64
ID1_MARK         object
FAM_CONT_Y      float64
FAM_CONT_N      float64
ID1_CITY          int64
PD                int64
disease1          int64
disease2          int64
disease3          int64
disease4          int64
disease5          int64
disease6          int64
disease7          int64
city             object
Age               int64
age_group        object
dtype: object

In [85]:
import pandas as pd

# 假设您的 DataFrame 是 df，并且其中有一列名为 'age_groups'
# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
df_d2_DP_group['age_group'] = df_d2_DP_group['age_group'].str.strip()
# 使用 value_counts() 方法统计每个年龄组的数量
#age_group_counts =df_d2_DP_group ['age_group'].value_counts()
age_group_counts = df_d2_DP_group['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_M = df_d2_DP_group.query('ID1_S==1')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d2_DP_group.query('ID1_S==2')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
print(age_group_counts)

# 显示结果
# print(age_group_counts)
# print(age_group_counts2)
# print(age_group_counts.index.tolist())
# print(all_age_groups)

age_group
0-4      0
5-9      0
10-14    0
15-19    0
20-24    0
25-29    0
30-34    0
35-39    0
40-44    0
45-49    2
50-54    0
55-59    6
60-64    8
65-69    0
70-74    4
75-79    5
80-84    2
85~      3
Name: count, dtype: int64

In [86]:
import pandas as pd

# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']

# 数据清理
# 去除 'age_group' 列中值的前后空格
df_d2_DP_group['age_group'] = df_d2_DP_group['age_group'].str.strip()

# 确保 'ID1_S' 和 'ID' 列的数据类型正确
df_d2_DP_group['ID1_S'] = df_d2_DP_group['ID1_S'].astype(int)
df_d2_DP_group['ID'] = df_d2_DP_group['ID'].astype(str)

# 将 'age_group' 列转换为分类数据类型，确保顺序正确
df_d2_DP_group['age_group'] = pd.Categorical(df_d2_DP_group['age_group'], categories=all_age_groups, ordered=True)

# 按性别过滤数据
# 男性数据（ID1_S == 1）
df_d2_DP_M = df_d2_DP_group[df_d2_DP_group['ID1_S'] == 1]
df_d2_DP_F = df_d2_DP_group[df_d2_DP_group['ID1_S'] == 2]

# 按年龄组统计男性的 ID 数量
age_group_counts_M = df_d2_DP_M.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d2_DP_F.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
# 显示结果
print("男性各年龄组的 ID 数量：")
print(age_group_counts_M)
print(age_group_counts_F)
NP_PD_d2_M = age_group_counts_M.to_numpy()
NP_PD_d2_F = age_group_counts_F.to_numpy()
print(NP_PD_d2_M)

男性各年龄组的 ID 数量：
age_group
0-4      0
5-9      0
10-14    0
15-19    0
20-24    0
25-29    0
30-34    0
35-39    0
40-44    0
45-49    0
50-54    0
55-59    5
60-64    6
65-69    0
70-74    2
75-79    4
80-84    0
85~      3
Name: ID, dtype: int64
age_group
0-4      0
5-9      0
10-14    0
15-19    0
20-24    0
25-29    0
30-34    0
35-39    0
40-44    0
45-49    2
50-54    0
55-59    1
60-64    2
65-69    0
70-74    2
75-79    1
80-84    2
85~      0
Name: ID, dtype: int64
[0 0 0 0 0 0 0 0 0 0 0 5 6 0 2 4 0 3]

In [87]:
df_d2_DP_group.dtypes

ID                object
ID1               object
ID1_DIVISION       int64
ID1_UNIT          object
ID_ROC             int64
ID_S               int64
ID1_ROC            int64
ID1_S              int64
ID_BIRTH_Y         int64
ID1_TYPE          object
ID_RELATION      float64
ID1_AMT          float64
ID1_IDENT         object
PREM_YM            int64
ID_STATUS          int64
ID1_MARK          object
FAM_CONT_Y       float64
FAM_CONT_N       float64
ID1_CITY           int64
PD                 int64
disease1           int64
disease2           int64
disease3           int64
disease4           int64
disease5           int64
disease6           int64
disease7           int64
city              object
Age                int64
age_group       category
dtype: object

In [88]:
import pandas as pd

who2000 = pd.read_csv('data/who2000.csv')
# 定义所有可能的 `ID1_S` 和 `age_group` 组合
all_ID1_S = ['1', '2']
#all_age_groups = who2000['AGE']
# 确保 ID1_S 是整数类型
df_d2_nDP_group['ID1_S'] = df_d2_nDP_group['ID1_S'].astype(int)

# 确保 age_group 列没有多余空格
df_d2_nDP_group['age_group'] = df_d2_nDP_group['age_group'].str.strip()

all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
# 去除 'age_group' 列中值的前后空格
df_d2_DP_group['age_group'] = df_d2_DP_group['age_group'].str.strip()

# 创建 MultiIndex，包含所有可能的组合
index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])

# 男性组
# 男性组
whole_nPD_M = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d2_nDP_group[(df_d2_nDP_group['ID1_S'] == 1) & (df_d2_nDP_group['age_group'] == all_age_groups[i])]
    # 打印每个分组数据以调试
    #print(f"男性组第{i}组数据:\n", data)
    whole_nPD_M[i] = data if not data.empty else pd.DataFrame(columns=df_d2_nDP_group.columns).reindex(
        index=[(1, all_age_groups[i])])

# 女性组
whole_nPD_F = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d2_nDP_group.query(f'ID1_S == 2 and age_group == "{all_age_groups[i]}"')
    # 打印每个分组数据以调试
    print(f"女性组第{i}组数据:\n", data)
    whole_nPD_F[i] = data if not data.empty else pd.DataFrame(columns=df_d2_nDP_group.columns).reindex(
        index=[(2, all_age_groups[i])])

女性组第0组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第1组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第2组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第3组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第4组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第5组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第6组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第7组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2897  <%<[$/[))"&^  <%<[$/[))"&^             5       62       0     2
2837  ~%~=}#]$;<)>  ~%~=}#]$;<)>             3      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2897        0      2        1979        2  ...         0         1        0
2837        0      2        1978        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2897         0         0        0         0   高雄市   35      35-39
2837         0         0        0         0   彰化縣   36      35-39

[2 rows x 30 columns]
女性组第8组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2975  /%/~&/%%\<)&  /%/~&/%%\<)&             1      12H       0     2
2904  $]$%)&""&!#[  $]$%)&""&!#[             2      12H       0     2
2966  <%<:~@[#;%&:  <%<:~@[#;%&:             2       62       0     2
2923  @]@))<&>;/[\  @]@))<&>;/[\             1      12H       0     2
2951  {%{>{<;_#]+%  {%{>{<;_#]+%             1      12H       0     2
2910  (](}=#\;~>:[  (](}=#\;~>:[             1      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2975        0      2        1974        2  ...         0         1        0
2904        0      2        1973        2  ...         0         1        0
2966        0      2        1970        2  ...         0         1        0
2923        0      2        1973        2  ...         0         1        0
2951        0      2        1971        2  ...         0         1        0
2910        0      2        1974        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2975         0         0        0         0   新北市   40      40-44
2904         0         0        0         0   桃園市   41      40-44
2966         1         0        0         0   桃園市   44      40-44
2923         0         0        0         0   台北市   41      40-44
2951         0         0        0         1   台北市   43      40-44
2910         0         0        0         0   台北市   40      40-44

[6 rows x 30 columns]
女性组第9组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3020  "]"^))}[^@+$  "]"^))}[^@+$             4      12H       0     2
3003  }%}{$#[;><$&  }%}{$#[;><$&             2       32       0     2
3007  _%_"\@@+=}+(  _%_"\@@+=}+(             3      12H       0     2
2981  $]$!%$!\!~:&  $]$!%$!\!~:&             2      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3020        0      2        1966        2  ...         0         1        0
3003        0      2        1967        2  ...         0         1        0
3007        0      2        1969        2  ...         0         1        0
2981        0      2        1966        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3020         0         0        0         0   台南市   48      45-49
3003         0         0        0         0   苗栗縣   47      45-49
3007         0         0        0         0   台中市   45      45-49
2981         0         0        0         0   桃園市   48      45-49

[4 rows x 30 columns]
女性组第10组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3095  ]%]</"@!\=[{  ]%]</"@!\=[{             5       21       0     2
3039  [][}("{}%:\<  [][}("{}%:\<             1       62       0     2
3130  $%$_(-]-}#:_  $%$_(-]-}#:_             1      11A       0     2
3038  +]+!}]%(>-:@  +]+!}]%(>-:@             5      12H       0     2
3036  :]:~"/[[/]&&  :]:~"/[[/]&&             4      12H       0     2
3077  >]>"\)>^_)%{  >]>"\)>^_)%{             2      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3095        0      2        1961        2  ...         0         1        0
3039        0      2        1964        2  ...         0         1        0
3130        0      2        1961        2  ...         0         1        0
3038        0      2        1964        2  ...         0         1        0
3036        0      2        1963        2  ...         0         1        0
3077        0      2        1962        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3095         0         0        0         0   高雄市   53      50-54
3039         0         0        0         0   新北市   50      50-54
3130         0         0        0         0   台北市   53      50-54
3038         0         0        0         1   高雄市   50      50-54
3036         0         0        0         0   雲林縣   51      50-54
3077         0         0        0         0   新竹縣   52      50-54

[6 rows x 30 columns]
女性组第11组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3219  }]}+&)$<*@$_  }]}+&)$<*@$_             2      12H       0     2
3204  &]&:#[[%*!(-  &]&:#[[%*!(-             5      31Q       0     2
3250  >]>/_";"@/{!  >]>/_";"@/{!             4      12H       0     2
3163  /%/$({\_%~#}  /%/$({\_%~#}             3       21       0     2
3177  {]{][<")+"@"  {]{][<")+"@"             6       62       0     2
3176  -]-{=)%+=-(^  -]-{=)%+=-(^             4       21       0     2
3217  ;];#_@-\#!;&  ;];#_@-\#!;&             4       21       0     2
3241  #]#{{]+"+%:_  #]#{{]+"+%:_             1      12H       0     2
3216  ]]]++$[^*]-#  ]]]++$[^*]-#             2       21       0     2
3167  ;];>)$#_*/-@  ;];>)$#_*/-@             3       52       0     2
3162  #]#_#@;@$]\:  #]#_#@;@$]\:             4       21       0     2
3243  [][^+>{%-/<+  [][^+>{%-/<+             5       32       0     2
3267  !]!!*<@-"=;!  !]!!*<@-"=;!             1      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3219        0      2        1959        1  ...         1         1        0
3204        0      2        1957        2  ...         0         1        0
3250        0      2        1958        2  ...         0         1        0
3163        0      2        1955        2  ...         0         1        1
3177        0      2        1958        2  ...         0         1        0
3176        0      2        1958        2  ...         0         1        0
3217        0      2        1957        2  ...         0         1        0
3241        0      2        1959        2  ...         1         1        0
3216        0      2        1957        2  ...         0         1        1
3167        0      2        1958        2  ...         0         1        0
3162        0      2        1956        2  ...         1         1        1
3243        0      2        1958        2  ...         0         1        0
3267        0      2        1957        2  ...         1         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3219         0         0        0         0   桃園市   55      55-59
3204         0         0        0         0   高雄市   57      55-59
3250         0         0        0         0   雲林縣   56      55-59
3163         0         0        0         0   台中市   59      55-59
3177         0         0        0         0   台東縣   56      55-59
3176         0         0        0         0   雲林縣   56      55-59
3217         0         0        0         0   台南市   57      55-59
3241         0         0        0         0   台北市   55      55-59
3216         0         0        0         0   桃園市   57      55-59
3167         0         0        0         0   台中市   56      55-59
3162         0         0        0         0   雲林縣   58      55-59
3243         0         0        0         0   高雄市   56      55-59
3267         0         0        0         0   新北市   57      55-59

[13 rows x 30 columns]
女性组第12组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3274  ;%;;+/~^[\/-  ;%;;+/~^[\/-             1       62       0     2
3275  ^]^@\#&$@+/!  ^]^@\#&$@+/!             3      31Q       0     2
3293  "]"+##$({++:  "]"+##$({++:             4      31Q       0     2
3301  {]{}@>!)%("{  {]{}@>!)%("{             1      12H       0     2
3295  (%(&%":!]/]=  (%(&%":!]/]=             3       21       0     2
3402  +%+=#-!:-<_;  +%+=#-!:-<_;             1       21       0     2
3398  ;%;;+/~^[\/-  ;%;;+/~^[\/-             1       62       0     2
3333  =%=#;-&=(^="  =%=#;-&=(^="             4       21       0     2
3434  $%$-~/&"["{/  $%$-~/&"["{/             5       21       0     2
3284  =]=\{@~-*&{<  =]=\{@~-*&{<             2       21       0     2
3455  ;];<"#(_#[){  ;];<"#(_#[){             3      31Q       0     2
3396  +%+)&@-[)={)  +%+)&@-[)={)             5       21       0     2
3440  !%!>=&({)(/&  !%!>=&({)(/&             4       21       0     2
3365  _%_!"@[+$^<{  _%_!"@[+$^<{             1      12H       0     2
3399  %]%[%@--:*&~  %]%[%@--:*&~             1      12M       0     2
3433  *%*_;]{*)([-  *%*_;]{*)([-             1       21       0     2
3307  "]"+##$({++:  "]"+##$({++:             4      31Q       0     2
3351  [%[-^-[(%}[{  [%[-^-[(%}[{             5      31Q       0     2
3415  +%+=#-!:-<_;  +%+=#-!:-<_;             1       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3274        0      2        1951        A  ...         0         1        0
3275        0      2        1951        2  ...         0         1        0
3293        0      2        1950        2  ...         0         1        0
3301        0      2        1954        2  ...         0         1        0
3295        0      2        1953        2  ...         0         1        0
3402        0      2        1953        2  ...         0         1        0
3398        0      2        1951        A  ...         0         1        0
3333        0      2        1953        2  ...         0         1        0
3434        0      2        1950        2  ...         0         1        0
3284        0      2        1954        2  ...         1         1        0
3455        0      2        1950        2  ...         1         1        0
3396        0      2        1953        2  ...         0         1        0
3440        0      2        1954        2  ...         0         1        0
3365        0      2        1954        2  ...         0         1        0
3399        0      2        1954        2  ...         1         1        0
3433        0      2        1953        2  ...         0         1        0
3307        0      2        1950        2  ...         0         1        0
3351        0      2        1953        2  ...         0         1        0
3415        0      2        1953        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3274         0         0        0         0   台北市   63      60-64
3275         0         0        1         0   彰化縣   63      60-64
3293         0         0        0         1   嘉義縣   64      60-64
3301         0         0        0         0   台北市   60      60-64
3295         0         0        0         0   南投縣   61      60-64
3402         0         0        0         0   台北市   61      60-64
3398         0         0        0         0   台北市   63      60-64
3333         0         0        0         0   台南市   61      60-64
3434         0         0        0         0   高雄市   64      60-64
3284         1         0        1         0   桃園市   60      60-64
3455         1         0        0         0   彰化縣   64      60-64
3396         1         1        0         0   高雄市   61      60-64
3440         0         1        0         0   台南市   60      60-64
3365         0         0        0         0   新北市   60      60-64
3399         1         0        0         0   新北市   60      60-64
3433         0         0        0         0   新北市   61      60-64
3307         0         0        0         1   嘉義縣   64      60-64
3351         0         0        0         0   屏東縣   61      60-64
3415         0         0        0         0   台北市   61      60-64

[19 rows x 30 columns]
女性组第13组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3597  @%@_-<[}:^=_  @%@_-<[}:^=_             3       62       0     2
3594  [][;+/${;=@[  [][;+/${;=@[             1       21       0     2
3478  +]+>-"{>;{_+  +]+>-"{>;{_+             1       62       0     2
3511  }%}_{[^{:=^}  }%}_{[^{:=^}             1       21       0     2
3585  _%_(~>>=~"!}  _%_(~>>=~"!}             5       21       0     2
3580  {]{"+)(!!:[{  {]{"+)(!!:[{             1      31Q       0     2
3587  /]///$)_*:{-  /]///$)_*:{-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3597        0      2        1945        A  ...         1         1        0
3594        0      2        1945        2  ...         0         1        1
3478        0      2        1947        2  ...         0         1        0
3511        0      2        1948        2  ...         0         1        0
3585        0      2        1948        2  ...         1         1        0
3580        0      2        1948        2  ...         0         1        0
3587        0      2        1945        2  ...         1         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3597         1         0        0         0   南投縣   69      65-69
3594         1         0        0         0   台北市   69      65-69
3478         0         0        0         0   台北市   67      65-69
3511         0         0        0         1   台北市   66      65-69
3585         0         0        0         0   高雄市   66      65-69
3580         0         1        1         0   宜蘭縣   66      65-69
3587         0         0        0         0   雲林縣   69      65-69

[7 rows x 30 columns]
女性组第14组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4061  %]%@$-@;)&->  %]%@$-@;)&->             3      12H       0     2
3758  <%<]/"~:{#+"  <%<]/"~:{#+"             1      12H       0     2
3613  -%-!%"#[)[%\  -%-!%"#[)[%\             4      31Q       0     2
3814  -]-&{/@-]:=_  -]-&{/@-]:=_             6       62       0     2
3681  @]@=_")}+<{$  @]@=_")}+<{$             1       21       0     2
4167  ~]~;@{&=*\#~  ~]~;@{&=*\#~             1       62       0     2
3698  *%*_!)~}_}/+  *%*_!)~}_}/+             3      31Q       0     2
3813  {]{)/&#&=][)  {]{)/&#&=][)             5      31Q       0     2
3852  @]@=_")}+<{$  @]@=_")}+<{$             1       21       0     2
3776  >%>(//][[);^  >%>(//][[);^             4      31Q       0     2
3939  ~%~]*>>:$[<]  ~%~]*>>:$[<]             6       62       0     2
4047  )])#(@>){;~\  )])#(@>){;~\             2      31Q       0     2
4031  )%){=<{}(#~{  )%){=<{}(#~{             5       62       0     2
3728  ~%~]*>>:$[<]  ~%~]*>>:$[<]             6       62       0     2
4007  ~%~"${$]^<(@  ~%~"${$]^<(@             3       62       0     2
3907  <%</$<[#}&-&  <%</$<[#}&-&             1       62       0     2
4139  }]}@"<__$&/-  }]}@"<__$&/-             1       62       0     2
3900  ~%~]*>>:$[<]  ~%~]*>>:$[<]             6       62       0     2
3908  >]>&=#$--){@  >]>&=#$--){@             4      31Q       0     2
4067  <%</$<[#}&-&  <%</$<[#}&-&             1       62       0     2
4046  /%/]/</&):}-  /%/]/</&):}-             1       62       0     2
3831  ;%;;$&%]-^*\  ;%;;$&%]-^*\             5       62       0     2
3976  >]>&=#$--){@  >]>&=#$--){@             4      31Q       0     2
3901  >]>)+--="~"_  >]>)+--="~"_             3      31Q       0     2
3968  +%+-<{{^@[[(  +%+-<{{^@[[(             1       62       0     2
4068  ;%;;$&%]-^*\  ;%;;$&%]-^*\             5       62       0     2
4140  &%&{!{$]_/&<  &%&{!{$]_/&<             5       62       0     2
3810  \]\"}&>//]=:  \]\"}&>//]=:             2      31Q       0     2
3861  @]@_($-][=[;  @]@_($-][=[;             1       62       0     2
3953  *%*[&>[:@%_!  *%*[&>[:@%_!             1      13L       0     2
3669  )%)}}<!/$/^-  )%)}}<!/$/^-             1       62       0     2
3674  ~]~$~-$!/[@"  ~]~$~-$!/[@"             1      12H       0     2
4162  ~%~[&[-\_~\$  ~%~[&[-\_~\$             3      31Q       0     2
3989  ;];]}/#};{<:  ;];]}/#};{<:             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
4061        0      2        1942        1  ...         0         1        0
3758        0      2        1943        2  ...         0         1        0
3613        0      2        1940        2  ...         1         1        0
3814        0      2        1942        2  ...         1         1        1
3681        0      2        1941        2  ...         0         1        0
4167        0      2        1944        2  ...         0         1        0
3698        0      2        1943        2  ...         0         1        0
3813        0      2        1942        2  ...         1         1        0
3852        0      2        1941        2  ...         0         1        0
3776        0      2        1943        2  ...         1         1        0
3939        0      2        1943        A  ...         1         1        0
4047        0      2        1942        2  ...         1         1        1
4031        0      2        1940        A  ...         1         1        0
3728        0      2        1943        A  ...         1         1        0
4007        0      2        1941        2  ...         0         1        1

In [89]:
nPD_d2_M = []
nPD_d2_F = []

# 使用 whole_nPD_M 字典中的分组进行采样
for i in range(18):
    nPD_d2_M.append(whole_nPD_M[i].sample(n=NP_PD_d2_F[i] * 2, replace=True))

# 使用 whole_nPD_F 字典中的分组进行采样
for i in range(18):
    nPD_d2_F.append(whole_nPD_F[i].sample(n=NP_PD_d2_M[i] * 2, replace=True))

In [90]:
for i in range(18):
    print(len(nPD_d2_M[i]))
for i in range(18):
    print(len(nPD_d2_F[i]))

0
0
0
0
0
0
0
0
0
4
0
2
4
0
4
2
4
0
0
0
0
0
0
0
0
0
0
0
0
10
12
0
4
8
0
6

In [91]:
# 为女性组数据添加一个标记列，并垂直合并
for i in range(18):
    nPD_d2_age_F = pd.concat([nPD_d2_F[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d2_age_F))
for i in range(18):

    nPD_d2_age_M = pd.concat([nPD_d2_M[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d2_age_M))
nPD_d2_age = pd.concat([nPD_d2_age_F, nPD_d2_age_M], axis=0, ignore_index=True)

print("all:", len(nPD_d2_age))
# print(nPD_d2_age)

40
20
all: 60

In [92]:
print(len(df_d2_DP_group))

30

# 結果

In [93]:
import pandas as pd
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime

# 假设 df_d1_PDandnPD 是您的合并数据集
df_d2_PDandnPD = pd.concat([df_d2_DP_group, nPD_d2_age])

# 存储结果的列表
results = []
sumP=0
# 遍历 disease1 到 disease7
for n in range(1, 8):
    disease_col = f'disease{n}'
    
    # 筛选出 diseaseN == 1 的样本
    # disease_data = df_d1_PDandnPD[df_d1_PDandnPD[disease_col] == 1]
    
    # 创建 PD 与当前疾病的交叉表
    contingency_table = pd.crosstab(df_d2_PDandnPD['PD'], df_d2_PDandnPD[disease_col])
    
    # 检查表格是否为 2x2
    if contingency_table.shape == (2, 2):
        # 计算 Odds Ratio 和 p 值
        odds_ratio, p_value = fisher_exact(contingency_table)
        
        # 计算置信区间
        table = Table2x2(contingency_table.values)
        confidence_interval = table.oddsratio_confint()
        
        # 记录结果
        results.append({
            'Disease': disease_col,
            'Odds Ratio': odds_ratio,
            'p-value': p_value,
            'Confidence Interval': confidence_interval
        })
        
        # 输出结果
        print(f'\n{disease_col}:')
        print(f'Odds Ratio: {odds_ratio}')
        print(f'p-value: {p_value}')
        print(f'Confidence Interval: {confidence_interval}')
        
        # 检查 p 值
        if p_value < 0.05:
             print("Y_顯著")
        else:
            print("N_不顯著")
            sumP+=1
    else:
        print(f'\n{disease_col}:')
        print("X_交叉表不是 2x2，无法计算统计量。请检查数据。")
print(sumP)

disease1:
Odds Ratio: 1.625
p-value: 0.3600622240744396
Confidence Interval: (0.6658917317697932, 3.9655470612043797)
N_不顯著

disease2:
X_交叉表不是 2x2，无法计算统计量。请检查数据。

disease3:
Odds Ratio: 1.5
p-value: 0.45838279360308554
Confidence Interval: (0.5755138388863003, 3.9095497761688334)
N_不顯著

disease4:
Odds Ratio: 0.36507936507936506
p-value: 0.16043973706051473
Confidence Interval: (0.09612987427296564, 1.386488267198694)
N_不顯著

disease5:
Odds Ratio: 0.0
p-value: 0.17300403782673718
Confidence Interval: (0.008095669526439168, 2.7792636453993804)
N_不顯著

disease6:
Odds Ratio: 0.35714285714285715
p-value: 0.3239247586418218
Confidence Interval: (0.07304179130856557, 1.7462745384943126)
N_不顯著

disease7:
Odds Ratio: 3.347826086956522
p-value: 0.09565303608833994
Confidence Interval: (0.9624640274098524, 11.645047699776391)
N_不顯著
6

In [94]:
if sumP == 6:
    df_d2_PDandnPD.to_csv('data/out/pass6_d2.csv', index=False)
    print("\npass6_d2.csv")

pass6_d2.csv

In [95]:
# #odds ratio語法
# import pandas as pd
# import numpy as np
# from scipy.stats import fisher_exact
# import statsmodels.api as sm
# from statsmodels.stats.contingency_tables import Table2x2
# from datetime import datetime
# #合併PD與nPD
# df_d2_PDandnPD=pd.concat([df_d2_DP_group,nPD_d2_age])
# # 創建交叉表
# contingency_table = pd.crosstab(df_d2_PDandnPD['PD'], df_d2_PDandnPD['disease6'])
# 
# # 計算odds ratio和p-value
# odds_ratio, p_value = fisher_exact(contingency_table)
# 
# # 計算odds ratio的信賴區間
# table = Table2x2(contingency_table.values)
# confidence_interval = table.oddsratio_confint()
# 
# print(f'Odds Ratio: {odds_ratio}')
# print(f'p-value: {p_value}')
# print(f'Confidence Interval: {confidence_interval}')
# if p_value < 0.05:
#     print("\nfail")
# else:
#     print("\npass")
#     
#     nowtime = datetime.now().strftime("%Y%m%d_%H%M")
#     pass_csvFileName=f'd2_pass_PDandnPD{nowtime}.csv'
#     print(pass_csvFileName)    
#     df_d2_PDandnPD.to_csv(f'data/{pass_csvFileName}', index=False)

In [96]:
# !ls ~/df_outData

In [97]:
# !ls ./data

In [98]:
# !cp ./data/{pass_csvFileName} ~/df_outData/

In [99]:
# !ls ~/df_outData

In [100]:
# df_d2_PDandnPD