In [199]:
import sys

from numpy.testing.print_coercion_tables import print_coercion_table

# from time import process_time_ns

# from scipy.misc.tests.test_doccer import param_doc2

print("start")
print(sys.version)
import os
import pandas as pd

os.getcwd()

start
3.8.20 (default, Oct  3 2024, 10:22:23)
[Clang 14.0.6 ]

'/Users/lai_zx/PycharmProjects/HH_DB'

### 資料載入 PD_group nPD_group

In [200]:
df_PD_group = pd.read_csv('data/PD_group_utf8.csv')
df_nPD_group = pd.read_csv('data/nPD_group_utf8.csv')

In [201]:
print(df_nPD_group.info)
print(df_PD_group.info)

<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     $]$>^"^>%]{$  $]$>^"^>%]{$             1      12H       0     1
1     /%/;#[@""^]~  /%/;#[@""^]~             4      12H       0     1
2     <]<*]#:*-:;=  <]<*]#:*-:;=             2      12H       0     1
3     }%}_~#<^!-%!  }%}_~#<^!-%!             1       62       0     1
4     @]@[$-!~)@}*  @]@[$-!~)@}*             3      12H       0     1
...            ...           ...           ...      ...     ...   ...
5445  ;];;%>:&%"-@  ;];;%>:&%"-@             4      31Q       0     2
5446  ~]~/&]!-@"(%  #%#<}-:^-{%{             5       21       0     2
5447  @%@#&$]~]&!=  @%@#&$]~]&!=             2       62       0     2
5448  +%+!<<>^/&~+  +%+!<<>^/&~+             3      31Q       0     2
5449  _%_*"$[%<-_-  _%_*"$[%<-_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      1        1984        2  ...         0         0        0
1           0      1        1981        2  ...         0         0        0
2           0      1        1982        2  ...         0         0        0
3           0      1        1981        2  ...         0         0        0
4           0      1        1982        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
5445        0      2        1929        2  ...         0         0        0
5446        0      2        1926        2  ...         0         0        0
5447        0      2        1924        2  ...         0         0        0
5448        0      2        1925        2  ...         0         0        0
5449        0      2        1927        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            0         0        0         0   台北市   30  30-34
1            0         0        0         0   雲林縣   33  30-34
2            0         0        0         0   新竹縣   32  30-34
3            0         0        0         0   新北市   33  30-34
4            0         0        0         0   彰化縣   32  30-34
...        ...       ...      ...       ...   ...  ...         ...
5445         0         0        1         0   嘉義縣   85  85~
5446         0         0        0         0   屏東縣   88  85~
5447         0         0        0         0   新竹縣   90  85~
5448         0         0        1         0   台中市   89  85~
5449         0         0        0         0   嘉義市   87  85~

[5450 rows x 30 columns]>
<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     )]))<@%/-@/\  )]))<@%/-@/\             1      31Q       0     2
1     )])->[[_;"}+  )])->[[_;"}+             3       62       0     2
2     )])/;&*^})\_  )])/;&*^})\_             3      31Q       0     2
3     )%):~-[#[%/=  )%):~-[#[%/=             4      31Q       0     2
4     )%)_#)]_>)-{  )%)_#)]_>)-{             3      31Q       0     1
...            ...           ...           ...      ...     ...   ...
2720  (%({_[-}]%%/  (%({_[-}]%%/             5       62       0     2
2721  (%(/:#=${(<"  (%(/:#=${(<"             1       62       0     1
2722  (%(/&<[!>=^!  (%(/&<[!>=^!             1       62       0     2
2723  (%([]$!-$\]]  (%([]$!-$\]]             4      31Q       0     2
2724  (%(&<]")^&+<  (%(&<]")^&+<             4       62       0     1

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      2        1926        2  ...         1         0        0
1           0      2        1928        2  ...         1         0        0
2           0      2        1923        2  ...         0         0        0
3           0      2        1922        2  ...         0         0        0
4           0      1        1941        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
2720        0      2        1915        2  ...         0         0        1
2721        0      1        1974        2  ...         0         0        0
2722        0      2        1941        A  ...         0         0        1
2723        0      2        1933        2  ...         1         0        0
2724        0      1        1953        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            1         0        0         0   宜蘭縣   88  85~
1            0         1        0         0   南投縣   86  85~
2            0         1        0         0   彰化縣   91  85~
3            0         0        0         0   雲林縣   92  85~
4            0         0        0         0   南投縣   73  70-74
...        ...       ...      ...       ...   ...  ...         ...
2720         0         0        0         0   屏東縣   99  85~
2721         0         0        0         0   台北市   40  40-44
2722         1         0        1         0   新北市   73  70-74
2723         0         0        0         0   嘉義縣   81  80-84
2724         0         0        0         0   台南市   61  60-64

[2725 rows x 30 columns]>

### disease3

In [202]:
print(len(df_PD_group.query('disease3==1')))
print(len(df_nPD_group.query('disease3==1')))

629
682

## 比例

In [203]:
# 從PD_group 抽 有 disease3 
df_d3_DP_group = (df_PD_group.query('disease3==1')).sample(260)
df_d3_nDP_group = (df_nPD_group.query('disease3==1')).sample(600)
print(len(df_d3_DP_group.query(' disease3==1')))
print(len(df_d3_nDP_group.query(' disease3==1')))

260
600

In [204]:
df_d3_DP_group['ID1_S'] = df_d3_DP_group['ID1_S'].astype(str)
df_d3_DP_group['age_group'] = df_d3_DP_group['age_group'].astype(str)
print(df_d3_DP_group.dtypes)

ID               object
ID1              object
ID1_DIVISION      int64
ID1_UNIT         object
ID_ROC            int64
ID_S              int64
ID1_ROC           int64
ID1_S            object
ID_BIRTH_Y        int64
ID1_TYPE         object
ID_RELATION     float64
ID1_AMT         float64
ID1_IDENT        object
PREM_YM           int64
ID_STATUS         int64
ID1_MARK         object
FAM_CONT_Y      float64
FAM_CONT_N      float64
ID1_CITY          int64
PD                int64
disease1          int64
disease2          int64
disease3          int64
disease4          int64
disease5          int64
disease6          int64
disease7          int64
city             object
Age               int64
age_group        object
dtype: object

In [205]:
import pandas as pd

# 假设您的 DataFrame 是 df，并且其中有一列名为 'age_groups'
# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
df_d3_DP_group['age_group'] = df_d3_DP_group['age_group'].str.strip()
# 使用 value_counts() 方法统计每个年龄组的数量
#age_group_counts =df_d3_DP_group ['age_group'].value_counts()
age_group_counts = df_d3_DP_group['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_M = df_d3_DP_group.query('ID1_S==1')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d3_DP_group.query('ID1_S==2')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
print(age_group_counts)

# 显示结果
# print(age_group_counts)
# print(age_group_counts2)
# print(age_group_counts.index.tolist())
# print(all_age_groups)

age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     5
45-49     3
50-54     0
55-59    10
60-64    13
65-69    29
70-74    77
75-79    44
80-84    41
85~      38
Name: count, dtype: int64

In [206]:
import pandas as pd

# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']

# 数据清理
# 去除 'age_group' 列中值的前后空格
df_d3_DP_group['age_group'] = df_d3_DP_group['age_group'].str.strip()

# 确保 'ID1_S' 和 'ID' 列的数据类型正确
df_d3_DP_group['ID1_S'] = df_d3_DP_group['ID1_S'].astype(int)
df_d3_DP_group['ID'] = df_d3_DP_group['ID'].astype(str)

# 将 'age_group' 列转换为分类数据类型，确保顺序正确
df_d3_DP_group['age_group'] = pd.Categorical(df_d3_DP_group['age_group'], categories=all_age_groups, ordered=True)

# 按性别过滤数据
# 男性数据（ID1_S == 1）
df_d3_DP_M = df_d3_DP_group[df_d3_DP_group['ID1_S'] == 1]
df_d3_DP_F = df_d3_DP_group[df_d3_DP_group['ID1_S'] == 2]

# 按年龄组统计男性的 ID 数量
age_group_counts_M = df_d3_DP_M.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d3_DP_F.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
# 显示结果
print("男性各年龄组的 ID 数量：")
print(age_group_counts_M)
print(age_group_counts_F)
NP_PD_d3_M = age_group_counts_M.to_numpy()
NP_PD_d3_F = age_group_counts_F.to_numpy()
print(NP_PD_d3_M)

男性各年龄组的 ID 数量：
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     5
45-49     3
50-54     0
55-59    10
60-64     4
65-69    18
70-74    21
75-79    18
80-84    14
85~      14
Name: ID, dtype: int64
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     0
45-49     0
50-54     0
55-59     0
60-64     9
65-69    11
70-74    56
75-79    26
80-84    27
85~      24
Name: ID, dtype: int64
[ 0  0  0  0  0  0  0  0  5  3  0 10  4 18 21 18 14 14]

In [207]:
df_d3_DP_group.dtypes

ID                object
ID1               object
ID1_DIVISION       int64
ID1_UNIT          object
ID_ROC             int64
ID_S               int64
ID1_ROC            int64
ID1_S              int64
ID_BIRTH_Y         int64
ID1_TYPE          object
ID_RELATION      float64
ID1_AMT          float64
ID1_IDENT         object
PREM_YM            int64
ID_STATUS          int64
ID1_MARK          object
FAM_CONT_Y       float64
FAM_CONT_N       float64
ID1_CITY           int64
PD                 int64
disease1           int64
disease2           int64
disease3           int64
disease4           int64
disease5           int64
disease6           int64
disease7           int64
city              object
Age                int64
age_group       category
dtype: object

In [208]:
import pandas as pd

who2000 = pd.read_csv('data/who2000.csv')
# 定义所有可能的 `ID1_S` 和 `age_group` 组合
all_ID1_S = ['1', '2']
#all_age_groups = who2000['AGE']
# 确保 ID1_S 是整数类型
df_d3_nDP_group['ID1_S'] = df_d3_nDP_group['ID1_S'].astype(int)

# 确保 age_group 列没有多余空格
df_d3_nDP_group['age_group'] = df_d3_nDP_group['age_group'].str.strip()

all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
# 去除 'age_group' 列中值的前后空格
df_d3_DP_group['age_group'] = df_d3_DP_group['age_group'].str.strip()

# 创建 MultiIndex，包含所有可能的组合
index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])

# 男性组
# 男性组
whole_nPD_M = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d3_nDP_group[(df_d3_nDP_group['ID1_S'] == 1) & (df_d3_nDP_group['age_group'] == all_age_groups[i])]
    # 打印每个分组数据以调试
    #print(f"男性组第{i}组数据:\n", data)
    whole_nPD_M[i] = data if not data.empty else pd.DataFrame(columns=df_d3_nDP_group.columns).reindex(
        index=[(1, all_age_groups[i])])

# 女性组
whole_nPD_F = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d3_nDP_group.query(f'ID1_S == 2 and age_group == "{all_age_groups[i]}"')
    # 打印每个分组数据以调试
    print(f"女性组第{i}组数据:\n", data)
    whole_nPD_F[i] = data if not data.empty else pd.DataFrame(columns=df_d3_nDP_group.columns).reindex(
        index=[(2, all_age_groups[i])])

女性组第0组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第1组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第2组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第3组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第4组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第5组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第6组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第7组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第8组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第9组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2988  )])(&[(:%$#+  )])(&[(:%$#+             4       21       0     2
2986  "]"+]#/(&-/{  "]"+]#/(&-/{             5       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2988        0      2        1968        2  ...         0         0        1
2986        0      2        1965        2  ...         0         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
2988         1         0        0         0   嘉義縣   46      45-49
2986         1         0        0         0   屏東縣   49      45-49

[2 rows x 30 columns]
女性组第10组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3131  \%\<>"^-+#!>  \%\<>"^-+#!>             5       21       0     2
3047  [%[{=&=>/>{_  [%[{=&=>/>{_             2      12H       0     2
3139  :]::%@*>(%;)  :]::%@*>(%;)             5      13I       0     2
3035  !]!%"/_>+(_:  !]!%"/_>+(_:             5       62       0     2
3079  ;%;$^#_>#<^@  ;%;$^#_>#<^@             2      12H       0     2
3028  #]#$\/((^"~&  #]#$\/((^"~&             2      31Q       0     2
3082  %]%\/&@<"*}(  %]%\/&@<"*}(             5       21       0     2
3078  }]}*($/_/$~(  }]}*($/_/$~(             4       21       0     2
3050  -]-_-$)^=/{#  -]-_-$)^=/{#             5       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3131        0      2        1960        2  ...         1         0        1
3047        0      2        1962        2  ...         0         0        1
3139        0      2        1960        2  ...         1         0        1
3035        0      2        1963        2  ...         0         0        1
3079        0      2        1964        1  ...         0         0        1
3028        0      2        1960        2  ...         0         0        1
3082        0      2        1960        2  ...         1         0        1
3078        0      2        1962        2  ...         0         0        1
3050        0      2        1961        2  ...         0         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3131         0         0        0         0   高雄市   54      50-54
3047         1         1        0         0   桃園市   52      50-54
3139         1         0        0         0   高雄市   54      50-54
3035         1         0        1         0   高雄市   51      50-54
3079         0         0        0         0   苗栗縣   50      50-54
3028         1         0        0         0   桃園市   54      50-54
3082         1         0        0         0   屏東縣   54      50-54
3078         1         0        0         0   台南市   52      50-54
3050         0         0        1         0   高雄市   53      50-54

[9 rows x 30 columns]
女性组第11组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3148  #]#/$[<)#(:(  #]#/$[<)#(:(             4      31Q       0     2
3249  %%%;"[:]>>-[  %%%;"[:]>>-[             2       62       0     2
3252  <]<\=>@(+]/"  <]<\=>@(+]/"             1      12H       0     2
3224  $]$!<$)$~)}~  $]$!<$)$~)}~             1      12H       0     2
3263  *]*(_/~;#/\@  *]*(_/~;#/\@             1      12H       0     2
3180  (](<+{]^%!:-  (](<+{]^%!:-             2       21       0     2
3163  /%/$({\_%~#}  /%/$({\_%~#}             3       21       0     2
3216  ]]]++$[^*]-#  ]]]++$[^*]-#             2       21       0     2
3162  #]#_#@;@$]\:  #]#_#@;@$]\:             4       21       0     2
3235  _]_#}){;]<$:  _]_#}){;]<$:             4       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3148        0      2        1956        2  ...         1         0        1
3249        0      2        1958        A  ...         1         0        1
3252        0      2        1957        2  ...         0         0        1
3224        0      2        1958        2  ...         0         0        1
3263        0      2        1958        2  ...         0         0        1
3180        0      2        1956        2  ...         1         0        1
3163        0      2        1955        2  ...         0         1        1
3216        0      2        1957        2  ...         0         1        1
3162        0      2        1956        2  ...         1         1        1
3235        0      2        1957        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3148         1         0        0         0   雲林縣   58      55-59
3249         1         0        0         0   桃園市   56      55-59
3252         1         0        0         0   台北市   57      55-59
3224         1         0        1         0   新北市   56      55-59
3263         0         0        0         0   台北市   56      55-59
3180         0         0        0         0   新竹市   58      55-59
3163         0         0        0         0   台中市   59      55-59
3216         0         0        0         0   桃園市   57      55-59
3162         0         0        0         0   雲林縣   58      55-59
3235         1         0        0         0   台南市   57      55-59

[10 rows x 30 columns]
女性组第12组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3355  ~%~<-@&]@>}/  ~%~<-@&]@>}/             4       21       0     2
3285  {]{$~[%_\&*_  {]{$~[%_\&*_             4       32       0     2
3456  ]]]_~-+"~;</  ]]]_~-+"~;</             3       62       0     2
3349  &%&/)&$_!>:;  &%&/)&$_!>:;             1       21       0     2
3431  =]=!)#~#$+}_  =]=!)#~#$+}_             1       21       0     2
3390  ^]^[!/@%(~;^  ^]^[!/@%(~;^             4       21       0     2
3298  (](<:{/##$%_  (](<:{/##$%_             4      31Q       0     2
3416  [][~@->^+;!!  [][~@->^+;!!             5       52       0     2
3312  -]-~)>{]\<_$  -]-~)>{]\<_$             2       21       0     2
3412  -]-;<#-+^_%(  -]-;<#-+^_%(             1      12H       0     2
3322  )%):;/#@[^&-  )%):;/#@[^&-             3      31Q       0     2
3426  !%!;">->:^\]  !%!;">->:^\]             3      12H       0     2
3401  }%}{!--;_-)]  }%}{!--;_-)]             2       62       0     2
3374  &]&/;#+}^_-#  &]&/;#+}^_-#             2       62       0     2
3328  <%<(;$_\(>$(  <%<(;$_\(>$(             2       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3355        0      2        1954        2  ...         1         0        1
3285        0      2        1951        2  ...         1         0        1
3456        0      2        1950        A  ...         1         0        1
3349        0      2        1950        2  ...         1         0        1
3431        0      2        1950        2  ...         1         0        1
3390        0      2        1954        2  ...         0         0        1
3298        0      2        1953        2  ...         1         0        1
3416        0      2        1954        2  ...         1         0        1
3312        0      2        1953        2  ...         0         0        1
3412        0      2        1950        2  ...         1         0        1
3322        0      2        1953        2  ...         0         0        1
3426        0      2        1954        2  ...         0         0        1
3401        0      2        1951        2  ...         1         0        1
3374        0      2        1951        A  ...         0         0        1
3328        0      2        1953        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3355         0         1        0         0   台南市   60      60-64
3285         1         0        0         1   台南市   63      60-64
3456         0         0        0         0   台中市   64      60-64
3349         0         0        1         0   台北市   64      60-64
3431         1         0        0         0   台北市   64      60-64
3390         0         0        0         0   雲林縣   60      60-64
3298         1         0        0         0   雲林縣   61      60-64
3416         1         0        1         0   高雄市   60      60-64
3312         1         0        0         0   新竹縣   61      60-64
3412         0         1        0         0   新北市   64      60-64
3322         0         0        0         0   台中市   61      60-64
3426         0         0        0         0   台中市   60      60-64
3401         0         0        0         0   新竹縣   63      60-64
3374         1         0        0         0   桃園市   63      60-64
3328         1         0        0         0   桃園市   61      60-64

[15 rows x 30 columns]
女性组第13组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3527  #%#\*&(-=[~~  #%#\*&(-=[~~             3       62       0     2
3484  *%*=/{"=&\#>  *%*=/{"=&\#>             3       62       0     2
3513  *]*$--+@:#*;  *]*$--+@:#*;             2      31Q       0     2
3521  @%@\={&*="/#  @%@\={&*="/#             5       62       0     2
3508  =%=\%{)=$;)@  =%=\%{)=$;)@             1      12H       0     2
3461  !]!$){]}%%\<  !]!$){]}%%\<             4       21       0     2
3603  &%&_\/"--<^^  &%&_\/"--<^^             3      31Q       0     2
3594  [][;+/${;=@[  [][;+/${;=@[             1       21       0     2
3592  @]@:->[{~%$#  @]@:->[{~%$#             4       21       0     2
3471  @]@!*&-!-&[/  @]@!*&-!-&[/             4       21       0     2
3552  @%@\={&*="/#  @%@\={&*="/#             5       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3527        0      2        1947        A  ...         0         0        1
3484        0      2        1948        A  ...         0         0        1
3513        0      2        1949        2  ...         1         0        1
3521        0      2        1945        A  ...         0         0        1
3508        0      2        1947        B  ...         0         0        1
3461        0      2        1949        2  ...         0         0        1
3603        0      2        1946        2  ...         0         0        1
3594        0      2        1945        2  ...         0         1        1
3592        0      2        1949        2  ...         1         0        1
3471        0      2        1947        2  ...         1         0        1
3552        0      2        1945        A  ...         0         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3527         0         0        0         0   台中市   67      65-69
3484         0         0        1         0   台中市   66      65-69
3513         0         0        0         0   新竹縣   65      65-69
3521         0         0        0         0   高雄市   69      65-69
3508         1         0        0         0   台北市   67      65-69
3461         1         0        0         0   台南市   65      65-69
3603         0         0        1         0   南投縣   68      65-69
3594         1         0        0         0   台北市   69      65-69
3592         1         0        0         0   台南市   65      65-69
3471         0         1        0         1   嘉義縣   67      65-69
3552         0         0        0         0   高雄市   69      65-69

[11 rows x 30 columns]
女性组第14组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3890  _]_&([!@>&~#  _]_&([!@>&~#             4      31Q       0     2
3870  %%%]#@:]]%]@  %%%]#@:]]%]@             5      31Q       0     2
4091  \]\~(<_</@[~  \]\~(<_</@[~             5      31Q       0     2
4047  )])#(@>){;~\  )])#(@>){;~\             2      31Q       0     2
3759  &]&=!-~!\;!*  &]&=!-~!\;!*             5       62       0     2
...            ...           ...           ...      ...     ...   ...
3835  \]\~(<_</@[~  \]\~(<_</@[~             5      31Q       0     2
3927  &%&#-[>\&}]{  &%&#-[>\&}]{             6      31Q       0     2
3722  +%+}})"^@=$^  +%+}})"^@=$^             6       62       0     2
3975  [%[=%&(+]\~(  [%[=%&(+]\~(             2       62       0     2
3814  -]-&{/@-]:=_  -]-&{/@-]:=_             6       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3890        0      2        1943        2  ...         0         0        1
3870        0      2        1943        2  ...         0         0        1
4091        0      2        1942        2  ...         0         0        1
4047        0      2        1942        2  ...         1         1        1
3759        0      2        1944        2  ...         0         0        1
...       ...    ...         ...      ...  ...       ...       ...      ...
3835        0      2        1942        2  ...         0         0        1
3927        0      2        1942        2  ...         0         0        1
3722        0      2        1944        A  ...         0         0        1
3975        0      2        1942        A  ...         1         0        1
3814        0      2        1942        2  ...         1         1        1

      disease4  disease5 disease6  disease7  city  Age  age_group
3890         0         0        0         0   台南市   71      70-74
3870         1         0        0         0   高雄市   71      70-74
4091         1         0        1         0   屏東縣   72      70-74
4047         0         0        0         0   桃園市   72      70-74
3759         1         0        0         0   高雄市   70      70-74
...        ...       ...      ...       ...   ...  ...        ...
3835         1         0        1         0   屏東縣   72      70-74
3927         1         0        0         0   台東縣   72      70-74
3722         0         1        0         0   花蓮縣   70      70-74
3975         0         0        0         1   桃園市   72      70-74
3814         1         0        0         0   台東縣   72      70-74

[81 rows x 30 columns]
女性组第15组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4525  ;];@=)][[_-"  ;];@=)][[_-"             4       62       0     2
4504  *%*!$$!!;#+#  *%*!$$!!;#+#             4      31Q       0     2
4227  -]-"\"*<&${(  -]-"\"*<&${(             4      31Q       0     2
4447  :]:[:/{~_=^~  :]:[:/{~_=^~             4      31Q       0     2
4557  #%#}:&[(*~+>  #%#}:&[(*~+>             4      31Q       0     2
...            ...           ...           ...      ...     ...   ...
4588  }]}!<-;(~<!&  }]}!<-;(~<!&             3      31Q       0     2
4399  ^]^~^]+<>:!)  ^]^~^]+<>:!)             5      31Q       0     2
4339  ^%^>{>-@}+>)  ^%^>{>-@}+>)             1       32       0     2
4204  /%/--{#]{=+!  /%/--{#]{=+!             4      31Q       0     2
4317  @%@@]@;>~&/#  @%@@]@;>~&/#             1       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
4525        0      2        1938        A  ...         1         0        1
4504        0      2        1937        2  ...         0         0        1
4227        0      2        1938        2  ...         1         0        1
4447        0      2        1937        2  ...         1         0        1
4557        0      2        1939        2  ...         1         0        1
...       ...    ...         ...      ...  ...       ...       ...      ...
4588        0      2        1938        2  ...         1         0        1
4399        0      2        1939        2  ...         0         0        1
4339        0      2        1939        2  ...         1         0        1
4204        0      2        1939        2  ...         1         0        1
4317        0      2        1939        A  ...         1         1        1

      disease4  disease5 disease6  disease7  city  Age  age_group
4525         0         0        0         0   雲林縣   76      75-79
4504         0         0        0         1   台南市   77      75-79
4227         1         0        0         0   台南市   76      75-79
4447         1         0        0         0   雲林縣   77      75-79
4557         1         0        0         0   雲林縣   75      75-79
...        ...       ...      ...       ...   ...  ...        ...
4588         0         0        0         0   台中市   76      75-79
4399         0         1        0         0   高雄市   75      75-79
4339         0         0        0         0   宜蘭縣   75      75-79
4204         1         1        0         0   台南市   75      75-79
4317         1         0        1         0   新北市   75      75-79

[70 rows x 30 columns]
女性组第16组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4840  }%}<^&!]>#\[  }%}<^&!]>#\[             6      31Q       0     2
4609  $%$^{"{~_-"}  $%$^{"{~_-"}             5      31Q       0     2
4759  <%<:>>^^)-$^  <%<:>>^^)-$^             4       21       0     2
4606  ;];~\<]-=;!(  ;];~\<]-=;!(             4      31Q       0     2
4713  "%">^//-^"#+  "%">^//-^"#+             3      31Q       0     2

In [209]:
nPD_d3_M = []
nPD_d3_F = []

# 使用 whole_nPD_M 字典中的分组进行采样
for i in range(18):
    nPD_d3_M.append(whole_nPD_M[i].sample(n=NP_PD_d3_F[i] * 2, replace=True))

# 使用 whole_nPD_F 字典中的分组进行采样
for i in range(18):
    nPD_d3_F.append(whole_nPD_F[i].sample(n=NP_PD_d3_M[i] * 2, replace=True))

In [210]:
for i in range(18):
    print(len(nPD_d3_M[i]))
for i in range(18):
    print(len(nPD_d3_F[i]))

0
0
0
0
0
0
0
0
0
0
0
0
18
22
112
52
54
48
0
0
0
0
0
0
0
0
10
6
0
20
8
36
42
36
28
28

In [211]:
# 为女性组数据添加一个标记列，并垂直合并
for i in range(18):
    nPD_d3_age_F = pd.concat([nPD_d3_F[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d3_age_F))
for i in range(18):

    nPD_d3_age_M = pd.concat([nPD_d3_M[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d3_age_M))
nPD_d3_age = pd.concat([nPD_d3_age_F, nPD_d3_age_M], axis=0, ignore_index=True)

print("all:", len(nPD_d3_age))
# print(nPD_d3_age)

214
306
all: 520

In [212]:
print(len(df_d3_DP_group))

260

# 結果

In [213]:
#odds ratio語法
import pandas as pd
import numpy as np
from scipy.stats import fisher_exact
import statsmodels.api as sm
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime
#合併PD與nPD
df_d3_PDandnPD=pd.concat([df_d3_DP_group,nPD_d3_age])
# 創建交叉表
contingency_table = pd.crosstab(df_d3_PDandnPD['PD'], df_d3_PDandnPD['disease6'])

# 計算odds ratio和p-value
odds_ratio, p_value = fisher_exact(contingency_table)

# 計算odds ratio的信賴區間
table = Table2x2(contingency_table.values)
confidence_interval = table.oddsratio_confint()

print(f'Odds Ratio: {odds_ratio}')
print(f'p-value: {p_value}')
print(f'Confidence Interval: {confidence_interval}')
if p_value < 0.05:
    print("\nfail")
else:
    print("\npass")
    
    nowtime = datetime.now().strftime("%Y%m%d_%H%M")
    pass_csvFileName=f'd3_pass_PDandnPD{nowtime}.csv'
    print(pass_csvFileName)    
    df_d3_PDandnPD.to_csv(f'data/{pass_csvFileName}', index=False)

Odds Ratio: 1.0425046651461747
p-value: 0.8433282764471051
Confidence Interval: (0.7081720970643828, 1.534677773039583)

pass
d3_pass_PDandnPD20241101_1824.csv

In [214]:
import pandas as pd
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime

# 假设 df_d3_PDandnPD 是您的合并数据集
df_d3_PDandnPD = pd.concat([df_d3_DP_group, nPD_d3_age])

# 存储结果的列表
results = []
sumP=0
# 遍历 disease1 到 disease7
for n in range(1, 8):
    disease_col = f'disease{n}'
    
    # 筛选出 diseaseN == 1 的样本
    # disease_data = df_d1_PDandnPD[df_d1_PDandnPD[disease_col] == 1]
    
    # 创建 PD 与当前疾病的交叉表
    contingency_table = pd.crosstab(df_d3_PDandnPD['PD'], df_d3_PDandnPD[disease_col])
    
    # 检查表格是否为 2x2
    if contingency_table.shape == (2, 2):
        # 计算 Odds Ratio 和 p 值
        odds_ratio, p_value = fisher_exact(contingency_table)
        
        # 计算置信区间
        table = Table2x2(contingency_table.values)
        confidence_interval = table.oddsratio_confint()
        
        # 记录结果
        results.append({
            'Disease': disease_col,
            'Odds Ratio': odds_ratio,
            'p-value': p_value,
            'Confidence Interval': confidence_interval
        })
        
        # 输出结果
        print(f'\n{disease_col}:')
        print(f'Odds Ratio: {odds_ratio}')
        print(f'p-value: {p_value}')
        print(f'Confidence Interval: {confidence_interval}')
        
        # 检查 p 值
        if p_value < 0.05:
             print("Y_顯著")
        else:
            print("N_不顯著")
            sumP+=1
    else:
        print(f'\n{disease_col}:')
        print("X_交叉表不是 2x2，无法计算统计量。请检查数据。")
print(sumP)

disease1:
Odds Ratio: 1.560515873015873
p-value: 0.003780210198903216
Confidence Interval: (1.1555246930991485, 2.107449372979812)
Y_顯著

disease2:
Odds Ratio: 0.9793388429752066
p-value: 1.0
Confidence Interval: (0.5447230864250996, 1.7607195165059248)
N_不顯著

disease3:
X_交叉表不是 2x2，无法计算统计量。请检查数据。

disease4:
Odds Ratio: 0.8435054773082942
p-value: 0.3127469593484432
Confidence Interval: (0.6208982134682933, 1.145922914280422)
N_不顯著

disease5:
Odds Ratio: 0.7283874923359902
p-value: 0.2073311453325159
Confidence Interval: (0.45453279215275927, 1.1672388618623697)
N_不顯著

disease6:
Odds Ratio: 1.0425046651461747
p-value: 0.8433282764471051
Confidence Interval: (0.7081720970643828, 1.534677773039583)
N_不顯著

disease7:
Odds Ratio: 0.4968421052631579
p-value: 0.05818030342446587
Confidence Interval: (0.2434742437232055, 1.0138734750233442)
N_不顯著
5

In [215]:
if sumP == 6:
    df_d3_PDandnPD.to_csv('data/out/pass6_d3.csv', index=False)
    print("\npass6_d3.csv")

In [216]:
# !ls ~/df_outData

In [217]:
# !ls ./data

In [218]:
# !cp ./data/{pass_csvFileName} ~/df_outData/

In [219]:
# !ls ~/df_outData

In [220]:
# df_d3_PDandnPD