In [441]:
import sys

from numpy.testing.print_coercion_tables import print_coercion_table

# from time import process_time_ns

# from scipy.misc.tests.test_doccer import param_doc2

print("start")
print(sys.version)
import os
import pandas as pd

os.getcwd()

start
3.8.20 (default, Oct  3 2024, 10:22:23)
[Clang 14.0.6 ]

'/Users/lai_zx/PycharmProjects/HH_DB'

### 資料載入 PD_group nPD_group

In [442]:
df_PD_group = pd.read_csv('data/PD_group_utf8.csv')
df_nPD_group = pd.read_csv('data/nPD_group_utf8.csv')

In [443]:
print(df_nPD_group.info)
print(df_PD_group.info)

<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     $]$>^"^>%]{$  $]$>^"^>%]{$             1      12H       0     1
1     /%/;#[@""^]~  /%/;#[@""^]~             4      12H       0     1
2     <]<*]#:*-:;=  <]<*]#:*-:;=             2      12H       0     1
3     }%}_~#<^!-%!  }%}_~#<^!-%!             1       62       0     1
4     @]@[$-!~)@}*  @]@[$-!~)@}*             3      12H       0     1
...            ...           ...           ...      ...     ...   ...
5445  ;];;%>:&%"-@  ;];;%>:&%"-@             4      31Q       0     2
5446  ~]~/&]!-@"(%  #%#<}-:^-{%{             5       21       0     2
5447  @%@#&$]~]&!=  @%@#&$]~]&!=             2       62       0     2
5448  +%+!<<>^/&~+  +%+!<<>^/&~+             3      31Q       0     2
5449  _%_*"$[%<-_-  _%_*"$[%<-_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      1        1984        2  ...         0         0        0
1           0      1        1981        2  ...         0         0        0
2           0      1        1982        2  ...         0         0        0
3           0      1        1981        2  ...         0         0        0
4           0      1        1982        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
5445        0      2        1929        2  ...         0         0        0
5446        0      2        1926        2  ...         0         0        0
5447        0      2        1924        2  ...         0         0        0
5448        0      2        1925        2  ...         0         0        0
5449        0      2        1927        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            0         0        0         0   台北市   30  30-34
1            0         0        0         0   雲林縣   33  30-34
2            0         0        0         0   新竹縣   32  30-34
3            0         0        0         0   新北市   33  30-34
4            0         0        0         0   彰化縣   32  30-34
...        ...       ...      ...       ...   ...  ...         ...
5445         0         0        1         0   嘉義縣   85  85~
5446         0         0        0         0   屏東縣   88  85~
5447         0         0        0         0   新竹縣   90  85~
5448         0         0        1         0   台中市   89  85~
5449         0         0        0         0   嘉義市   87  85~

[5450 rows x 30 columns]>
<bound method DataFrame.info of                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
0     )]))<@%/-@/\  )]))<@%/-@/\             1      31Q       0     2
1     )])->[[_;"}+  )])->[[_;"}+             3       62       0     2
2     )])/;&*^})\_  )])/;&*^})\_             3      31Q       0     2
3     )%):~-[#[%/=  )%):~-[#[%/=             4      31Q       0     2
4     )%)_#)]_>)-{  )%)_#)]_>)-{             3      31Q       0     1
...            ...           ...           ...      ...     ...   ...
2720  (%({_[-}]%%/  (%({_[-}]%%/             5       62       0     2
2721  (%(/:#=${(<"  (%(/:#=${(<"             1       62       0     1
2722  (%(/&<[!>=^!  (%(/&<[!>=^!             1       62       0     2
2723  (%([]$!-$\]]  (%([]$!-$\]]             4      31Q       0     2
2724  (%(&<]")^&+<  (%(&<]")^&+<             4       62       0     1

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
0           0      2        1926        2  ...         1         0        0
1           0      2        1928        2  ...         1         0        0
2           0      2        1923        2  ...         0         0        0
3           0      2        1922        2  ...         0         0        0
4           0      1        1941        2  ...         0         0        0
...       ...    ...         ...      ...  ...       ...       ...      ...
2720        0      2        1915        2  ...         0         0        1
2721        0      1        1974        2  ...         0         0        0
2722        0      2        1941        A  ...         0         0        1
2723        0      2        1933        2  ...         1         0        0
2724        0      1        1953        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age   age_group
0            1         0        0         0   宜蘭縣   88  85~
1            0         1        0         0   南投縣   86  85~
2            0         1        0         0   彰化縣   91  85~
3            0         0        0         0   雲林縣   92  85~
4            0         0        0         0   南投縣   73  70-74
...        ...       ...      ...       ...   ...  ...         ...
2720         0         0        0         0   屏東縣   99  85~
2721         0         0        0         0   台北市   40  40-44
2722         1         0        1         0   新北市   73  70-74
2723         0         0        0         0   嘉義縣   81  80-84
2724         0         0        0         0   台南市   61  60-64

[2725 rows x 30 columns]>

### disease7

In [444]:
print(len(df_PD_group.query('disease7==1')))
print(len(df_nPD_group.query('disease7==1')))

273
208

## 比例

In [445]:
# 從PD_group 抽 有 disease7 
df_d7_DP_group = (df_PD_group.query('disease7==1')).sample(70)
df_d7_nDP_group = (df_nPD_group.query('disease7==1')).sample(200)
print(len(df_d7_DP_group.query(' disease7==1')))
print(len(df_d7_nDP_group.query(' disease7==1')))

70
200

In [446]:
df_d7_DP_group['ID1_S'] = df_d7_DP_group['ID1_S'].astype(str)
df_d7_DP_group['age_group'] = df_d7_DP_group['age_group'].astype(str)
print(df_d7_DP_group.dtypes)

ID               object
ID1              object
ID1_DIVISION      int64
ID1_UNIT         object
ID_ROC            int64
ID_S              int64
ID1_ROC           int64
ID1_S            object
ID_BIRTH_Y        int64
ID1_TYPE         object
ID_RELATION     float64
ID1_AMT         float64
ID1_IDENT        object
PREM_YM           int64
ID_STATUS         int64
ID1_MARK         object
FAM_CONT_Y      float64
FAM_CONT_N      float64
ID1_CITY          int64
PD                int64
disease1          int64
disease2          int64
disease3          int64
disease4          int64
disease5          int64
disease6          int64
disease7          int64
city             object
Age               int64
age_group        object
dtype: object

In [447]:
import pandas as pd

# 假设您的 DataFrame 是 df，并且其中有一列名为 'age_groups'
# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
df_d7_DP_group['age_group'] = df_d7_DP_group['age_group'].str.strip()
# 使用 value_counts() 方法统计每个年龄组的数量
#age_group_counts =df_d7_DP_group ['age_group'].value_counts()
age_group_counts = df_d7_DP_group['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_M = df_d7_DP_group.query('ID1_S==1')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d7_DP_group.query('ID1_S==2')['age_group'].value_counts().reindex(all_age_groups, fill_value=0)
print(age_group_counts)

# 显示结果
# print(age_group_counts)
# print(age_group_counts2)
# print(age_group_counts.index.tolist())
# print(all_age_groups)

age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     2
45-49     0
50-54     5
55-59     4
60-64     4
65-69     7
70-74    10
75-79    15
80-84     8
85~      15
Name: count, dtype: int64

In [448]:
import pandas as pd

# 定义所有的年龄分组
all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']

# 数据清理
# 去除 'age_group' 列中值的前后空格
df_d7_DP_group['age_group'] = df_d7_DP_group['age_group'].str.strip()

# 确保 'ID1_S' 和 'ID' 列的数据类型正确
df_d7_DP_group['ID1_S'] = df_d7_DP_group['ID1_S'].astype(int)
df_d7_DP_group['ID'] = df_d7_DP_group['ID'].astype(str)

# 将 'age_group' 列转换为分类数据类型，确保顺序正确
df_d7_DP_group['age_group'] = pd.Categorical(df_d7_DP_group['age_group'], categories=all_age_groups, ordered=True)

# 按性别过滤数据
# 男性数据（ID1_S == 1）
df_d7_DP_M = df_d7_DP_group[df_d7_DP_group['ID1_S'] == 1]
df_d7_DP_F = df_d7_DP_group[df_d7_DP_group['ID1_S'] == 2]

# 按年龄组统计男性的 ID 数量
age_group_counts_M = df_d7_DP_M.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
age_group_counts_F = df_d7_DP_F.groupby('age_group')['ID'].count().reindex(all_age_groups, fill_value=0)
# 显示结果
print("男性各年龄组的 ID 数量：")
print(age_group_counts_M)
print(age_group_counts_F)
NP_PD_d7_M = age_group_counts_M.to_numpy()
NP_PD_d7_F = age_group_counts_F.to_numpy()
print(NP_PD_d7_M)

男性各年龄组的 ID 数量：
age_group
0-4       0
5-9       0
10-14     0
15-19     0
20-24     0
25-29     0
30-34     0
35-39     0
40-44     2
45-49     0
50-54     5
55-59     3
60-64     4
65-69     0
70-74     4
75-79     6
80-84     8
85~      15
Name: ID, dtype: int64
age_group
0-4      0
5-9      0
10-14    0
15-19    0
20-24    0
25-29    0
30-34    0
35-39    0
40-44    0
45-49    0
50-54    0
55-59    1
60-64    0
65-69    7
70-74    6
75-79    9
80-84    0
85~      0
Name: ID, dtype: int64
[ 0  0  0  0  0  0  0  0  2  0  5  3  4  0  4  6  8 15]

In [449]:
df_d7_DP_group.dtypes

ID                object
ID1               object
ID1_DIVISION       int64
ID1_UNIT          object
ID_ROC             int64
ID_S               int64
ID1_ROC            int64
ID1_S              int64
ID_BIRTH_Y         int64
ID1_TYPE          object
ID_RELATION      float64
ID1_AMT          float64
ID1_IDENT         object
PREM_YM            int64
ID_STATUS          int64
ID1_MARK          object
FAM_CONT_Y       float64
FAM_CONT_N       float64
ID1_CITY           int64
PD                 int64
disease1           int64
disease2           int64
disease3           int64
disease4           int64
disease5           int64
disease6           int64
disease7           int64
city              object
Age                int64
age_group       category
dtype: object

In [450]:
import pandas as pd

who2000 = pd.read_csv('data/who2000.csv')
# 定义所有可能的 `ID1_S` 和 `age_group` 组合
all_ID1_S = ['1', '2']
#all_age_groups = who2000['AGE']
# 确保 ID1_S 是整数类型
df_d7_nDP_group['ID1_S'] = df_d7_nDP_group['ID1_S'].astype(int)

# 确保 age_group 列没有多余空格
df_d7_nDP_group['age_group'] = df_d7_nDP_group['age_group'].str.strip()

all_age_groups = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39',
                  '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74',
                  '75-79', '80-84', '85~']
# 去除 'age_group' 列中值的前后空格
df_d7_DP_group['age_group'] = df_d7_DP_group['age_group'].str.strip()

# 创建 MultiIndex，包含所有可能的组合
index = pd.MultiIndex.from_product([all_ID1_S, all_age_groups], names=['ID1_S', 'age_group'])

# 男性组
# 男性组
whole_nPD_M = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d7_nDP_group[(df_d7_nDP_group['ID1_S'] == 1) & (df_d7_nDP_group['age_group'] == all_age_groups[i])]
    # 打印每个分组数据以调试
    #print(f"男性组第{i}组数据:\n", data)
    whole_nPD_M[i] = data if not data.empty else pd.DataFrame(columns=df_d7_nDP_group.columns).reindex(
        index=[(1, all_age_groups[i])])

# 女性组
whole_nPD_F = {}
for i in range(18):
    # 获取分组数据，若为空，则以空DataFrame代替
    data = df_d7_nDP_group.query(f'ID1_S == 2 and age_group == "{all_age_groups[i]}"')
    # 打印每个分组数据以调试
    print(f"女性组第{i}组数据:\n", data)
    whole_nPD_F[i] = data if not data.empty else pd.DataFrame(columns=df_d7_nDP_group.columns).reindex(
        index=[(2, all_age_groups[i])])

女性组第0组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第1组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第2组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第3组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第4组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第5组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第6组数据:
 Empty DataFrame
Columns: [ID, ID1, ID1_DIVISION, ID1_UNIT, ID_ROC, ID_S, ID1_ROC, ID1_S, ID_BIRTH_Y, ID1_TYPE, ID_RELATION, ID1_AMT, ID1_IDENT, PREM_YM, ID_STATUS, ID1_MARK, FAM_CONT_Y, FAM_CONT_N, ID1_CITY, PD, disease1, disease2, disease3, disease4, disease5, disease6, disease7, city, Age, age_group]
Index: []

[0 rows x 30 columns]
女性组第7组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2871  "]"]+<:#"]@}  "]"]+<:#"]@}             1      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2871        0      2        1977        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2871         0         0        0         1   新北市   37      35-39

[1 rows x 30 columns]
女性组第8组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
2951  {%{>{<;_#]+%  {%{>{<;_#]+%             1      12H       0     2
2955  <]<;}>(=\=%#  <]<;}>(=\=%#             3       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
2951        0      2        1971        2  ...         0         1        0
2955        0      2        1970        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
2951         0         0        0         1   台北市   43      40-44
2955         0         0        0         1   彰化縣   44      40-44

[2 rows x 30 columns]
女性组第9组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3014  \%\+=#%:[]_\  \%\+=#%:[]_\             3      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3014        0      2        1965        1  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3014         0         0        0         1   彰化縣   49      45-49

[1 rows x 30 columns]
女性组第10组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3121  >]>:($+;%_*"  >]>:($+;%_*"             1       32       0     2
3038  +]+!}]%(>-:@  +]+!}]%(>-:@             5      12H       0     2
3098  ^%^>+[\$=[;~  ^%^>+[\$=[;~             4      11B       0     2
3119  :]:\=>@(+]~&  :]:\=>@(+]~&             4      31Q       0     2
3069  +]+]:<":#&{>  +]+]:<":#&{>             5       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3121        0      2        1961        2  ...         0         0        0
3038        0      2        1964        2  ...         0         1        0
3098        0      2        1963        2  ...         0         0        0
3119        0      2        1961        2  ...         0         0        0
3069        0      2        1960        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3121         0         0        0         1   新北市   53      50-54
3038         0         0        0         1   高雄市   50      50-54
3098         0         0        0         1   雲林縣   51      50-54
3119         1         0        0         1   雲林縣   53      50-54
3069         0         0        0         1   高雄市   54      50-54

[5 rows x 30 columns]
女性组第11组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3159  -%-]*"(&(==(  -%-]*"(&(==(             5       21       0     2
3256  #%#$*-<_\&=&  #%#$*-<_\&=&             3       21       0     2
3218  ~]~&:"_):%["  ~]~&:"_):%["             1       21       0     2
3266  $%$][<%(:={\  $%$][<%(:={\             3       21       0     2
3203  ~]~)^@!"@<\$  ~]~)^@!"@<\$             1      12H       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3159        0      2        1959        2  ...         1         0        1
3256        0      2        1955        2  ...         0         0        0
3218        0      2        1958        2  ...         1         0        0
3266        0      2        1959        2  ...         0         0        0
3203        0      2        1958        2  ...         0         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3159         1         0        0         1   屏東縣   55      55-59
3256         1         0        0         1   台中市   59      55-59
3218         0         0        0         1   台北市   56      55-59
3266         0         0        0         1   台中市   55      55-59
3203         0         1        0         1   台北市   56      55-59

[5 rows x 30 columns]
女性组第12组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3293  "]"+##$({++:  "]"+##$({++:             4      31Q       0     2
3285  {]{$~[%_\&*_  {]{$~[%_\&*_             4       32       0     2
3450  *]*>@[>]^({>  *]*>@[>]^({>             6      31Q       0     2
3307  "]"+##$({++:  "]"+##$({++:             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3293        0      2        1950        2  ...         0         1        0
3285        0      2        1951        2  ...         1         0        1
3450        0      2        1951        2  ...         0         0        0
3307        0      2        1950        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3293         0         0        0         1   嘉義縣   64      60-64
3285         1         0        0         1   台南市   63      60-64
3450         0         0        0         1   台東縣   63      60-64
3307         0         0        0         1   嘉義縣   64      60-64

[4 rows x 30 columns]
女性组第13组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3485  *%*/\&"+(+(;  *%*/\&"+(+(;             2      31Q       0     2
3547  @]@:]";@$$:"  @]@:]";@$$:"             6       62       0     2
3507  =%==_<~&/=:@  =%==_<~&/=:@             3      31Q       0     2
3471  @]@!*&-!-&[/  @]@!*&-!-&[/             4       21       0     2
3511  }%}_{[^{:=^}  }%}_{[^{:=^}             1       21       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3485        0      2        1945        2  ...         0         0        1
3547        0      2        1947        A  ...         1         0        0
3507        0      2        1948        2  ...         0         0        0
3471        0      2        1947        2  ...         1         0        1
3511        0      2        1948        2  ...         0         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3485         1         0        0         1   新竹市   69      65-69
3547         0         0        0         1   台東縣   67      65-69
3507         0         0        0         1   台中市   66      65-69
3471         0         1        0         1   嘉義縣   67      65-69
3511         0         0        0         1   台北市   66      65-69

[5 rows x 30 columns]
女性组第14组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
3755  !%!(*[{(:\<~  !%!(*[{(:\<~             1       62       0     2
3726  <%<*_#={{^"%  <%<*_#={{^"%             4      31Q       0     2
3975  [%[=%&(+]\~(  [%[=%&(+]\~(             2       62       0     2
3657  -%-~~/#\&{&-  -%-~~/#\&{&-             5       62       0     2
3744  >%>\>@}={"/&  >%>\>@}={"/&             1       21       0     2
4142  !%!(*[{(:\<~  !%!(*[{(:\<~             1       62       0     2
3613  -%-!%"#[)[%\  -%-!%"#[)[%\             4      31Q       0     2
4102  >%>\>@}={"/&  >%>\>@}={"/&             1       21       0     2
3645  -%-]_&/-![>&  -%-]_&/-![>&             1       62       0     2
3713  :%:_""[]-#):  :%:_""[]-#):             4      31Q       0     2
3863  !%![->]_]::}  !%![->]_]::}             4      31Q       0     2
4118  <%<*_#={{^"%  <%<*_#={{^"%             4      31Q       0     2
3699  ]%]}}<[!$&<"  ]%]}}<[!$&<"             1       62       0     2
4137  <]<@"->/_*;>  <]<@"->/_*;>             5       32       0     2
4007  ~%~"${$]^<(@  ~%~"${$]^<(@             3       62       0     2
4033  (%(}^/^"^%\;  (%(}^/^"^%\;             2       62       0     2
3662  :]:>#@+<>"^&  :]:>#@+<>"^&             5      31Q       0     2
4025  )])&}@;(\/\)  )])&}@;(\/\)             5       62       0     2
3631  [%[=%&(+]\~(  [%[=%&(+]\~(             2       62       0     2
3612  -]-^><}+>/<)  -]-^><}+>/<)             5      31Q       0     2
4023  \]\++>^-++=]  \]\++>^-++=]             1       62       0     2
3669  )%)}}<!/$/^-  )%)}}<!/$/^-             1       62       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
3755        0      2        1941        A  ...         0         0        1
3726        0      2        1942        2  ...         1         0        0
3975        0      2        1942        A  ...         1         0        1
3657        0      2        1941        2  ...         0         0        0
3744        0      2        1940        2  ...         0         0        1
4142        0      2        1941        A  ...         0         0        1
3613        0      2        1940        2  ...         1         1        0
4102        0      2        1940        2  ...         0         0        1
3645        0      2        1943        2  ...         0         0        0
3713        0      2        1944        2  ...         1         0        1
3863        0      2        1942        2  ...         0         0        1
4118        0      2        1942        2  ...         1         0        0
3699        0      2        1942        A  ...         0         0        0
4137        0      2        1942        2  ...         1         0        0
4007        0      2        1941        2  ...         0         1        1
4033        0      2        1943        A  ...         1         0        0
3662        0      2        1940        2  ...         1         0        1
4025        0      2        1940        2  ...         1         0        0
3631        0      2        1942        A  ...         1         0        1
3612        0      2        1940        2  ...         1         0        0
4023        0      2        1941        A  ...         1         0        0
3669        0      2        1944        A  ...         1         1        0

      disease4  disease5 disease6  disease7  city  Age  age_group
3755         1         1        1         1   新北市   73      70-74
3726         0         0        0         1   嘉義市   72      70-74
3975         0         0        0         1   桃園市   72      70-74
3657         0         0        0         1   高雄市   73      70-74
3744         1         0        0         1   台北市   74      70-74
4142         1         1        1         1   新北市   73      70-74
3613         0         0        0         1   嘉義縣   74      70-74
4102         1         0        0         1   台北市   74      70-74
3645         0         1        0         1   新北市   71      70-74
3713         0         0        0         1   嘉義市   70      70-74
3863         0         0        0         1   台南市   72      70-74
4118         0         0        0         1   嘉義市   72      70-74
3699         0         0        0         1   基隆市   72      70-74
4137         1         0        0         1   高雄市   72      70-74
4007         0         0        0         1   南投縣   73      70-74
4033         0         0        0         1   桃園市   71      70-74
3662         0         0        0         1   屏東縣   74      70-74
4025         1         0        0         1   高雄市   74      70-74
3631         0         0        0         1   桃園市   72      70-74
3612         0         0        0         1   屏東縣   74      70-74
4023         0         0        0         1   台北市   73      70-74
3669         0         0        0         1   新北市   70      70-74

[22 rows x 30 columns]
女性组第15组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4531  ^%^(">"["&[^  ^%^(">"["&[^             4      31Q       0     2
4191  <%<}]#$*(%~>  <%<}]#$*(%~>             5      31Q       0     2
4293  (](_~-^+[~{-  (](_~-^+[~{-             6      31Q       0     2
4510  [][~~]!)$=&#  [][~~]!)$=&#             4       62       0     2
4495  (](:]/]~__>+  (](:]/]~__>+             6      31Q       0     2
4579  }]}!%>)"/"{_  }]}!%>)"/"{_             4      31Q       0     2
4347  (](:*&^%/[+_  (](:*&^%/[+_             5      31Q       0     2
4269  :]:!))$:+^{;  :]:!))$:+^{;             2      31Q       0     2
4504  *%*!$$!!;#+#  *%*!$$!!;#+#             4      31Q       0     2
4571  >%>%;/"%^[[]  >%>%;/"%^[[]             5       62       0     2
4311  /]/^-{>!**^"  /]/^-{>!**^"             1      31Q       0     2
4323  (](:*&^%/[+_  (](:*&^%/[+_             5      31Q       0     2
4400  {]{_~#>%~~_-  {]{_~#>%~~_-             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
4531        0      2        1939        2  ...         1         0        0
4191        0      2        1937        2  ...         1         0        1
4293        0      2        1935        2  ...         1         0        0
4510        0      2        1936        A  ...         1         0        0
4495        0      2        1935        2  ...         0         0        0
4579        0      2        1936        2  ...         1         0        0
4347        0      2        1937        2  ...         0         0        0
4269        0      2        1938        2  ...         0         0        0
4504        0      2        1937        2  ...         0         0        1
4571        0      2        1936        A  ...         0         0        0
4311        0      2        1936        2  ...         1         0        1
4323        0      2        1937        2  ...         0         0        0
4400        0      2        1939        2  ...         1         0        1

      disease4  disease5 disease6  disease7  city  Age  age_group
4531         0         0        0         1   台南市   75      75-79
4191         0         0        0         1   屏東縣   77      75-79
4293         0         0        0         1   花蓮縣   79      75-79
4510         0         0        0         1   嘉義縣   78      75-79
4495         0         0        1         1   台東縣   79      75-79
4579         1         0        0         1   台南市   78      75-79
4347         0         0        0         1   屏東縣   77      75-79
4269         0         0        0         1   新竹市   76      75-79
4504         0         0        0         1   台南市   77      75-79
4571         0         0        0         1   高雄市   78      75-79
4311         0         0        0         1   新北市   78      75-79
4323         0         0        0         1   屏東縣   77      75-79
4400         0         0        0         1   嘉義縣   75      75-79

[13 rows x 30 columns]
女性组第16组数据:
                 ID           ID1  ID1_DIVISION ID1_UNIT  ID_ROC  ID_S  \
4820  {]{-=<<&:;\@  {]{-=<<&:;\@             2      31Q       0     2
4791  ~%~{%[/*<>{[  ~%~{%[/*<>{[             1       62       0     2
4604  :]:*]<=+}]*(  :]:*]<=+}]*(             5      31Q       0     2
4648  ^%^=/)[_>{%%  ^%^=/)[_>{%%             4      31Q       0     2
4817  !%!(")/$%!!-  !%!(")/$%!!-             2      31Q       0     2
4845  :]:]&""~!]->  :]:]&""~!]->             1      31Q       0     2
4837  *%*}!"=">:_-  *%*}!"=">:_-             4      31Q       0     2
4784  [%[*]{-#;"%;  [%[*]{-#;"%;             4      31Q       0     2
4664  $]$=%#&/}!#)  $]$=%#&/}!#)             5      12H       0     2
4752  $]$=%#&/}!#)  $]$=%#&/}!#)             5      12H       0     2
4699  <%<:>>^^)-$^  <%<:>>^^)-$^             4       21       0     2
4760  ;];$>>_@!:@]  ;];$>>_@!:@]             2      31Q       0     2
4680  :]:*}[-"!)"@  :]:*}[-"!)"@             4      31Q       0     2
4695  _]_>*$/>}<_%  _]_>*$/>}<_%             4      31Q       0     2
4759  <%<:>>^^)-$^  <%<:>>^^)-$^             4       21       0     2
4861  =]=@["*}][#*  =]=@["*}][#*             4      31Q       0     2

      ID1_ROC  ID1_S  ID_BIRTH_Y ID1_TYPE  ...  disease1  disease2 disease3  \
4820        0      2        1933        2  ...         1         0        0
4791        0      2        1933        A  ...         0         0        0
4604        0      2        1933        2  ...         0         0        0
4648        0      2        1932        2  ...         0         1        0
4817        0      2        1933        2  ...         1         0        1
4845        0      2        1930        2  ...         1         0        1
4837        0      2        1932        2  ...         1         0        1
4784        0      2        1932        2  ...         1         0        1
4664        0      2        1932        1  ...         1         0        0
4752        0      2        1932        1  ...         1         0        0
4699        0      2        1934        2  ...         1         0        1
4760        0      2        1934        2  ...         0         0        0
4680        0      2        1932        2  ...         0         0        1
4695        0      2        1931        2  ...         1         0        1
4759        0      2        1934        2  ...         1         0        1
4861        0      2        1933        2  ...         1         0        0

      disease4  disease5 disease6  disease7  city  Age  age_group
4820         0         0        0         1   桃園市   81      80-84
4791         0         0        0         1   台北市   81      80-84
4604         0         0        0         1   屏東縣   81      80-84
4648         0         0        0         1   台南市   82      80-84
4817         0         0        0         1   桃園市   81      80-84
4845         1         0        0         1   宜蘭縣   84      80-84

In [451]:
nPD_d7_M = []
nPD_d7_F = []

# 使用 whole_nPD_M 字典中的分组进行采样
for i in range(18):
    nPD_d7_M.append(whole_nPD_M[i].sample(n=NP_PD_d7_F[i] * 2, replace=True))

# 使用 whole_nPD_F 字典中的分组进行采样
for i in range(18):
    nPD_d7_F.append(whole_nPD_F[i].sample(n=NP_PD_d7_M[i] * 2, replace=True))

In [452]:
for i in range(18):
    print(len(nPD_d7_M[i]))
for i in range(18):
    print(len(nPD_d7_F[i]))

0
0
0
0
0
0
0
0
0
0
0
2
0
14
12
18
0
0
0
0
0
0
0
0
0
0
4
0
10
6
8
0
8
12
16
30

In [453]:
# 为女性组数据添加一个标记列，并垂直合并
for i in range(18):
    nPD_d7_age_F = pd.concat([nPD_d7_F[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d7_age_F))
for i in range(18):

    nPD_d7_age_M = pd.concat([nPD_d7_M[i] for i in range(18)], axis=0, ignore_index=True)
print(len(nPD_d7_age_M))
nPD_d7_age = pd.concat([nPD_d7_age_F, nPD_d7_age_M], axis=0, ignore_index=True)

print("all:", len(nPD_d7_age))
# print(nPD_d7_age)

94
46
all: 140

In [454]:
print(len(df_d7_DP_group))

70

# 結果

In [455]:
# #odds ratio語法
# import pandas as pd
# import numpy as np
# from scipy.stats import fisher_exact
# import statsmodels.api as sm
# from statsmodels.stats.contingency_tables import Table2x2
# from datetime import datetime
# #合併PD與nPD
# df_d7_PDandnPD=pd.concat([df_d7_DP_group,nPD_d7_age])
# # 創建交叉表
# contingency_table = pd.crosstab(df_d7_PDandnPD['PD'], df_d7_PDandnPD['disease7'])
# print(contingency_table.shape)
# # 計算odds ratio和p-value
# odds_ratio, p_value = fisher_exact(contingency_table)
# 
# # 計算odds ratio的信賴區間
# table = Table2x2(contingency_table.values)
# confidence_interval = table.oddsratio_confint()
# print(confidence_interval.shape)
# print(f'Odds Ratio: {odds_ratio}')
# print(f'p-value: {p_value}')
# print(f'Confidence Interval: {confidence_interval}')
# if p_value < 0.05:
#     print("\nfail")
# else:
#     print("\npass")
#     
#     nowtime = datetime.now().strftime("%Y%m%d_%H%M")
#     pass_csvFileName=f'd7_pass_PDandnPD{nowtime}.csv'
#     print(pass_csvFileName)    
#     df_d7_PDandnPD.to_csv(f'data/{pass_csvFileName}', index=False)

In [456]:
import pandas as pd
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2
from datetime import datetime

# 假设 df_d7_PDandnPD 是您的合并数据集
df_d7_PDandnPD = pd.concat([df_d7_DP_group, nPD_d7_age])

# 存储结果的列表
results = []
sumP=0
# 遍历 disease1 到 disease7
for n in range(1, 8):
    disease_col = f'disease{n}'
    
    # 筛选出 diseaseN == 1 的样本
    # disease_data = df_d1_PDandnPD[df_d1_PDandnPD[disease_col] == 1]
    
    # 创建 PD 与当前疾病的交叉表
    contingency_table = pd.crosstab(df_d7_PDandnPD['PD'], df_d7_PDandnPD[disease_col])
    
    # 检查表格是否为 2x2
    if contingency_table.shape == (2, 2):
        # 计算 Odds Ratio 和 p 值
        odds_ratio, p_value = fisher_exact(contingency_table)
        
        # 计算置信区间
        table = Table2x2(contingency_table.values)
        confidence_interval = table.oddsratio_confint()
        
        # 记录结果
        results.append({
            'Disease': disease_col,
            'Odds Ratio': odds_ratio,
            'p-value': p_value,
            'Confidence Interval': confidence_interval
        })
        
        # 输出结果
        print(f'\n{disease_col}:')
        print(f'Odds Ratio: {odds_ratio}')
        print(f'p-value: {p_value}')
        print(f'Confidence Interval: {confidence_interval}')
        
        # 检查 p 值
        if p_value < 0.05:
             print("Y_顯著")
        else:
            print("N_不顯著")
            sumP+=1
    else:
        print(f'\n{disease_col}:')
        print("X_交叉表不是 2x2，无法计算统计量。请检查数据。")
print(sumP)

disease1:
Odds Ratio: 1.0296610169491525
p-value: 1.0
Confidence Interval: (0.5763962189684261, 1.8393628808360374)
N_不顯著

disease2:
Odds Ratio: 2.4516129032258065
p-value: 0.09671726793713455
Confidence Interval: (0.8508989101563956, 7.063595634596063)
N_不顯著

disease3:
Odds Ratio: 0.6174863387978142
p-value: 0.3315133180068691
Confidence Interval: (0.27301392238713706, 1.3965931673669603)
N_不顯著

disease4:
Odds Ratio: 1.517751479289941
p-value: 0.2805841187623195
Confidence Interval: (0.7653580082854852, 3.00979349265207)
N_不顯著

disease5:
Odds Ratio: 0.36363636363636365
p-value: 0.07022504255589042
Confidence Interval: (0.1192724740993781, 1.108649803377955)
N_不顯著

disease6:
Odds Ratio: 0.6464646464646465
p-value: 0.5867003475175887
Confidence Interval: (0.2006582686069642, 2.0827277242546476)
N_不顯著

disease7:
X_交叉表不是 2x2，无法计算统计量。请检查数据。
6

In [457]:
# !ls ~/df_outData

In [458]:
if sumP == 6:
    df_d7_PDandnPD.to_csv('data/out/pass6_d7.csv', index=False)
    print("\npass6_d7.csv")

pass6_d7.csv

In [459]:
# !ls ./data

In [460]:
# !cp ./data/{pass_csvFileName} ~/df_outData/

In [461]:
# !ls ~/df_outData

In [462]:
# df_d7_PDandnPD